### ISSUE TITLE
Missing jdk.aot.jmod on Windows x86 build

### ISSUE THREAD

**Issue by sekkingsoft** [AdoptOpenJDK/openjdk-support#100]
jdk.aot.jmod is not included in AdoptOpenJDK 14 for Windows x86 (32-bit) I need to include it in my jre runtime image for 32-bit windows, as GSON depends on it.

* **Platform and architecture (e.g. Linux/x64**:  Windows 10 Pro 1909

* **Java version (from "java --version") e.g. 1.8.0_181, 11.0.4+11 etc.**:  AdoptOpenJDK (build 14.0.1+7)

* **Variant e.g. HotSpot or OpenJ9**: HotSpot

* **Have you tested it with other vendors' java**: No. As far as I know, AdpotOpenJdk is the only one still supporting 32bit Windows

* **Steps to reproduce**: Download and install/extract AdoptOpenJDK 14 for Windows x86. See that jdk.aot.jmod is not located in jmods-directory.

* **Error messsage and/or description of what is not working as expected**: I need jdk.aot in my custom runtime for 32-bit Windows.

**Comment by aahlenst** [comment]
Both Azul Zulu for Windows on x86 as well as AdoptOpenJDK for Windows on x86 lack the module jdk.aot. Azul Zulu does not have it on Linux, either. @jerboaa @karianna I assume it's not supported on x86? https://openjdk.java.net/jeps/295 indicates that, too, but I'm not sure whether the JEP is relevant.

With AdoptOpenJDK 14.0.1 for x86:

```
> bin/java -version
openjdk version "14.0.1" 2020-04-14
OpenJDK Runtime Environment AdoptOpenJDK (build 14.0.1+7)
OpenJDK Client VM AdoptOpenJDK (build 14.0.1+7, mixed mode, sharing)
> bin/java --list-modules | Select-String -Pattern "aot"
```

With Azul Zulu 14.0.1 for x86:

```
> bin/java -version
openjdk version "14.0.1" 2020-04-14
OpenJDK Runtime Environment Zulu14.28+21-CA (build 14.0.1+8)
OpenJDK Client VM Zulu14.28+21-CA (build 14.0.1+8, mixed mode, sharing)
> bin/java --list-modules | Select-String -Pattern "aot"
````

With OpenJDK 14.0.1 for AMD64:

```
> bin/java -version
openjdk version "14.0.1" 2020-04-14
OpenJDK Runtime Environment (build 14.0.1+7)
OpenJDK 64-Bit Server VM (build 14.0.1+7, mixed mode, sharing)
> bin/java --list-modules | Select-String -Pattern "aot"

jdk.aot@14.0.1
```

**Comment by jerboaa** [comment]
@aahlenst I'm not sure which platforms jaotc is supported these days. You are correct. Initially it was Linux x86_64 only.

**Comment by aahlenst** [comment]
I found https://bugs.openjdk.java.net/browse/JDK-8172670 ("AOT Platform Support for Windows and Mac OS X x64") which says x86_64 only.

@sekkingsoft Looks like lack of x86 support isn't an accident and not our fault. Considering that x86 (32 bit) support isn't a high priority anymore, it is unlikely that anybody wants to do something about it. Maybe replacing Gson would be an option for you? [Moshi](https://github.com/square/moshi) is a re-thinking of Gson by the same authors, features code generation and even runs on Android (Java 8 language level).
