### ISSUE TITLE
gpg: no valid OpenPGP data found.

### ISSUE THREAD

**Issue by DeepanSaha** [AdoptOpenJDK/openjdk-support#103]
* **Platform and architecture (e.g. Linux/x64**: Ubuntu

* **Java version (from "java --version") e.g. 1.8.0_181, 11.0.4+11 etc.**:

* **Variant e.g. HotSpot or OpenJ8**:

* **Have you tested it with other vendors' java**:No

* **Steps to reproduce**:

* **Error messsage and/or description of what is not working as expected**:
wget -qO - https://adoptopenjdk.jfrog.io/adoptopenjdk/api/gpg/key/public | sudo apt-key add -
gpg: no valid OpenPGP data found.

While running the command getting the error.

**Comment by aahlenst** [comment]
Probably an intermittent error. It's working fine, now.

**Comment by DeepanSaha** [comment]
Still facing the same issue.

**Comment by aahlenst** [comment]
@DeepanSaha Please show what you’re getting from https://adoptopenjdk.jfrog.io/adoptopenjdk/api/gpg/key/public.

**Comment by DeepanSaha** [comment]
Ign:6 https://adoptopenjdk.jfrog.io/adoptopenjdk/deb xenial InRelease
Hit:7 https://adoptopenjdk.jfrog.io/adoptopenjdk/deb xenial Release
Err:8 https://adoptopenjdk.jfrog.io/adoptopenjdk/deb xenial Release.gpg
  Unknown error executing apt-key
Reading package lists... Done
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://adoptopenjdk.jfrog.io/adoptopenjdk/deb xenial Release: Unknown error executing apt-key
W: Failed to fetch https://adoptopenjdk.jfrog.io/adoptopenjdk/deb/dists/xenial/Release.gpg  Unknown error executing apt-key
W: Some index files failed to download. They have been ignored, or old ones used instead.
root@dcsvm0063:/var/lib/apt/lists# wget -qO - https://adoptopenjdk.jfrog.io/adoptopenjdk/api/gpg/key/public | sudo apt-key add -
gpg: no valid OpenPGP data found.
root@dcsvm0063:/var/lib/apt/lists# sudo add-apt-repository --yes https://adoptopenjdk.jfrog.io/adoptopenjdk/deb/
root@dcsvm0063:/var/lib/apt/lists# apt-get update
Hit:1 http://us.archive.ubuntu.com/ubuntu xenial InRelease
Hit:2 http://security.ubuntu.com/ubuntu xenial-security InRelease
Hit:3 http://us.archive.ubuntu.com/ubuntu xenial-updates InRelease
Hit:4 http://ppa.launchpad.net/linuxuprising/java/ubuntu xenial InRelease
Hit:5 http://us.archive.ubuntu.com/ubuntu xenial-backports InRelease
Ign:6 https://adoptopenjdk.jfrog.io/adoptopenjdk/deb xenial InRelease
Hit:7 https://adoptopenjdk.jfrog.io/adoptopenjdk/deb xenial Release
Err:8 https://adoptopenjdk.jfrog.io/adoptopenjdk/deb xenial Release.gpg
  Unknown error executing apt-key
Reading package lists... Done
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://adoptopenjdk.jfrog.io/adoptopenjdk/deb xenial Release: Unknown error executing apt-key
W: Failed to fetch https://adoptopenjdk.jfrog.io/adoptopenjdk/deb/dists/xenial/Release.gpg  Unknown error executing apt-key
W: Some index files failed to download. They have been ignored, or old ones used instead.


Still facing the error after updating the key and running update command.

**Comment by DeepanSaha** [comment]
Can you provide me steps so that i can successfully installed the openjdk.

**Comment by DeepanSaha** [comment]
Issue resolved.

**Comment by DeepanSaha** [comment]
# apt-get update
Hit:1 http://us.archive.ubuntu.com/ubuntu xenial InRelease
Get:2 http://security.ubuntu.com/ubuntu xenial-security InRelease [109 kB]
Get:3 http://us.archive.ubuntu.com/ubuntu xenial-updates InRelease [109 kB]
Hit:4 http://cz.archive.ubuntu.com/ubuntu xenial InRelease
Get:5 http://us.archive.ubuntu.com/ubuntu xenial-backports InRelease [107 kB]
Fetched 325 kB in 0s (374 kB/s)
Reading package lists... Done
W: Target Packages (main/binary-amd64/Packages) is configured multiple times in /etc/apt/sources.list:47 and /etc/apt/sources.list:64
W: Target Packages (main/binary-i386/Packages) is configured multiple times in /etc/apt/sources.list:47 and /etc/apt/sources.list:64
W: Target Packages (main/binary-all/Packages) is configured multiple times in /etc/apt/sources.list:47 and /etc/apt/sources.list:64
W: Target Translations (main/i18n/Translation-en_US) is configured multiple times in /etc/apt/sources.list:47 and /etc/apt/sources.list:64
W: Target Translations (main/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list:47 and /etc/apt/sources.list:64
E: The method driver /usr/lib/apt/methods/https could not be found.
N: Is the package apt-transport-https installed?
E: Failed to fetch https://adoptopenjdk.jfrog.io/adoptopenjdk/deb/dists/xenial/InRelease
E: Some index files failed to download. They have been ignored, or old ones used instead.
W: Target Packages (main/binary-amd64/Packages) is configured multiple times in /etc/apt/sources.list:47 and /etc/apt/sources.list:64
W: Target Packages (main/binary-i386/Packages) is configured multiple times in /etc/apt/sources.list:47 and /etc/apt/sources.list:64
W: Target Packages (main/binary-all/Packages) is configured multiple times in /etc/apt/sources.list:47 and /etc/apt/sources.list:64
W: Target Translations (main/i18n/Translation-en_US) is configured multiple times in /etc/apt/sources.list:47 and /etc/apt/sources.list:64
W: Target Translations (main/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list:47 and /etc/apt/sources.list:64


While running the update command getting the error that not able to fetch. It was working fine when i am installing kn other server but suddenly showing this error.

**Comment by aahlenst** [comment]
The fix is in the output you provided:

```
E: The method driver /usr/lib/apt/methods/https could not be found.
N: Is the package apt-transport-https installed?
```

**Comment by DeepanSaha** [comment]
Resolved. Thanks for the help.
