### ISSUE TITLE
Incorrect FontMetrics on Windows via PrinterJob Graphics

### ISSUE THREAD

**Issue by teamacs** [AdoptOpenJDK/openjdk-support#105]
On Windows, the FontMetrics returned from Graphics.getFontMetrics(Font) within a PrinterJob are incorrect if the PageFormat has had the orientation explicitly set to PageFormat.LANDSCAPE or PageFormat.REVERSE_LANDSCAPE.  The issue is not present when explicitly setting the orientation to PageFormat.PORTRAIT. The attached code demonstrates the problem.

[JPSFontMetrics.zip](https://github.com/AdoptOpenJDK/openjdk-build/files/2287290/JPSFontMetrics.zip)

**Comment by karianna** [comment]
> @karianna This seems like an support issue rather than build. Could this be transferred over to https://github.com/AdoptOpenJDK/openjdk-support?

I think it is a build issue, I think we may need to change a native lib we're compiling with / bundling

**Comment by aahlenst** [comment]
https://bugs.openjdk.java.net/browse/JDK-8213453
https://bugs.openjdk.java.net/browse/JDK-8139178

Was fixed with 12, 11.0.4 and 8u232.
