### ISSUE TITLE
apt: Hash Sum mismatch

### ISSUE THREAD

**Issue by kosakosinski** [AdoptOpenJDK/openjdk-support#107]
* **Platform and architecture (e.g. Linux/x64**: Ubuntu 18.04 x64 on VirtualBox with Vagrant

* **Java version (from "java --version") e.g. 1.8.0_181, 11.0.4+11 etc.**:

* **Variant e.g. HotSpot or OpenJ9**: HotSpot

* **Have you tested it with other vendors' java**: No

* **Steps to reproduce**:
vagrant init hashicorp/bionic64 --box-version 1.0.282
vagrant up
vagrant ssh

* **Error messsage and/or description of what is not working as expected**:
vagrant@vagrant:~$ sudo apt-get install adoptopenjdk-8-hotspot
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following packages were automatically installed and are no longer required:
  linux-image-unsigned-4.15.0-55-generic linux-modules-4.15.0-55-generic
Use 'sudo apt autoremove' to remove them.
The following additional packages will be installed:
  java-common libasound2 libasound2-data libx11-6 libx11-data libxcb1 libxext6 libxi6 libxrender1 libxtst6 x11-common
Suggested packages:
  default-jre libasound2-plugins alsa-utils
The following NEW packages will be installed:
  adoptopenjdk-8-hotspot java-common libasound2 libasound2-data libx11-6 libx11-data libxcb1 libxext6 libxi6
  libxrender1 libxtst6 x11-common
0 upgraded, 12 newly installed, 0 to remove and 0 not upgraded.
Need to get 103 MB/104 MB of archives.
After this operation, 210 MB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 https://adoptopenjdk.jfrog.io/adoptopenjdk/deb bionic/main amd64 adoptopenjdk-8-hotspot amd64 8u252-b09-2 [103 MB]
Get:1 https://adoptopenjdk.jfrog.io/adoptopenjdk/deb bionic/main amd64 adoptopenjdk-8-hotspot amd64 8u252-b09-2 [103 MB]
Err:1 https://adoptopenjdk.jfrog.io/adoptopenjdk/deb bionic/main amd64 adoptopenjdk-8-hotspot amd64 8u252-b09-2
  Hash Sum mismatch
  Hashes of expected file:
   - SHA256:456dc31038599386af63a978092ae4af887c6a9b7c7437ecaca612e72abdef68
   - SHA1:e326f1817353c8888d1441058961ee79c92abffa [weak]
   - Filesize:102611612 [weak]
  Hashes of received file:
   - SHA256:a3377091166ac3d7b23fabea658840d55578138e30a83cda638ce0496e1f6aac
   - SHA1:73e091979d312643800db8f79b3a64eb7d37e0a6 [weak]
   - Filesize:102611612 [weak]
  Last modification reported: Fri, 17 Apr 2020 13:25:01 +0000
Fetched 51.0 MB in 3min 16s (260 kB/s)
E: Failed to fetch https://adoptopenjdk.jfrog.io/adoptopenjdk/deb/pool/main/a/adoptopenjdk-8-hotspot/adoptopenjdk-8-hotspot_8u252-b09-2_amd64.deb  Hash Sum mismatch
   Hashes of expected file:
    - SHA256:456dc31038599386af63a978092ae4af887c6a9b7c7437ecaca612e72abdef68
    - SHA1:e326f1817353c8888d1441058961ee79c92abffa [weak]
    - Filesize:102611612 [weak]
   Hashes of received file:
    - SHA256:a3377091166ac3d7b23fabea658840d55578138e30a83cda638ce0496e1f6aac
    - SHA1:73e091979d312643800db8f79b3a64eb7d37e0a6 [weak]
    - Filesize:102611612 [weak]
   Last modification reported: Fri, 17 Apr 2020 13:25:01 +0000
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

**Comment by kosakosinski** [comment]
When I did standard install procedure on same Ubuntu on WSL, I got AdoptOpenJDK installed without any problems.

**Comment by aahlenst** [comment]
I cannot reproduce the problem. Maybe some proxy issue.

```
rm -rf /var/lib/apt/lists/*
apt-get clean
apt-get update
```

should get you going again.

**Comment by philmcm** [comment]
I have the same issue.  @aahlenst commands above did not help.   I am also using Vagrant with the hashicorp/bionic64 box.  I'm happy to open a new issue if required with all the relevant output on my side.

**Comment by aahlenst** [comment]
The update of Debian repositories is racy by design. As a result, middleboxes like proxies can cache an inconsistent state. The only option I see is to wait until it goes away, especially because we have no control of that middlebox.
