### ISSUE TITLE
JVM crash with SIGSEGV error:ObjectSynchronizer::inflate

### ISSUE THREAD

**Issue by nehamanel** [AdoptOpenJDK/openjdk-support#110]
* Platform and architecture: Linux 64

* Java version: 1.8.0_92

* **Have you tested it with other vendors' java**: No

* **Error messsage and/or description of what is not working as expected**:

![image](https://user-images.githubusercontent.com/58589054/83146500-0693f880-a114-11ea-895d-a66c0ccdc02e.png)

We have a java application running on Linux and it suddenly crashed with the following error in pid file:
 V  [libjvm.so+0xa2b484]  ObjectSynchronizer::inflate(Thread*, oopDesc*)+0x384
Has this been fixed in any later versions of AdoptOpen Jdk ?

**Comment by aahlenst** [comment]
Probably not: https://bugs.openjdk.java.net/browse/JDK-8184250?jql=text%20~%20ObjectSynchronizer%3A%3Ainflate%20ORDER%20BY%20created%20DESC.
