### ISSUE TITLE
Getting error while trying to launch using OpenWebStart

### ISSUE THREAD

**Issue by NetOps-spectrum** [AdoptOpenJDK/openjdk-support#111]
**Adopt Open JDK** : OpenJDK8U-jre_x64_windows_hotspot_8u232b09 

**OpenWebstart** : v1.1.6

![image](https://user-images.githubusercontent.com/58945429/83148538-b8ccbf80-a116-11ea-850f-65fe59995b73.png)

![image](https://user-images.githubusercontent.com/58945429/83148581-c97d3580-a116-11ea-9e91-997830db47ae.png)

**Comment by NetOps-spectrum** [comment]
Any help/clue?

**Comment by hendrikebbers** [comment]
@NetOps-spectrum the issue belongs to https://github.com/AdoptOpenJDK/IcedTea-Web/

You already created a copy (https://github.com/AdoptOpenJDK/IcedTea-Web/issues/648) so I will close this one :)

**Comment by aahlenst** [comment]
@hendrikebbers Thanks!
