### ISSUE TITLE
OpenJDK 11.0.6 upgrade/Java 8 issue

### ISSUE THREAD

**Issue by Martajsliwka** [AdoptOpenJDK/openjdk-support#113]
Hi
In my environment (win10)  we use OpenJDK 11, however there are still apps that needs Java 8 (we use Oracle Java 8.202).
After upgrading OpenJDK 11.0.6  - pushed via SCCM on PC (previous version OpenJDK11.0.3), 
AND restart PC some applications had issue as below
`
![Issue command Prompt](https://user-images.githubusercontent.com/61330256/83529630-e20c9780-a4ea-11ea-9569-da2890a710dc.JPG)

What went wrong? How to avoid this issue in the future?
I Haven't tested it with other vendors' java**:

**Comment by karianna** [comment]
@Martajsliwka please try our 11.0.7 builds

**Comment by aahlenst** [comment]
If using a newer version does not help, we need steps to reproduce: What application, launch parameters, ... Otherwise we cannot work on it.

**Comment by aahlenst** [comment]
Closing due to lack of requested feedback. We're happy to reopen the issue if feedback is provided by the OP (or anybody else) at a later date.
