### ISSUE TITLE
32 bit version is not built Large address aware

### ISSUE THREAD

**Issue by ed03875** [AdoptOpenJDK/openjdk-support#115]
* **Platform and architecture (e.g. Linux/x64**:
Windows W32
* **Java version (from "java --version") e.g. 1.8.0_181, 11.0.4+11 etc.**:
Both  jdk8u252-b09  jdk8u232-b09

* **Variant e.g. HotSpot or OpenJ9**:
OpenJ9
* **Have you tested it with other vendors' java**:
Yes IBM version is Large address aware

* **Steps to reproduce**:
dumpbin /headers java.exe |grep -i large 
or 
dumpbin /headers nlnotes.exe |grep -i large

If nothing found can't handle >2GB address
                   

* **Error messsage and/or description of what is not working as expected**:
The openJDK J9 32 bit version is not built Large address aware and therefore cannot address memory > 2 GB and so the command fails.  The headers output does not have this line in it:
Application can handle large (>2GB) addresses

dumpbin /headers nlnotes.exe |grep -i large
        or
dumpbin /headers java.exe |grep -i large

**Comment by aahlenst** [comment]
@pshipton Could somebody of OpenJ9 please look into it?

**Comment by pshipton** [comment]
Duplicated in eclipse/openj9#9774 for investigation.

**Comment by pshipton** [comment]
The fix is merged, and will be included in the next nightly build here at AdoptOpenJDK.net
https://github.com/ibmruntimes/openj9-openjdk-jdk8/pull/416
