### ISSUE TITLE
Misssing c:\Program Files\AdoptOpenJDK\jdk-8.0.252.09-hotspot\bin\msvcr100.dll?

### ISSUE THREAD

**Issue by Pierre-de-la-Verre** [AdoptOpenJDK/openjdk-support#118]
- Win 10, 64 bit
- c:\Program Files\AdoptOpenJDK\jdk-8.0.252.09-hotspot
- SQL developer (from Oracle) 19.4

I just changed from Java 8.252 to AdoptOpenJDK and got a message when I started SQL Developer:
" .. Missing c:\Program Files\AdoptOpenJDK\jdk-8.0.252.09-hotspot\bin\msvcr100.dll"
I copied it from another place and now SQL developer starts.

Is this a bug (a missing file) or not?

Same problem, described by another user, including screenshots and same solution:
[https://www.java-forum.org/thema/sql-developer-installation-unable-to-launch-the-java-virtual-machine-located-at-path-msvcr100-dll.188142/](url)

And maybe the same or a similar thing at Oracle:
[How To Fix SQL Developer With JDK Included Getting Error: "program can't start because MSVCR100.dll is missing" ? (Doc ID 2031937.1)](https://support.oracle.com/knowledge/Middleware/2031937_1.html)

**Comment by aahlenst** [comment]
We build with Visual Studio 2013 or even 2017. msvcr100.dll is therefore missing as it is a part of Visual Studio 2010. The recommended resolution is to install http://www.microsoft.com/de-de/download/details.aspx?id=8328 (32 bit) or http://www.microsoft.com/en-us/download/details.aspx?id=13523 (64 bit).
