### ISSUE TITLE
Table Headers appear black (11.0.7)

### ISSUE THREAD

**Issue by taylorsmock** [AdoptOpenJDK/openjdk-support#120]
* **Platform and architecture (e.g. Linux/x64**: Mac OS X 10.15.5, x64

* **Java version (from "java --version") e.g. 1.8.0_181, 11.0.4+11 etc.**:
openjdk version "11.0.7" 2020-04-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.7+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.7+10, mixed mode)

* **Variant e.g. HotSpot or OpenJ9**: Should be hotspot. Installed via homebrew. It is also reproducible with OpenWebStart.

* **Have you tested it with other vendors' java**: Yes. Does not reproduce on AdoptOpenJDK 11.0.6, Azul 11, AdoptOpenJDK 10, AdoptOpenJDK 12.

* **Steps to reproduce**:
Download a `josm` jar file from `https://josm.openstreetmap.de`
`java -jar ${PATH_TO_JOSM_JAR}`
Click on `Imagery` (top toolbar) -> `Imagery preferences`.

* **Error messsage and/or description of what is not working as expected**:
Non-black table headers
![black-table-headers](https://user-images.githubusercontent.com/45215054/83766911-33776c80-a63a-11ea-9c21-fb1d2fb7ef69.png)

External bug: https://josm.openstreetmap.de/ticket/19309

**Comment by taylorsmock** [comment]
Yes, I do use dark mode.

**Comment by aahlenst** [comment]
This is not specific to AdoptOpenJDK. Happens with BellSoft Liberica, too. Big difference is the toolchain version. Zulu is still on 10.13.

It does not happen with AdoptOpenJDK 14 and Oracle's build. But both refuse to adapt to Dark Mode, anyway.

**Comment by aahlenst** [comment]
I tested on a nightly build of 11.0.8 and there the problem is fixed. As with 14.0.1, Swing does not try to adapt to Dark Mode. Instead, everything stays in light mode:

<img width="519" alt="Bildschirmfoto 2020-06-06 um 13 40 38" src="https://user-images.githubusercontent.com/198908/83943315-59983a80-a7fb-11ea-94dc-86da6636833b.png">

For reference, how to reproduce (**enable Dark Mode**):

```
$  wget https://docs.oracle.com/javase/tutorial/uiswing/examples/components/SimpleTableDemoProject/src/components/SimpleTableDemo.java
$ javac -d . SimpleTableDemo.java
$ java components.SimpleTableDemo
```
