### ISSUE TITLE
Not able to find the javafx api support with either AdoptopenJdk 8 or 11

### ISSUE THREAD

**Issue by jitendrakm41** [AdoptOpenJDK/openjdk-support#130]
* **Platform and architecture (e.g. Linux/x64**: MAC OS 64

* **Java version (from "java --version") e.g. 1.8.0_181, 11.0.4+11 etc.**: adoptopenjdk-11, adoptopenjdk-8

* **Variant e.g. HotSpot or OpenJ9**:

* **Have you tested it with other vendors' java**: With Oracle java version 8, it was available.

* **Steps to reproduce**: Download either adoptopenjdk-11 or adoptopenjdk-8

* **Error messsage and/or description of what is not working as expected**: Not able to compile the code only.

**Comment by jitendrakm41** [comment]
Please suggest me how to solve this.

**Comment by aahlenst** [comment]
https://adoptopenjdk.net/faq.html#openjfxfaq explains the general situation. With AdoptOpenJDK 8, you're out of luck. With 11, you should be able to use OpenJFX 14. See https://openjfx.io/openjfx-docs/#install-java for how to get going.
