### ISSUE TITLE
OpenJDK 11: ELF file OS ABI invalid on SLES 11

### ISSUE THREAD

**Issue by DJViking** [AdoptOpenJDK/openjdk-support#133]
OpenJDK 11 LTS 11.0.4+11
SUSE Linux Enterprise Server 11

Running `java -version`
```
Error: dl failure on line 597
Error: failed /usr/java/jdk-11.0.4+11/lib/server/libjvm.so, because /usr/java/jdk-11.0.4+11/lib/server/libjvm.so: ELF file OS ABI invalid
```

It works fine on SUSE Linux Enterprise Server 11.3

Have tried the BellSoft OpenJDK 11.0.4 and that works fine on both SLES 11.0 and SLES 11.3

**Comment by aahlenst** [comment]
https://adoptopenjdk.net/supported_platforms.html lists our supported platforms. SLES 11 is not on it, although that list is very conservative. Only SLES 12 is.

**Comment by karianna** [comment]
Ah yeah, we'll have to close this I'm afraid.
