### ISSUE TITLE
How to install JDK instead of JRE ?

### ISSUE THREAD

**Issue by hmoreira2** [AdoptOpenJDK/openjdk-support#136]
I installed adoptopenjdk-8-hotspot on CentOS using RPM install instructions. It worked, but JRE was installed. I need JDK. How to  install JDK instead of JRE ?

**Comment by aahlenst** [comment]
Maybe you accidentally typed `adoptopenjdk-8-hotspot-jre`? `yum install adoptopenjdk-8-hotspot` should give you the JDK.

**Comment by hmoreira2** [comment]
No, karianna .... I typed adoptopenjdk-8-hotspot. Where JDK files are placed in CentOS ?

**Comment by hmoreira2** [comment]
Sorry, guys, my mistake !!!! I found it. Do you believe I was searching the files in the wrong server? Probably it´s another C-19 effect !!!
Thank for your time !!!!
