### ISSUE TITLE
AoptOpenJDk build jdk8u252-b09 does not decode jpeg image files

### ISSUE THREAD

**Issue by gavlow** [AdoptOpenJDK/openjdk-support#141]
* **Platform and architecture windows 10 **:

* **Java version  1.8.0_252,:

* **Variant HotSpot **:

* **Have you tested it with other vendors' java**:

* **Steps to reproduce**:

* **Error messsage and/or description of what is not working as expected**:

C:\Java\jdk8u252-b09\src.zip;java/awt/image/renderable/ParameterBlock.java

Line 298-300
   public Vector<Object> getParameters() {
        return parameters;
    }

![image](https://user-images.githubusercontent.com/67985198/86856986-db33fe80-c100-11ea-976b-4b2edc8a76ae.png)

For these calls

               RenderedImage ri = JAI.create("fileload", imageFileName);
                PlanarImage image = new RenderedImageAdapter(ri);

if imageFilename = ".\ASHES_AIRPHOTO_tiny.jpg"

then 
 PlanarImage image = new RenderedImageAdapter(ri);

throws the exception and "image" is not created

...

if imageFilename  = ".\ASHES_HIGHWALL40_3D_Image.tif"

then
   PlanarImage image = new RenderedImageAdapter(ri);

creates image with all the correct parameters
![image](https://user-images.githubusercontent.com/67985198/86859132-4e3f7400-c105-11ea-9d44-e80b01ae7bbb.png)

**Comment by aahlenst** [comment]
Thanks for getting in touch, but as it stands, you do not provide enough information to diagnose the problem. Please share a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example). This should include a copy of the image you're having trouble with.

**Comment by karianna** [comment]
@gavlow Are you also able to try the adoptopenjdk.net/upstream.html build

**Comment by gavlow** [comment]
I checked the available builds for AdoptOpenJDK 8 from the upstream site and only x64 is available. Unfortunately I am using a 32 bit/x86 application and hence need a 32 bit (x86) build

**Comment by gavlow** [comment]
Found a workaround for this issue in Java 8 using this example:

https://docs.oracle.com/javase/tutorial/2d/images/examples/LoadImageApp.java


Basically this involved replacing this code

                RenderedImage ri = JAI.create("fileload", imageFileName);
                PlanarImage image = new RenderedImageAdapter(ri);
                this.orgImage = image.getAsBufferedImage();


with:

                    this.orgImage = ImageIO.read(new File(imageFileName));


Thanks everyone for their feedback
