### ISSUE TITLE
macOS tar.gz

### ISSUE THREAD

**Issue by brunoborges** [AdoptOpenJDK/openjdk-support#144]
In what situation would users actually make good use of the tar.gz package for macOS?

**Comment by aahlenst** [comment]
@gdams Can you help?

**Comment by karianna** [comment]
It's for when they want to bundle that in another package.  See https://github.com/AdoptOpenJDK/openjdk-support/issues/97

**Comment by aahlenst** [comment]
I use it for testing because I do not have to install it. As long as I download it with curl/wget or remove the quarantine attribute, it does its job.

@brunoborges Why do you ask?

**Comment by brunoborges** [comment]
Can't one extract the contents from a PKG file as well?

**Comment by aahlenst** [comment]
Yes, but complicated: https://stackoverflow.com/a/11299907. Again, why do you ask?

**Comment by gdams** [comment]
there are several reasons that users may wish to use the tarball:

1. To work around notarization/codesign issues on a local mac
1. To bundle the JDK/JRE into an application
1. To create a custom bundle with extra CACERTS etc

**Comment by karianna** [comment]
Closing as I think we have the complete answer.
