### ISSUE TITLE
OpenJ9 reproducibility

### ISSUE THREAD

**Issue by Hello71** [AdoptOpenJDK/openjdk-support#148]
openjdk-build seems overly complicated, but it looks like openj9 builds from a branch, not a tag. for example, https://github.com/ibmruntimes/openj9-openjdk-jdk14/commits/openj9-0.21.0 has had several updates since initial branch. how can users determine which version of openj9-openjdk-jdk14 is used? furthermore, the openj9 and omr hashes are not locked, so do they just float with whenever the build happens to be triggered?

**Comment by aahlenst** [comment]
@pshipton Could you please answer?

**Comment by pshipton** [comment]
@Hello71 see https://github.com/eclipse/openj9/releases/tag/openj9-0.21.0
OpenJ9 and OMR are built from tags, in this case openj9-0.21.0

OpenJDK is built from the branch https://github.com/ibmruntimes/openj9-openjdk-jdk14/tree/openj9-0.21.0, but the contents won't change. If you think it's necessary, we can ask the maintainers to create a tag to correspond to the release.

**Comment by pshipton** [comment]
This is where the tags for OpenJ9/OMR are set. https://github.com/ibmruntimes/openj9-openjdk-jdk14/blob/openj9-0.21.0/closed/get_j9_source.sh#L60

**Comment by Hello71** [comment]
Thanks, I saw that already. I was concerned because 14.0.2 was released on July 8, but there were commits at https://github.com/ibmruntimes/openj9-openjdk-jdk14/commits/openj9-0.21.0 until July 15. Checking closer though, https://github.com/AdoptOpenJDK/openjdk14-binaries/releases/tag/jdk-14.0.2%2B12_openj9-0.21.0 wasn't built until July 16, so I now see that there is no problem there.

For Linux distro integration, we strongly prefer tags, as git branches connote potential change, even if they are technically identical. Even if there is a statement that branches are considered fixed, it is not always clear from outside when exactly that is the case. For example, https://github.com/ibmruntimes/openj9-openjdk-jdk14/commits/openj9-0.21.0 had commits between July 8 (?) and July 15. I guess it was discussed internally and "released" on July 16, but as far as I (and other developers) can see, there doesn't seem to be any clear external indicator of when that is the case. I am currently working on Arch and Gentoo, but these points are common across all Linux distros. https://github.com/eclipse/openj9 and https://github.com/eclipse/openj9-omr are fine here, because they have both branches (vx.y.z-release) and tags (openj9-x.y.z).

We would also slightly prefer a single source tarball as opposed to downloading separate files. Most Linux distros do not permit network access during builds for security, reproducibility, and upstream load reasons. From what I can see now, that would need to include openj9-openjdk-jdk14, openj9, openj9-omr, and freemarker. I haven't finished testing that though, because  It is of course possible to download multiple files, but it would be more convenient for both us and any other users building their own JDK if for example https://github.com/ibmruntimes/openj9-openjdk-jdk14/releases had unified tarballs so you can just download, extract, ./configure; make; run. In general, bundled libraries are frowned upon on Linux, but it seems to me that the JVM is currently closely tied to the JDK, so that it is not possible to use a single system OpenJ9 with multiple JDKs linked to it.

I think it would also be nice if AdoptOpenJDK was more clear about which sources it's building from. For example, on https://adoptopenjdk.net/releases.html it could say something like "Built from https://hg.openjdk.java.net/jdk-updates/jdk14u/rev/jdk-14.0.2-ga using https://github.com/AdoptOpenJDK/openjdk-build/commit/2259450b995e6ca0ea46d442db2064d5d0392c30" or something like that. For OpenJ9, it would need to be a little bit longer, but hopefully you get the idea.

This is getting a bit long for a bug report though, and we can move it to the mailing lists if you'd prefer.

**Comment by aahlenst** [comment]
AdoptOpenJDK does not build from Mercurial forests but from our mirrored Git repositories, e.g. https://github.com/AdoptOpenJDK/openjdk-jdk14. You can find metadata next to the binaries on GitHub, for example https://github.com/AdoptOpenJDK/openjdk14-binaries/releases/tag/jdk-14.0.2%2B12. Look for the JSON files. If you want more metadata, please open an issue on https://github.com/AdoptOpenJDK/openjdk-build/issues.

**Comment by pshipton** [comment]
OpenJDK didn't release the final code to open source until July 14, even if it was finalized internally by July 8, which accounts for most of the changes to the openj9-0.21.0 branch. The release process started asap after that, with mirroring, merging, build, test, assessment of the test results, creation of the release tags taking the time before the July 16 release. The branch was initially created in June, and used to produce some milestone builds, with additional fixes added prior to the release. There was a last minute fix added (https://github.com/ibmruntimes/openj9-openjdk-jdk14/pull/67), which we knew was coming but couldn't make until we had the final OpenJDK code. The other change sets the default OpenJ9/OMR release tags to build from.

> JVM is currently closely tied to the JDK, so that it is not possible to use a single system OpenJ9 with multiple JDKs linked to it.

Correct. Although the same OpenJ9/OMR source supports Java 8, 11, 14, etc., after compilation some of the shared libraries are specific to the Java version, and the others are closely tied to those versions. In the future there will be fewer OpenJ9 related shared libraries.

@andrew-m-leonard please see this request for tagging the release commits https://github.com/AdoptOpenJDK/openjdk-support/issues/148#issuecomment-663687754. Also the request for creation of a single tarball containing all the sources.

**Comment by aahlenst** [comment]
It looks like all questions have been answered. If you think otherwise, please reopen.
