### ISSUE TITLE
OutOfMemoryError: Java heap space in Libreoffice with AdoptOpenjdk 13.0.1-hotspot

### ISSUE THREAD

**Issue by HelmutL** [AdoptOpenJDK/openjdk-support#15]
Windows10 64-bit

LibreOffice 6.3, LanguageTool 4.7

Every time a tect document is opened, an OutOfMemoryError: Java heap space is thrown.
This problem is present with AdopOpenJDK 13.0.1 with HotSpot JVM.
It does not occur with Oracle Java (from 8 to 13,0,1), openjdk 13.0.1, or AdoptOpenJDK  13.0.1 with OpenJ9 JVM
![JavaHeap](https://user-images.githubusercontent.com/17042607/69345534-8f1b7300-0c71-11ea-83c2-6166893f43fd.jpg)

**Comment by aahlenst** [comment]
@HelmutL Delete the folder `bin/client` in the JDK directory and test again. I suspect the client VM is requested which by default uses a significantly smaller heap. We‘re one of very few providers that still ships a client VM.

**Comment by HelmutL** [comment]
It seems this is the trick. After deleting the client directory it seems to run ok (tested with jdk-14.0.1+7 with hotspot). When the directory is present, the error occurs.

**Comment by aahlenst** [comment]
Great to hear. Please report to LibreOffice that they should stop requesting the client VM (most vendors do not ship it anyway and the server VM is the default on 64 bit Windows) or configure an appropriately large heap with `-Xmx`. The default maximum is 256 Mb as specified by Oracle.
