### ISSUE TITLE
java.security.KeyStore should support PKCS#12 files with AES

### ISSUE THREAD

**Issue by AbirDas** [AdoptOpenJDK/openjdk-support#151]
Windows server 2019

When using PKCS12 certificate with Java 11.0.3, getting error -
java.io.IOException: keystore password was incorrect
        at java.base/sun.security.pkcs12.PKCS12KeyStore.engineLoad(PKCS12KeyStore.java:2108)
        at java.base/sun.security.util.KeyStoreDelegator.engineLoad(KeyStoreDelegator.java:222)
        at java.base/java.security.KeyStore.load(KeyStore.java:1479)
        at Main.main(Main.java:16)
Caused by: java.security.UnrecoverableKeyException: failed to decrypt safe contents entry: javax.crypto.BadPaddingException: Given final block not properly padded. Such issues can arise if a bad key is used during decryption.
        ... 4 more

But not getting any issue with JKS certificates. 

The following code demonstrates the problem:
import java.io.File;
import java.io.FileInputStream;
import java.security.KeyStore;
import java.util.Enumeration;
import java.util.Objects;

public class Main {
	public static void main(String[] args) throws Exception {
		KeyStore keystore;

		File certFile   = new File("AES256.pfx");
		String password = new String("Password");

		try {
			keystore = KeyStore.getInstance("pkcs12");
			keystore.load(new FileInputStream(certFile),
				password.toCharArray());
		} catch (Exception e) {
			e.printStackTrace();
		}
	}
}

**Comment by karianna** [comment]
Can you try with 11.0.8 please and also are you sure the password stored in AES256.pfx is "password"?  Lastly, I'd use the Files API to ensure that file truly exists before trying to access it

**Comment by AbirDas** [comment]
i have tried on 11.0.8+10 still same issue, Actually in code we are using default password:- changeit
through keyStore Explorer am able to open and access it.

**Comment by aahlenst** [comment]
The information you provided is insufficient to reproduce the problem and therefore to help you. What is AES256.pfx exactly? How was it created? What else did you try? Did you have a look at similar problems on StackOverflow, for example https://stackoverflow.com/questions/10338543/what-causes-keytool-error-failed-to-decrypt-safe-contents-entry?

**Comment by AbirDas** [comment]
Reproducing step:-
1>create pkcs12 certificate
keytool.exe -genkey -keyalg RSA -dname "CN=AB, OU=AB, O=ABC, ST=Pennsylvania, C=US, DC=ABC, DC=com" -keystore .\AES256..pfx -storepass changeit -alias AB -validity 36500 -keysize 2048 -storetype pkcs12
2> try to load with below code AdoptOpenJDK11:-
KeyStore keystore;

	File certFile   = new File("AES256.pfx");
	String password = new String("changeit");

	try {
		keystore = KeyStore.getInstance("pkcs12");
		keystore.load(new FileInputStream(certFile),
			password.toCharArray());
	} catch (Exception e) {
		e.printStackTrace();
	}

**Comment by AbirDas** [comment]
Yes i have tried some ScackOverflow suggestion but didn't help in my case. as i want to use keystore certificate format to be PKCS12 as it is stander. and not JKS which is JAVA specific.

I have found few similar issue but no solution:-https://community.oracle.com/thread/4272238

Found similar in Oracle and story of addressing it:-
https://bugs.java.com/bugdatabase/view_bug.do?bug_id=8220734
https://bugs.java.com/bugdatabase/view_bug.do?bug_id=8214513

**Comment by karianna** [comment]
Can you also try with the adoptopenjdk.net/upstream.html build?  That way we know if it's an adopt issue or not.

**Comment by aahlenst** [comment]
I cannot reproduce it, neither on macOS nor on Windows:

```
> keytool.exe -genkey -keyalg RSA -dname "CN=AB, OU=AB, O=ABC, ST=Pennsylvania, C=US, DC=ABC, DC=com" -keystore AES256.pfx -storepass changeit -alias AB -validity 36500 -keysize 2048 -storetype pkcs12
> keytool -list -keystore AES256.pfx
Keystore-Kennwort eingeben:
Keystore-Typ: PKCS12
Keystore-Provider: SUN

Keystore enthält 1 Eintrag

ab, 02.08.2020, PrivateKeyEntry,
Zertifikat-Fingerprint (SHA-256): 94:51:4C:77:6B:47:22:52:36:EA:3A:DC:B8:08:5D:CF:2D:DB:57:D5:89:FE:A2:9C:F6:0D:09:95:0E:FC:48:9A
> javac LoadKeystore.java
> java LoadKeystore
1
> java -version
openjdk version "11.0.8" 2020-07-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.8+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.8+10, mixed mode)
```

The source code of LoadKeystore.java:

```java
import java.io.File;
import java.io.FileInputStream;
import java.security.KeyStore;

public class LoadKeystore {
    public static void main(String[] args) throws Exception {
        KeyStore keystore = KeyStore.getInstance("pkcs12");
        keystore.load(new FileInputStream(new File("AES256.pfx")), "changeit".toCharArray());
        System.out.println(keystore.size());
    }
}
```

**Comment by AbirDas** [comment]
Yea this is strange, even am not able to reproduce in developer machine. Issue only arise when run in windows 2019 server deployed in tomcat9.0, Sorry for the initial problem statement. even am trying to investigate root cause of issue, it just work with JKS and not PKCS12.
Will update my finding.

**Comment by aahlenst** [comment]
Closing due to lack of requested feedback. We're happy to reopen the issue if feedback is provided by the OP (or anybody else) at a later date.
