### ISSUE TITLE
Can one determine whether heap is normal or large somehow from installed release [Windows]

### ISSUE THREAD

**Issue by tushev** [AdoptOpenJDK/openjdk-support#153]
I need to determine whether installed release is of normal- or large-heap type.

Is it possible somehow, for instance, from a `release` file?

**Comment by aahlenst** [comment]
@pshipton Do you know of any option? If not, would probably a good idea to the version output.

**Comment by pshipton** [comment]
You can't tell from the release file output. The -version out does indicate "Compressed References" or not. The difference in the build is the directory structure contains either a `compressedrefs` directory or a `default` directory (`default` for 32-bit). Where exactly that is in the structure depends on whether it's Java 8 or Java 11+, and whether it's Windows or some other platform. On Windows the directory is in the jre/bin directory, or in bin if there is no jre directory.

You could open an issue at https://github.com/eclipse/openj9/issues to see about adding something to the release file, but note the OpenJ9 project is actively working on not having a separate large heap build. It's functional but not yet performant.

**Comment by tushev** [comment]
Thank you very much! This is enough for my task.

**Comment by tushev** [comment]
@pshipton  Still need one more clarification - does `default` for 32-bit tells that it's normal heap?

i.e., the algorithm looks like:
if x64 => presence of  `compressedrefs` = normal heap; `default` = large heap
if x32 => presence of  `default` = normal heap

**Comment by pshipton** [comment]
Correct, there is only one type for 32-bit.

**Comment by tushev** [comment]
@pshipton Thank you!
