### ISSUE TITLE
Java process hang after sending signal for graceful shutdown

### ISSUE THREAD

**Issue by yaakov-berkovitch** [AdoptOpenJDK/openjdk-support#154]
## Summary

Send a SIG-TERM to gracefully shutdown the Java application, and the process stuck in shutdown and never terminates.
This issue causes some degradation in our application. A simple application was built to reproduce the issue and can be send if needed.

## Steps to reproduce
Very simple spring boot application, that has 2 classes: 

1. main class:
```
@SpringBootApplication
public class Application {
    public static void main(String args[]) {
        SpringApplication.run(Application.class, args);
    }
}

```
2. configuration class to handle the shutdown
```
@Configuration
public class AppConfiguration {
    private static final Logger log = LoggerFactory.getLogger(AppConfiguration.class);

    @PreDestroy
    public void destroy() {
        log.info("Shutdown initiated");
    }
}

```
I also wrote a script that run the application and then send the sig-term signal in a loop until the problem is reproduced. It occurs after the first try and sometimes only after 2-3 runs. The script stops when it failed to terminate the current java process running.
The script looks as follows:
```
# export JAVA_HOME=/usr/lib/jvm/jdk-11.0.8+10/
export JAVA_HOME=/usr/lib/jvm/jdk-11.0.7+10/
export PATH=${JAVA_HOME}/bin:${PATH}

i=0
while [ true ]; do
	echo "Test #${i} at `date`"
	java -jar build/libs/gracefulshutdown-0.0.1-SNAPSHOT.jar &
	sleep 12
	# Get the pid
	pid=`ps -ef | grep graceful | grep -v grep | awk '{print \$2}'`
	# Kill the process
	kill $pid
	# Wait a while
	sleep 5
	# check process terminated
	ps -ef | grep $pid | grep -v grep 2> /dev/null
	if (( $? != 0 )); then
		echo "Process ID $pid terminated successfully"
	else
		echo "Process ID $pid didn't terminate"
		echo "Stop the test"
		exit 1
	fi
	((i+=1))
	sleep 5
done

```

## Expected results
Process to stop running.

## Actual results
Process is stuck in shutdown, and here is the thread stack:
```
Java callstack:
 at java/lang/Shutdown.halt0(Native Method)
 at java/lang/Shutdown.halt(Shutdown.java:152)
 (entered lock: java/lang/Shutdown$Lock@0x00000000C4D041C8, entry count: 1)
 at java/lang/Shutdown.exit(Shutdown.java:175)
 (entered lock: java/lang/Shutdown@0x00000000C4CD4EB8, entry count: 1)
 at java/lang/Terminator$1.handle(Terminator.java:51)
 at jdk/internal/misc/Signal$1.run(Signal.java:220)
 at java/lang/Thread.run(Thread.java:836)

```

## Triaging info

Java version:

openjdk 11.0.8 2020-07-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.8+10)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.21.0, JRE 11 Linux amd64-64-Bit Compressed References 20200715_697 (JIT enabled, AOT enabled)
OpenJ9   - 34cf4c075
OMR      - 113e54219
JCL      - 95bb504fbb based on jdk-11.0.8+10)

What is your operating system and platform?

Centos 7.7 x86

How did you install Java?

Using RPM according to this [link](https://adoptopenjdk.net/installation.html).

Did it work before?

Yes, in the previous version (jdk-11.0.7+10) it works.

Did you test with other Java versions?

Yes. It works with jdk-11.0.7+10

**Comment by aahlenst** [comment]
Sounds a lot like https://github.com/eclipse/openj9/issues/10288.

**Comment by aahlenst** [comment]
@yaakov-berkovitch Thanks a lot for filling out the complete form 😄

**Comment by aahlenst** [comment]
Fix is in. Should be visible with the next or the next but one nightly build. If the issue persists, please report back.
