### ISSUE TITLE
Is it possible to get a list of all *AdoptOpenJDK* installations on Windows?

### ISSUE THREAD

**Issue by tushev** [AdoptOpenJDK/openjdk-support#155]
I need to get a complete list of **AdoptOpenJDK** installations (I need to distinguish AdoptOpenJDK from other distributions).

So far I have found these registry keys:
![image](https://user-images.githubusercontent.com/18406797/89126851-95513700-d502-11ea-9f0d-f033b088ac3b.png)

1. Is this the correct way to enumerate all installed AdoptOpenJDK MSIs?
1a. Do other installations (like extracted from ZIP) add their keys here on first run?
2. What happens when some installation is being updated? Does its directory change? What happens with the registry keys?
3. Do these keys contain a list of only active installs, without any installations that were uninstalled beforehand (provided that they underwent normal uninstall process)?

**Comment by aahlenst** [comment]
From memory, no Windows machine nearby to test:

1. Yes, for the machine-wide installation. For per-user installations, the same structure exists in `HKCU`.
1a. The standalone binaries do not create any registry entries.
2. What exactly is your definition of update? In case of 11.0.7 to 11.0.8, the old MSI should be unistalled and the new one added. So the old registry entries disappear and new ones are added. Again, per-machine and per-user installations are treated as separate things.
3. The registry keys are removed during uninstall.

**Comment by tushev** [comment]
Thanks!
