### ISSUE TITLE
JVM returning corrupt data from jar file archive

### ISSUE THREAD

**Issue by JayJay3** [AdoptOpenJDK/openjdk-support#156]
I found that JVM returns corrupted data with following code.

It reads a data file bundled in a jar file as binary input stream. First part read is OK. But later part is corrupted. Note that if I read the file as a stand alone file, it works OK. This problem exists in jdk-14.0.2+12, jdk8u262-b10, etc. Probably all versions affected.

` 
InputStream inputstream = getClass().getResourceAsStream("resources/data.dat");

byte[] buff = new byte[1936];
for (int i=0; i < 24; i++) {
	inputstream.read(buff);
}
`

**Comment by aahlenst** [comment]
Thanks for getting in touch, but as it stands, you do not provide enough information to diagnose the problem. Please share a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example). This should include how to create `data.dat` and what "corrupted" means. Furthermore, show how you deal with the situation that the stream returns less bytes than the buffer's size because the snippet you provided does not. Quoting https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/io/InputStream.html#read(byte%5B%5D):

> The number of bytes read is, at most, equal to the length of b. Let k be the number of bytes actually read; these bytes will be stored in elements b[0] through b[k-1], leaving elements b[k] through b[b.length-1] unaffected.

**Comment by JayJay3** [comment]
Data is series of 4 byte float values. It's not an issue of length. It reads fully without errors. But values returned are "corrupted values". The file size can be multiple mega bytes. This doesn't happen when run from Eclipse SDK or read from a standalone file, which does not read from JAR file. When the binary data is bundled into a jar file and opened with from the jar file with this;

`InputStream inputstream = getClass().getResourceAsStream("resources/data.dat");`

and read(), it returns contaminated values.

It happens ONLY when read from a JAR file as InputStream!

**Comment by JayJay3** [comment]
Data  is 4 byte float values converted into 4 byte integer for speedy I/O operation.
When read, my program convert back from integer values back to float values.
After many reads, converted float values become NaN (Not a number), which means corrupted values.

**Comment by aahlenst** [comment]
Please share a sample project like https://github.com/aahlenst/datetimeformatter-parse-bug that demonstrates the problem.

**Comment by JayJay3** [comment]
I found the cause of problem!
The problem was with Windows case insensitive file naming convention. When made into Jar file, mistakes in capital letters in file names cause problems. This is what happened to my case.

Thanks for the attention and sorry for my mistake!
