### ISSUE TITLE
Profiling methods in AdoptOpenJDK 14.0.2 crashes JVM

### ISSUE THREAD

**Issue by assofohdz** [AdoptOpenJDK/openjdk-support#157]
#Summary

Profiling methods crashes the JVM

## Steps to reproduce

1. Install latest Netbeans:
Product Version: Apache NetBeans IDE 12.0
Java: 14.0.2; OpenJDK 64-Bit Server VM 14.0.2+12
Runtime: OpenJDK Runtime Environment 14.0.2+12
System: Windows 10 version 10.0 running on amd64; Cp1252; en_GB (nb)
2. Run the Netbeans template game AnagramGae
3. Through Netbeans, attach profiler and choose "Methods"

## Expected results

Profiling methods succeeding

## Actual results

This is the error given

> 
>  A fatal error has been detected by the Java Runtime Environment:
> 
>   EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ff97c33ff7b, pid=2496, tid=18520
> 
>  JRE version: OpenJDK Runtime Environment AdoptOpenJDK (14.0.2+12) (build 14.0.2+12)
>  Java VM: OpenJDK 64-Bit Server VM AdoptOpenJDK (14.0.2+12, mixed mode, sharing, tiered, compressed oops, g1 gc, windows-amd64)
>  Problematic frame:
>  V  [jvm.dll+0x5aff7b]
> 
>  No core dump will be written. Minidumps are not enabled by default on client versions of Windows
> 
>  An error report file with more information is saved as:
>  C:\Users\AFahrenholz\Documents\NetBeansProjects\AnagramGame\hs_err_pid2496.log
> 
>  If you would like to submit a bug report, please visit:
>    https://github.com/AdoptOpenJDK/openjdk-support/issues
> 

## Triaging info

Java version:

PS C:\Users\AFahrenholz> javac --version
javac 14.0.2
PS C:\Users\AFahrenholz> java --version
openjdk 14.0.2 2020-07-14
OpenJDK Runtime Environment AdoptOpenJDK (build 14.0.2+12)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 14.0.2+12, mixed mode, sharing)

What is your operating system and platform?

System: Windows 10 version 10.0 running on amd64; Cp1252; en_GB (nb)

How did you install Java?

Downloaded via https://adoptopenjdk.net/

Did it work before?

Dont know - have only tried v. 14

Did you test with other Java versions?

Not yet

Log output:
[hs_err_pid2496.log](https://github.com/AdoptOpenJDK/openjdk-support/files/5020620/hs_err_pid2496.log)

**Comment by assofohdz** [comment]
I tried googling this error/bug and couldn't come up with anything recent - some places refer to the same bug with a comment saying its not a Netbeans error but a JVM error, hence why I'm trying to report it here.

**Comment by aahlenst** [comment]
This is an issue in NetBeans' native code:

https://issues.apache.org/jira/browse/NETBEANS-1428

**Comment by assofohdz** [comment]
@aahlenst Thank you.
