### ISSUE TITLE
How to run jstatd ?

### ISSUE THREAD

**Issue by hmoreira2** [AdoptOpenJDK/openjdk-support#161]
Hi guys

I need to run jstatd in adoptopenjdk. I cannot find the executable file at "bin" folder.

Java Version:
openjdk version "1.8.0_252"
OpenJDK Runtime Environment (build 1.8.0_252-b09)
Eclipse OpenJ9 VM (build openj9-0.20.0, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20200416_608 (JIT enabled, AOT enabled)
OpenJ9   - 05fa2d361
OMR      - d4365f371
JCL      - cfa47e66cd5 based on jdk8u252-b09)

OS : CentOS Linux release 7.7.1908 (Core)

Thanks

**Comment by tmancill** [comment]
Hi @hmoreira2 .  From that version string, you are installing the OpenJ9 JRE, and `jhat`, `jinfo`, and `jstatd` are not part of openjdk-openj9 in JDK 8.  See this reference:  https://github.com/eclipse/openj9/issues/8732#issuecomment-594648635

`jstatd` is included in AdoptOpenJDK hotspot builds of of JDK8, which you can download from [this page](https://adoptopenjdk.net/releases.html?variant=openjdk8&jvmVariant=hotspot), for example:  [OpenJDK8U-jdk_x64_linux_hotspot_8u265b01.tar.gz](https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u265-b01/OpenJDK8U-jdk_x64_linux_hotspot_8u265b01.tar.gz).
