### ISSUE TITLE
What exactly is a build number?

### ISSUE THREAD

**Issue by tushev** [AdoptOpenJDK/openjdk-support#163]
I have questions about build number - 11.0.8 **+10** :

1. What exactly is a build number? What changes in between builds?

2. As far as I understand, if something significant changes, then minor or security version is being changed. So I suppose that the build number is safe to ignore - is this correct?

**Comment by aahlenst** [comment]
Commits are being added by OpenJDK between build numbers. But once released (`ga` tag), it is unusual for this number to be increased. Normally, the patch segment (8 in the sample you provided) is increased. Therefore, it seems a bit dangerous to ignore the build number.

**Comment by tushev** [comment]
Thanks! I mean, is it safe for an end-user to update only when some greater number (i.e. security) changes? So it is not necessary to update, say from 11.0.8+10 to 11.0.8+11 if this happens for some reason?

**Comment by aahlenst** [comment]
If this happens and reaches the end user, then they should update. It isn't cosmetic stuff that would be changed at that stage.

**Comment by tushev** [comment]
OK.

Is there a way to get build from, say, `release` file or you have to run `java -version` and parse it?

**Comment by aahlenst** [comment]
It's in the registry. See your old post: https://github.com/AdoptOpenJDK/openjdk-support/issues/155#issue-671642154. There it says 11.0.8.**10** which is 11.0.8+10.

**Comment by tushev** [comment]
Thanks! My goal is to robustly detect version not only for MSI's, but for ZIP-extracted instances as well. 

I think I will then stick to registry, and use `java -version` for installations that are absent in the registry (although executing a shell command is much slower than parsing `release` file).

**Comment by aahlenst** [comment]
It's gross to do that over and over again. As you can see in https://github.com/AdoptOpenJDK/openjdk15-binaries/releases/tag/jdk15u-2020-08-14-15-52, there are JSON files next to each package with metadata. What about opening an issue in https://github.com/AdoptOpenJDK/openjdk-build that we place more info in the tarballs themselves? Do you have a release file handy? I don't remember what's in it.

**Comment by tushev** [comment]
These files vary from version to version. In case of 11 branch, they look like:
[release.txt](https://github.com/AdoptOpenJDK/openjdk-support/files/5076951/release.txt)

I think it will be a good idea to add more info in it.

**Comment by aahlenst** [comment]
I think the question was answered.
