### ISSUE TITLE
OpenJ9 JVM terminates with Illegal instruction - AIX 7200-04-01-1939  (even java -version)

### ISSUE THREAD

**Issue by matsremman** [AdoptOpenJDK/openjdk-support#166]
## Summary
In our AIX environment the OpenJ9 JVM will (in some scenarios) refuse to run if max heap size is default, or set too high. 
This affects 11.0.6, 11.0.7 and 11.0.8 OpenJ9 JVM. 

Hotspot JVM 11.0.7 and Java 8 does not seem to exhibit this behaviour. 

## Steps to reproduce
**Here is where it gets tricky. I don't have a reproducable case for you because it seems isolated to one specific LPAR (for now).** 

I will also mention we are awaiting to get IBM Runtime for business support on this but it is a few weeks away.

We are using Progress Openedge software, and with their version 12.2 they no longer supply the jdk. Any AdoptOpenJdk version 11 is certified to work with it. We have been running this with 11.0.7 Hotspot JVM for a few months without trouble.

We have two nodes in this cluster, and it only seems to affect one of the nodes (for now) - a failover to the other node does allow the software and java to be run without apparent issues. We have other clusters running on the same IBM hardware in other LPARs running other Progress Openedge versions using Java8 (see -version below) and we have never seen a jvm crash like this. 

Trying to run java -version 

$ java/bin/java -version
openjdk version "11.0.8" 2020-07-14Unhandled exception
Type=Illegal instruction vmState=0x00000000
J9Generic_Signal_Number=00000048 Signal_Number=00000004 Error_Value=00000000 Signal_Code=0000001e
Handler1=09001000A05775D0 Handler2=09001000A04C4828
R0=00000000FFFF0C72 R1=00000100255CABF0 R2=000000000000002A R3=00000007FFF86390
R4=000000003002EE00 R5=0000000000000015 R6=0000000000000015 R7=0000000000000000
R8=00000007FFF86390 R9=00000000FFF86380 R10=0000000000000000 R11=0000000000000038
R12=0000000022000222 R13=00000100255D5800 R14=000000003016CA80 R15=000000003016CE00
R16=00000100246E4578 R17=FFFFFFFFFFFFFFFF R18=00000100255CAE40 R19=0000000080000007
R20=0900000001223E2C R21=09001000A04CF4D8 R22=00000100255CAED0 R23=09001000A04C5308
R24=0900000001172312 R25=0000000000000003 R26=0000000000000000 R27=0000000000000001
R28=0000000000000015 R29=00000007FFF86308 R30=00000007FFF86380 R31=0000000000000015
IAR=0000010013ACC9B4 LR=0900000001451EEC MSR=A00000000200D032 CTR=0000010013ACC854
CR=840002220000000C FPSCR=8202000000000000 XER=0000000C82020000
FPR0 0000000000000055 (f: 85,000000, d: 4,199558e-322)
FPR1 c3e0000000000000 (f: 0,000000, d: -9,223372e+18)
FPR2 3fc734b81082677c (f: 276981632,000000, d: 1,812964e-01)
FPR3 3f50546e40000000 (f: 1073741824,000000, d: 9,966923e-04)
FPR4 bf90ecf58ddc7f4a (f: 2380037888,000000, d: -1,652893e-02)
FPR5 40a6b00000000000 (f: 0,000000, d: 2,904000e+03)
FPR6 4070b2e1c3abb439 (f: 3282809856,000000, d: 2,671801e+02)
FPR7 bfb62e42fefa4000 (f: 4277813248,000000, d: -8,664340e-02)
FPR8 3f6069c0ff9e20ca (f: 4288553216,000000, d: 2,003552e-03)
FPR9 402f22a87ca8fb20 (f: 2091449088,000000, d: 1,556769e+01)
FPR10 412e848000000000 (f: 0,000000, d: 1,000000e+06)
FPR11 43300000000f4240 (f: 1000000,000000, d: 4,503600e+15)
FPR12 4530000000000000 (f: 0,000000, d: 1,934281e+25)
FPR13 0000000000000000 (f: 0,000000, d: 0,000000e+00)
FPR14 0000000000000000 (f: 0,000000, d: 0,000000e+00)
FPR15 0000000000000000 (f: 0,000000, d: 0,000000e+00)
FPR16 0000000000000000 (f: 0,000000, d: 0,000000e+00)
FPR17 0000000000000000 (f: 0,000000, d: 0,000000e+00)
FPR18 0000000000000000 (f: 0,000000, d: 0,000000e+00)
FPR19 0000000000000000 (f: 0,000000, d: 0,000000e+00)
FPR20 0000000000000000 (f: 0,000000, d: 0,000000e+00)
FPR21 0000000000000000 (f: 0,000000, d: 0,000000e+00)
FPR22 0000000000000000 (f: 0,000000, d: 0,000000e+00)
FPR23 0000000000000000 (f: 0,000000, d: 0,000000e+00)
FPR24 0000000000000000 (f: 0,000000, d: 0,000000e+00)
FPR25 0000000000000000 (f: 0,000000, d: 0,000000e+00)
FPR26 0000000000000000 (f: 0,000000, d: 0,000000e+00)
FPR27 0000000000000000 (f: 0,000000, d: 0,000000e+00)
FPR28 0000000000000000 (f: 0,000000, d: 0,000000e+00)
FPR29 0000000000000000 (f: 0,000000, d: 0,000000e+00)
FPR30 0000000000000000 (f: 0,000000, d: 0,000000e+00)
FPR31 0000000000000000 (f: 0,000000, d: 0,000000e+00)

Compiled_method=java/lang/String.<init>([BIIZZ)V]
Target=2_90_20200715_695 (AIX 7.2)
CPU=ppc64 (16 logical CPUs) (0x1e00000000 RAM)
----------- Stack Backtrace -----------
runJavaThread+0x1d4 (0x0900000000FF2338 [libj9vm29.so+0x6c338])
javaProtectedThreadProc+0x11c (0x0900000000F88AA0 [libj9vm29.so+0x2aa0])
omrsig_protect+0x488 (0x090000000125544C [libj9prt29.so+0x5744c])
javaThreadProc+0x68 (0x0900000000F8888C [libj9vm29.so+0x288c])
thread_wrapper+0x33c (0x0900000000C1B700 [libj9thr29.so+0x4700])
_pthread_body+0xe8 (0x09000000005AEFEC [libpthreads.a+0x3fec])
---------------------------------------

JVMDUMP039I Processing dump event "gpf", detail "" at 2020/08/19 22:57:49 - please wait.

However if i run it with a smaller max heap size - it works fine:
$ java -Xmx1g -version
openjdk version "11.0.8" 2020-07-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.8+10)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.21.0, JRE 11 AIX ppc64-64-Bit Compressed References 20200715_695 (JIT enabled, AOT enabled)
OpenJ9   - 34cf4c075
OMR      - 113e54219
JCL      - 95bb504fbb based on jdk-11.0.8+10)
`
Now - it needs more details.. the cluster has nothing running on it after a failover to the other cluster node. The node has 120GB ram on it and ~66GB is reported by nmon in use - there was a lot of left over semaphores on the system.

We started up our software using the hotspot jvm (11.0.7) and ram usage up to ~95% - leaving about 5GB free.
We checked some semaphores that earlier was unmatched and they now have a PID attached, so reuse? We did not clear any semaphores before starting up the software using the Hotspot JVM

It has internally been suggested that the JVM crashing could be related to the continuity of available RAM segments.

Now, after all this - we tried the OpenJ9 JVM (both 11.0.7 and 11.0.8) - this is after 160-170 processes of the software has been started and the avaiable ram on the LPAR is < 10 GB.

$ jdk-11.0.7+10/bin/java -version
openjdk version "11.0.7" 2020-04-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.7+10)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.20.0, JRE 11 AIX ppc64-64-Bit Compressed References 20200428_580 (JIT enabled, AOT enabled)
OpenJ9   - 05fa2d3
OMR      - d4365f3
JCL      - 838028f based on jdk-11.0.7+10)

$ jdk-11.0.8+10/bin/java -version
openjdk version "11.0.8" 2020-07-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.8+10)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.21.0, JRE 11 AIX ppc64-64-Bit Compressed References 20200715_695 (JIT enabled, AOT enabled)
OpenJ9   - 34cf4c075
OMR      - 113e54219
JCL      - 95bb504fbb based on jdk-11.0.8+10)

Does any of this make any sense to anyone?

## Triaging info

Java version: OpenJ9 11.0.6, 11.0.7, 11.0.8

What is your operating system and platform? AIX 7200-04-01-1939 on Power9

How did you install Java? gunzip and tar xvf from the adoptopenjdk.net site.

Did it work before? No.

Did you test with other Java versions? Yes, see above.

**Comment by matsremman** [comment]
[javacore.20200819.225339.34144576.0003.txt](https://github.com/AdoptOpenJDK/openjdk-support/files/5105169/javacore.20200819.225339.34144576.0003.txt)
Here's a javacore file from the application trying to start (same crash as in -version)

**Comment by aahlenst** [comment]
@pshipton Can I hand this over to you? I don't have access to AIX.

**Comment by pshipton** [comment]
Created https://github.com/eclipse/openj9/issues/10448 to track the investigation at the OpenJ9 project.

**Comment by pshipton** [comment]
@aahlenst rather than ping me directly, pls request help in the OpenJ9 Slack. There are times I may not be available, such as for vacation, holidays, sick, etc.

**Comment by matsremman** [comment]
This issue has been handled in the OpenJ9 project.
