### ISSUE TITLE
Does Fedora repo have jpackage?

### ISSUE THREAD

**Issue by sblantipodi** [AdoptOpenJDK/openjdk-support#169]
Thanks for the great work here.

Just installed adoptopenjdk-14-hotspot from the fedora repo 
but it says that there is no jpackage command.

How can I install jpackage from the fedora repo? What package I need?

Thanks!

**Comment by aahlenst** [comment]
Fix is in an packages for 14 (HotSpot only at the moment) are out. Plan to update the rest in the near future.
