### ISSUE TITLE
Escape Characters showing in jshell with git bash

### ISSUE THREAD

**Issue by TrevorBrown-dev** [AdoptOpenJDK/openjdk-support#175]
Hello! I was using jshell in git bash and I noticed that escape characters seem to be printing to the terminal. I was wondering how this might be able to be fixed. 
[https://i.imgur.com/eYsLmct.png](url)

**Comment by aahlenst** [comment]
I assume only cmd/PowerShell are officially supported. What you could try is using [winpty](https://github.com/rprichard/winpty), for example `winpty jshell`. Maybe that helps.

**Comment by aahlenst** [comment]
Closing due to lack of requested feedback. We're happy to reopen the issue if feedback is provided by the OP (or anybody else) at a later date.
