### ISSUE TITLE
Windows-Client: EXCEPTION_ACCESS_VIOLATION crashes Swing-client

### ISSUE THREAD

**Issue by ThisOtterBeGood** [AdoptOpenJDK/openjdk-support#188]
## Question

Since upgrading to adoptjdk 11+ our swing client regurarily crashes with an EXCEPTION_ACCESS_VIOLATION. Can someone point me in the right direction what might be the problem, there are just so many places from our code mentioned but I cannot read when exactly the error happens. I'm willing to share any piece of code or information that might help solving or identying the problem. I was not able to create a small reproducable example of this.

[hs_err_pid21756.log](https://github.com/AdoptOpenJDK/openjdk-support/files/5299294/hs_err_pid21756.log)

Meta: I'm not sure where exactly to pose this question. It might be a bug, but since I cannot make the problem reproducable for you I went with a question.

## Context

Java version: 

JRE version: OpenJDK Runtime Environment AdoptOpenJDK (11.0.8+10) (build 11.0.8+10)
Java VM: OpenJDK 64-Bit Server VM AdoptOpenJDK (11.0.8+10, mixed mode, tiered, compressed oops, g1 gc, windows-amd64)

Your operating system and platform:

Intel(R) Core(TM) i7-2640M CPU @ 2.80GHz, 4 cores, 7G,  Windows 10 , 64 bit Build 18362 (10.0.18362.959)

**Comment by aahlenst** [comment]
This one looks odd because it crashes in native code without any references to the JVM in the stacktrace. What version of Java did you use before? What vendor? Do you have native components in your app?

`JAVA_HOME` still points to JDK 8. Might make sense to change that. Maybe something is loading things from `JAVA_HOME`.

**Comment by ThisOtterBeGood** [comment]
> This one looks odd because it crashes in native code without any references to the JVM in the stacktrace. What version of Java did you use before? What vendor? 

Wie recently switched from Oracles JDK 8 to adoptjdk 11

> Do you have native components in your app?

I've checked with my team and we don't have native code.

> `JAVA_HOME` still points to JDK 8. Might make sense to change that. Maybe something is loading things from `JAVA_HOME`.

We'll try this and see if this changes anything. Thanks in advance!

**Comment by aahlenst** [comment]
@ThisOtterBeGood While you are at it, please test with https://adoptopenjdk.net/upstream.html (11 GA).

**Comment by ThisOtterBeGood** [comment]
Changing JAVA_HOME did not work. We have some known time-window since when this happens, I'll rollback some commits and test if this resolves the problem, maybe it can be "solved" on our side.
Unfortunately we couldn't just use the upstream jdk since we use some homebrew kind of launcher who doesn't accept this. I'll look into this after I tried the commit-rollback. Again thanks for your help!

**Comment by ThisOtterBeGood** [comment]
Rolling back some code did not work either. I will try to get the upstream version working and see if that changes anything.

Would it help to provide some of the mentioned code? I can provide anything.

**Comment by aahlenst** [comment]
Narrowing the code down to a minimal reproducible example (1 Java file, a few lines of code) would help tremendously, especially if we'd need it for a bug report later on.

**Comment by ThisOtterBeGood** [comment]
Some more logs, I've collected.
[hs_err_pid1796.log](https://github.com/AdoptOpenJDK/openjdk-support/files/5316430/hs_err_pid1796.log) 11.0.7+10
[hs_err_pid3660.log](https://github.com/AdoptOpenJDK/openjdk-support/files/5316431/hs_err_pid3660.log) 11.0.5+10
[hs_err_pid17596.log](https://github.com/AdoptOpenJDK/openjdk-support/files/5316432/hs_err_pid17596.log) 11.0.5+10

**Comment by ThisOtterBeGood** [comment]
> Narrowing the code down to a minimal reproducible example (1 Java file, a few lines of code) would help tremendously, especially if we'd need it for a bug report later on.

I will see what I can do.

**Comment by aahlenst** [comment]
@ThisOtterBeGood Before you invest much time: What is `de.iwacs.sav.alien.access.SwappyRef.get()Lde/iwacs/sav/alien/Identifiable`? If possible, please show the code of `SwappyRef`.

**Comment by ThisOtterBeGood** [comment]
The javadoc describes it. `SwappyRef` uses a wrapped `WeakReference` (`LooseRef` also listed below) to access objects in memory which may be subject to garbage collection. If the `LooseRef`'s `WeakReference` has been collected by the gc, we reload its content. We work with a big data model and need to be able to let the gc collect unreferenced objects. We are currently testing the client with the JDK-8 Garbage Collector (`-XX:+UseParallelGC`) instead of G1. 

**SwappyRef.java**
```java
/**
 * <p>A {@link SwappyRef} is a reference to an {@link Identifiable}
 * which allows the JVM to swap the referenced object out of memory
 * when it is no longer referenced by hard references (just like
 * {@link WeakReference}s do). Unlike {@link WeakReference}s the
 * reference can <i>reload</i> the referenced {@link Identifiable}
 * from the underlying {@link NodeAccessor}, thus it is transparent to
 * the client whether the {@link Identifiable} has been kept in memory
 * all the time, or whether it has been swapped out and swapped in
 * again.</p>
 *
 * <p>The referenced {@link Identifiable} is identified via its
 * {@link ObjectID}. If there are multiple {@link SwappyRef}s which
 * address the same {@link Identifiable}, both instances will
 * reference the same object in memory at every point of time.</p>
 *
 * @param <T>
 *            The type of the referenced {@link Identifiable}.
 */
@ThreadSafe
@Immutable
public class SwappyRef<T extends Identifiable> implements Serializable {
    private static final long serialVersionUID = 9213529407697914308L;

    @Nullable
    private final ObjectID<T> targetID;

    /**
     * The looseRef is highly context sensitive because it references instances from the
     * current JVM but as the SwappyRef itself has to be serializable we have to declare
     * the reference here as transient.
     */
    @Nullable
    private transient LooseRef<LoadIdentifiableResult> looseRef;

    static SwappyRefContext ctx;

    /**
     * Creates a new {@link SwappyRef} which references the
     * {@link Identifiable} with the given {@link ObjectID}.
     *
     * @param targetID
     *            The {@link ObjectID} of the {@link Identifiable} to
     *            reference. May be <tt>null</tt>.
     */
    public SwappyRef(@Nullable ObjectID<T> targetID) {
        this.targetID = targetID;
    }

    /**
     * Gets the {@link ObjectID} of the referenced {@link Identifiable}.
     *
     * @return {@link ObjectID}, may be <tt>null</tt>.
     */
    @Nullable
    public ObjectID<T> getReferencedObjectID() {
        return targetID;
    }

    /**
     * Gets the referenced {@link Identifiable}.
     *
     * @return {@link Identifiable}. May be <tt>null</tt> if the
     *         underlying {@link NodeAccessor} cannot resolve the stored
     *         {@link ObjectID} or if the stored {@link ObjectID} is
     *         <tt>null</tt>.
     */
    @SuppressWarnings("unchecked")
    @Nullable
    public synchronized T get() {
        LooseRef<LoadIdentifiableResult> l = looseRef;
        if (l == null) {
            LoadIdentifiableResult container = getContext().restoreIdentifiable(targetID);
            looseRef = new LooseRef<>(container);
            return (T) container.identifiable;
        }

       LoadIdentifiableResult container = l.get();

        if (container == null) {
            container = getContext().restoreIdentifiable(targetID);
            looseRef = new LooseRef<>(container);
        } else {
            container = getContext().restoreIdentifiable(targetID, container);
            looseRef = new LooseRef<>(container);
        }

        return (T) container.identifiable;
    }

    private SwappyRefContext getContext() {
        return ctx;
    }

    @Override
    public final boolean equals(final Object other) {
    	if (this == other) {
    		return true;
    	}
    	if (!(other instanceof SwappyRef)) {
    		return false;
    	}
    	SwappyRef<?> castOther = (SwappyRef<?>) other;
    	return Objects.equals(targetID, castOther.targetID);
    }

    @Override
    public final int hashCode() {
    	return Objects.hash(targetID);
    }

    @Override
    public String toString() {
        return "SwappyRef [targetID=" + targetID + "]";
    }
}
```
LooseRef.java
```java
package de.iwacs.sav.alien.access;

import java.lang.ref.*;

import javax.annotation.*;
import javax.annotation.concurrent.*;

/**
 * A {@link LooseRef} is a reference which references another object either via
 * a {@link SoftReference} or a {@link WeakReference}.
 *
 * @author usan
 *
 * @param <T> The class of the referenced object.
 */
@ThreadSafe
public class LooseRef<T> {
    private final WeakReference<T> delegate;

    /**
     * Creates a new {@link LooseRef} which references the given object.
     *
     * @param referent
     *            The object to be referenced, may be <tt>null</tt>.
     */
    public LooseRef(@Nullable T referent) {
        this.delegate = new WeakReference<>(referent);
    }

    /**
     * Creates a new {@link LooseRef} which references the given object.
     *
     * @param referent
     *            The object to be referenced, may be <tt>null</tt>.
     * @param rq
     *            a {@link ReferenceQueue} which shall be used by the new
     *            reference.
     */
    public LooseRef(@Nullable T referent, @Nullable ReferenceQueue<T> rq) {
        this.delegate = new WeakReference<>(referent, rq);
    }

    /**
     * Gets the referenced object.
     *
     * @return <tt>null</tt> if <tt>null</tt> has been referenced or if
     *         the referenced object has already been claimed by the
     *         garbage collector.
     */
    @Nullable
    public T get() {
        return delegate.get();
    }
}
```

On a side-note: We tested our client with the JDK from ZULU JDK (I couldn't install your upstream version) and we got the same vm crash:
[hs_err_pid15872.log](https://github.com/AdoptOpenJDK/openjdk-support/files/5327002/hs_err_pid15872.log)

So this does not seem to be an "adopt-problem". Am I still in the proper channel with my crash or should I report it somewhere else?

**Comment by aahlenst** [comment]
Thanks for the code. This looks safe. However, I'm not (yet) convinced that this is a problem in the JVM. Do you use Unsafe or something similar? Look at the code paths in this method:

```
    public synchronized T get() {
        LooseRef<LoadIdentifiableResult> l = looseRef;
        if (l == null) {
            LoadIdentifiableResult container = getContext().restoreIdentifiable(targetID);
            looseRef = new LooseRef<>(container);
            return (T) container.identifiable;
        }

       LoadIdentifiableResult container = l.get();

        if (container == null) {
            container = getContext().restoreIdentifiable(targetID);
            looseRef = new LooseRef<>(container);
        } else {
            container = getContext().restoreIdentifiable(targetID, container);
            looseRef = new LooseRef<>(container);
        }

        return (T) container.identifiable;
    }
```

**Comment by ThisOtterBeGood** [comment]
I looked and we actually do use Unsafe there within the `restoreIdentifiable`-Method. I did not know about the danger of the Unsafe class (I just googled). I think it's worth a try to get rid of it.

**Comment by aahlenst** [comment]
The crash looks like an unsafe usage of Unsafe. Maybe there are updates for the libraries?

**Comment by ThisOtterBeGood** [comment]
I'm looking into the libraries, there are multiple references to `sun.misc.Unsafe` but I have to verify it is actually used in `SwappyRef.get`.
I've read about minidumps or debugging JDK with Visual Studio. Since we can reproduce it in moderate time (5-15 min. working with the client) would it help if i debug into the jdk?

**Comment by ThisOtterBeGood** [comment]
We got some more issues, that might be connected. We now experience similiar crashes on our server. The event is more deterministic since we know exactly when the crash happens. One of them even got a stack (horray?):
[java_error_SAVServer_pid10508_With_Stack.log](https://github.com/AdoptOpenJDK/openjdk-support/files/5332953/java_error_SAVServer_pid10508_With_Stack.log)

These are even more mysterious:
- [java_error_SAVServer_pid3036.log](https://github.com/AdoptOpenJDK/openjdk-support/files/5332977/java_error_SAVServer_pid3036.log)
- [java_error_SAVServer_pid7644.log](https://github.com/AdoptOpenJDK/openjdk-support/files/5332981/java_error_SAVServer_pid7644.log)
- [java_error_SAVServer_pid7724.log](https://github.com/AdoptOpenJDK/openjdk-support/files/5332982/java_error_SAVServer_pid7724.log)

This client is also something new, since it is connected to a different server:
[hs_err_pid18000.log](https://github.com/AdoptOpenJDK/openjdk-support/files/5332999/hs_err_pid18000.log)

Is there some channel where we could get paid support for this issue?

**Comment by aahlenst** [comment]
See https://adoptopenjdk.net/support.html for support options for AdoptOpenJDK. If you have the same problem with Azul Zulu or BellSoft Liberica, you can get support from them, too. 

The client errors are consistent. They all crash in the same place (10th line or so of the `hs_err_pid_*`):

```
# J 14851 c2 de.iwacs.sav.alien.access.SwappyRef.get()Lde/iwacs/sav/alien/Identifiable; (113 bytes) @ 0x000002296e519202 [0x000002296e518ee0+0x0000000000000322]
```

The server crashes are caused by code trying to execute code on memory pages that are marked as data. So the problem seems to be very similar to the client crashes.

Debugging can help, or not. Ultimately the JVM cannot do anything if something feeds it invalid memory references or frees memory without telling the JVM about it.

**Comment by ThisOtterBeGood** [comment]
We replaced one of our dependencies and since then we did not experience any vm-crashes. The library internally seemed to use {{Unsafe}} methods. Thanks for the help!

**Comment by aahlenst** [comment]
@ThisOtterBeGood Thanks for letting us know. Would you mind sharing the name of the library in case someone stumbles upon the issue in the future?

**Comment by ThisOtterBeGood** [comment]
It was https://github.com/RuedigerMoeller/fast-serialization/tree/v2.56
We had to use 2.56 since we did not upgrade to Java 14 yet.
