### ISSUE TITLE
FAQ page about getting source mentions _adopt tag suffix

### ISSUE THREAD

**Issue by prenagha** [AdoptOpenJDK/openjdk-support#190]
## Question

On the [FAQ](https://adoptopenjdk.net/faq.html) under [How do I get source code for a release](https://adoptopenjdk.net/faq.html#projects) it talks about cloning the repo, then switching into the directory, then checking out the release you want via the release name tag plus the `_adopt` suffix.

I cloned the repo for java 8 from `https://github.com/adoptopenjdk/openjdk-jdk8u`

Then switched to the cloned dir, and attempted `git checkout jdk8u265-b01_adopt`

And received git error message `error: pathspec 'jdk8u265-b01_adopt' did not match any file(s) known to git`

I went looking through the branch names and tags in that repo and don't see any that have `_adopt` suffix

## Context

Java version: 8 265 b01

```
java -version
openjdk version "1.8.0_265"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_265-b01)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.265-b01, mixed mode)
```

Your operating system and platform:

macOS Catallina 10.15.7

**Comment by gdams** [comment]
I don't think we've ever had the _adopt suffix on the jdk8 repo. It only applies to jdk9+.

I will update the documents.
