### ISSUE TITLE
adoptopenjdk11-openj9: 11.0.8,10 - JVM Shutdown Hang

### ISSUE THREAD

**Issue by agsimeonov** [AdoptOpenJDK/openjdk-support#191]
Using homebrew just updated from version:
adoptopenjdk11-openj9: 11.0.6,10

To the current version:
adoptopenjdk11-openj9: 11.0.8,10

I have done this on 2 machines so I am certain 11.0.6 does not exhibit the problem that 11.0.8 does.

Steps to replicate:
1. Create a Spring Boot App via Initializr: https://start.spring.io/
 - Maven
 - Java 11
 - **IMPORTANT**: Add dependency Spring Web
 - Spring Boot 2.3.4
 - Packaging Jar

2. Download and unzip the project
3. Run `mvn clean install`
4. Run the demo project as so `java -jar target/demo-0.0.1-SNAPSHOT.jar`
5. Now try to exit via interrupt ctrl-c or `kill -2`

On 11.0.6 the process will exit on 11.0.8 the process will go through the motions for exit but hang untill killed forcefully via `kill -9`

Systems Tested On:
macOS 10.14.6
macOS 10.15.7

**Comment by aahlenst** [comment]
Sounds a lot like https://github.com/eclipse/openj9/issues/10288. Please test with a nightly build from https://adoptopenjdk.net/nightly.html and report back.

**Comment by agsimeonov** [comment]
@aahlenst Just ran it and still encountering the issue with latest nightly:

```
openjdk version "11.0.8" 2020-07-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.8+10)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.21.0, JRE 11 Mac OS X amd64-64-Bit Compressed References 20200715_677 (JIT enabled, AOT enabled)
OpenJ9   - 34cf4c075
OMR      - 113e54219
JCL      - 95bb504fbb based on jdk-11.0.8+10
```

**Comment by aahlenst** [comment]
@agsimeonov That version information looks odd. The upcoming release it 11.0.9 and it should be OpenJ9 0.22.0. Please double check that you got a nightly build.

**Comment by agsimeonov** [comment]
@aahlenst My bad works correctly on the latest nightly:

```
openjdk version "11.0.9" 2020-10-20
OpenJDK Runtime Environment Openj9 (build 11.0.9+10-202010061645)
Eclipse OpenJ9 VM Openj9 (build master-cc06e6bc1, JRE 11 Mac OS X amd64-64-Bit Compressed References 20201006_766 (JIT enabled, AOT enabled)
OpenJ9   - cc06e6bc1
OMR      - d405b96ec
JCL      - 6eb01bf3ab based on jdk-11.0.9+10)
```

**Comment by aahlenst** [comment]
Original report: https://github.com/AdoptOpenJDK/openjdk-support/issues/154
