### ISSUE TITLE
download link for latest release binary packages

### ISSUE THREAD

**Issue by chanlists** [AdoptOpenJDK/openjdk-support#193]
Hi there,

thanks for providing this resource. Are there any permanent download links for the latest release binaries, so that I can automatically download e. g. the latest release binary of the jdk on x86 in the LTS 8 line? Thanks,

Christian

**Comment by aahlenst** [comment]
https://api.adoptopenjdk.net/swagger-ui/

https://api.adoptopenjdk.net/v3/binary/latest/8/ga/windows/x64/jdk/hotspot/normal/adoptopenjdk?project=jdk gives you the zip for Windows.
