### ISSUE TITLE
com.sun.org.apache.xerces.internal.impl does not exist

### ISSUE THREAD

**Issue by mitsuyoshik** [AdoptOpenJDK/openjdk-support#199]
## Question

I am trying to port from java 1.6.0.0.07 to java kdl-11.0.8.10-hotspot.  When I build with kdl-11.0.8.10-hotspot, I get the following error:

[Excerpted message]
import com.sun.org.apache.xerces.internal.impl.xpath.regex.ParseException;
(package com.sun.org.apache.xerces.internal.impl.xpath.regex is declared in module java.xml, which does not export it)

Error: Package com.sun.org.apache.xerces.internal.impl.xs cannot be displayed.
import com.sun.org.apache.xerces.internal.impl.xs.SubstitutionGroupHandler;
(package com.sun.org.apache.xerces.internal.impl.xs is declared in module java.xml, which does not export it)

I am assuming that these errors occur because of the lack of packages "com.sun.org.apache.xerces.internal.impl.xs" and "com.sun.org.apache.xerces.internal.impl.xpath.regex".  Is there any way I can use these packages in kdl-11.0.8.10-hotspot?

## Context

Java version:kdl-11.0.8.10-hotspot

Your operating system and platform:

Windows 10 on x64"

Thank you for your support.

**Comment by aahlenst** [comment]
With JDK 9, the Java Platform Module System was introduced. As part of that, access to internal APIs was shut off that should not have been used in the first place. Resolution: Upgrade your dependencies, stop using internal APIs. In the case of Xerces, the library is available from https://xerces.apache.org/.
