### ISSUE TITLE
MulticastSocket.joinGroup crashes with Java 15 @Windows Server 2008

### ISSUE THREAD

**Issue by xlemmingx** [AdoptOpenJDK/openjdk-support#203]
## Summary

Behaviour of **MulticastSocket.joinGroup(SocketAddres, NetworkInterface)** changed with Java 15 and leads to an java.net.BindException. Same code on same machine works with Java 14.

## Steps to reproduce

Following code executed in jshell reproduces the error:

`var multiCastSocket = new MulticastSocket(12345);`
`var multicastInterface = NetworkInterface.getByInetAddress(InetAddress.getByName("IP_ADDRESS_OF_A_LOCAL_INTERFACE"));`
`multiCastSocket.joinGroup(new InetSocketAddress(InetAddress.getByName("224.0.0.128"), 12345), multicastInterface);`

## Expected results

Joining defined multi cast group of given IP ("224.0.0.128").

## Actual results

> java.net.BindException: Cannot assign requested address: no further information
at java.base/sun.nio.ch.Net.joinOrDrop4(Native Method)
at java.base/sun.nio.ch.Net.join4(Net.java:682)
at java.base/sun.nio.ch.DatagramChannelImpl.innerJoin(DatagramChannelImpl.java:1533)
at java.base/sun.nio.ch.DatagramChannelImpl.join(DatagramChannelImpl.java:1551)
at java.base/sun.nio.ch.DatagramSocketAdaptor.joinGroup(DatagramSocketAdaptor.java:532)
at java.base/java.net.MulticastSocket.joinGroup (MulticastSocket.java:329)

## Triaging info

Java version:

openjdk version "15.0.1" 2020-10-20
OpenJDK Runtime Environment AdoptOpenJDK (build 15.0.1+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 15.0.1+9, mixed mode, sharing)

What is your operating system and platform?

Windows Server 2008 R2

How did you install Java?

Installed by binary archive extraction downloaded from adoptopenjdk.org

Did it work before?

Never worked with Java 15 but worked before upgrade.

Did you test with other Java versions?

Same example as above works with java 14:
openjdk version "14" 2020-03-17
OpenJDK Runtime Environment AdoptOpenJDK (build 14+36)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 14+36, mixed mode, sharing)

Unfortunately we currently still have to use a Windows Server 2008 on local development network for some purposes. This is the only system on which we've got this problem

**Comment by aahlenst** [comment]
If it only happens on Windows Server 2008, you're out of luck. The oldest supported Windows version is Windows Server 2012 R2 (see https://openjdk.java.net/groups/build/doc/building.html).

This might have been caused by https://bugs.openjdk.java.net/browse/JDK-8235674 which delivered a new implementation of the DatagramSocket API.
