### ISSUE TITLE
NetBeans 12.0 Profiler crashes with EXCEPTION_ACCESS_VIOLATION when trying to profile Methods

### ISSUE THREAD

**Issue by lbruby** [AdoptOpenJDK/openjdk-support#208]
I am doing Java development on Windows 8.1, using NetBeans 12.0 and AdoptOpenJDK 11.0.9.11-hotspot. I'm trying to run the NetBeans Profiler. If I select to profile Methods, Java crashes. This is what comes out on the console. I will also attach the log that got dumped:

```
Profiler Agent: Waiting for connection on port 5140, timeout 10 seconds (Protocol version: 18)
Profiler Agent: Established connection with the tool
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.netbeans.lib.profiler.server.ClassLoaderManager to method java.lang.ClassLoader.findLoadedClass(java.lang.String)
WARNING: Please consider reporting this to the maintainers of org.netbeans.lib.profiler.server.ClassLoaderManager
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Profiler Agent: Local accelerated session
Starting main
In TestClass Constructor
In RunTestClass
Type something: 
48484848484848484848
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ff893055fab, pid=11300, tid=18484
#
# JRE version: OpenJDK Runtime Environment AdoptOpenJDK (11.0.9+11) (build 11.0.9+11)
# Java VM: OpenJDK 64-Bit Server VM AdoptOpenJDK (11.0.9+11, mixed mode, tiered, compressed oops, g1 gc, windows-amd64)
# Problematic frame:
# V  [jvm.dll+0x5a5fab]
#
# No core dump will be written. Minidumps are not enabled by default on client versions of Windows
#
# An error report file with more information is saved as:
# D:\mysoftware\NB12.0_TestProjects\TestProfilerNoFX\hs_err_pid11300.log
#
# If you would like to submit a bug report, please visit:
#   https://github.com/AdoptOpenJDK/openjdk-support/issues
#
Profiler Agent: Initializing...
Profiler Agent: Options: >C:\Program Files\NetBeans-12.0\netbeans\profiler\lib,5140,10<
Profiler Agent: Initialized successfully
Profiler Agent: 250 classes cached.
Profiler Agent: 250 classes cached.
Profiler Agent: 250 classes cached.
Profiler Agent: 250 classes cached.
Profiler Agent: 250 classes cached.
D:\mysoftware\NB12.0_TestProjects\TestProfilerNoFX\nbproject\build-impl.xml:1460: The following error occurred while executing this line:
D:\mysoftware\NB12.0_TestProjects\TestProfilerNoFX\nbproject\build-impl.xml:1330: The following error occurred while executing this line:
D:\mysoftware\NB12.0_TestProjects\TestProfilerNoFX\nbproject\build-impl.xml:936: Java returned: 1
BUILD FAILED (total time: 2 seconds)
```
It doesn't matter how simple the NetBeans project code is. It always crashes. 

TO REPRODUCE:

Install AdoptOpenJDK 11.0.9.11-hotspot on Windows 
Install NetBeans 12.0 LTS, it is available from Apache
Start NetBeans
Import the NetBeans Project ProfileCrashNoFX.zip I will attach to this issue.
Verify that there is a  JDK 11 Platform created in the Platform manager with a path to where you have AdoptOpenJDK 11.0.9.11-hotspot installed, and that this platform is selected under the Project Properties/Libraries settings, and for the Source setting. 

If you do not have JAVA_HOME set to the path of AdoptOpenJDK 11.0.9.11-hotspot, you can edit the netbeans.conf file, which is in Program Files\<where you have Netbeans 12.0>\netbeans\etc and enter this for netbeans_jdkhome 
netbeans_jdkhome="C:\Program Files\AdoptOpenJDK\jdk-11.0.9.11-hotspot"

Build the project. 
Right click on the Project name under the Projects tab and select Profile from the pop-up menu
A Profile tab should open in the Edit area of the screen
Click the down arrow next to the word Profile that is next to a green right arrow
Select Methods
Click the Green arrow to start the profiler
The profiler should run the application. The application displays a few strings on the Console and asks for a line of input. Should be able to type in the input and press enter and have the input displayed back. Instead the JVM crashes. 

Java version: 
openjdk version "11.0.9" 2020-10-20
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.9+11)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.9+11, mixed mode)

What is your operating system and platform?
Windows 8.1 Professional on ASUS laptop with Intel i7-4720HQ CPU @ 2.60 GHz

How did you install Java?
Used OpenJDK11U-jdk_x64_windows_hotspot_11.0.9_11.msi

Did it work before?
This was the first time I tried it

Did you test with other Java versions?
Yes. Tried Java 9.0.4 both for compiling and running the project, and for running NetBeans and the profiler. Got the same result. 
Tried AdoptOpenJDK 15.0.1.9-hotspot for both compiling and running the project, and for running NetBeans and the profiler. Same result.

[hs_err_pid11300.log](https://github.com/AdoptOpenJDK/openjdk-support/files/5563722/hs_err_pid11300.log)
[TestProfilerNoFX.zip](https://github.com/AdoptOpenJDK/openjdk-support/files/5563723/TestProfilerNoFX.zip)

**Comment by lbruby** [comment]
Sorry about the large font that got pasted in. It didn't look like that until after I submitted.

**Comment by aahlenst** [comment]
The crash happened in profilerinterface.dll. It's therefore not a Java issue. Please see https://issues.apache.org/jira/browse/NETBEANS-1428.

**Comment by lbruby** [comment]
Thank you. Your message ended up in my spam folder and I didn't find it until today.

Lisa

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
