### ISSUE TITLE
Link to last built for macOS 10.9

### ISSUE THREAD

**Issue by Sciss** [AdoptOpenJDK/openjdk-support#212]
**Problem description:**

I have a user on macOS 10.9; it's not possible to find an AdoptOpenJDK built supporting 10.9 (it seems 10.10 is the minimum). Would it be possible to provide an archive link for JDK 11 (or JDK 8 if not possible) that runs on macOS 10.9? Thank you!

**Comment by aahlenst** [comment]
Best chance is 8 before notarization, that's probably January 20. So try with 8u242 and then go back version by version until you find one: https://adoptopenjdk.net/archive.html?variant=openjdk8&jvmVariant=hotspot. 9+ were always supposed to be built on 10.10 or newer.

**Comment by aahlenst** [comment]
Question has been answered. If there is anything left to answer, I'm happy to reopen.
