### ISSUE TITLE
com.sun.management.OperatingSystemMXBean.getSystemCpuLoad not reliable on openjdk11:alpine-jre

### ISSUE THREAD

**Issue by macqm** [AdoptOpenJDK/openjdk-support#215]
**What are you trying to do?**
Our Java service is sending statistics (via [micrometer](https://github.com/micrometer-metrics/micrometer/blob/master/micrometer-core/src/main/java/io/micrometer/core/instrument/binder/system/ProcessorMetrics.java)) to Datadog. I recently switched our base Docker image to openjdk11:alpine-jre and noticed issues with the values reported by `getSystemCpuLoad` from `com.sun.management.OperatingSystemMXBean`. 
The container is deployed to a AWS EKS Pod.

**Expected behaviour:**
systemCpuLoad reports the correct CPU usage. I'd expect `adoptopenjdk/openjdk11:alpine-jre` to behave same way as other base images. I previously used a custom image based on centos:6 base image with  *OpenJDK11U-jdk_x64_linux_hotspot_11.0.3_7* and the `com.sun.management.OperatingSystemMXBean.getSystemCpuLoad` reported values corresponding to CPU usage reported by other metrics we collect. 

**Observed behaviour:**
In one environment, the method reports 1.0 constantly, even though the CPU usage from the Java process is below 10% on average.
In another environment, the method seems to have converged at a lower value (~0.2) and also doesn't reflect the actual CPU usage.

**Any other comments:**
I ruled out that it's an issue with Datadog - it just displays the metric it receives from our Java process.

From the container:
```
# uname -ar
Linux (hostname) 4.14.181-140.257.amzn2.x86_64 AdoptOpenJDK/openjdk-build#1 SMP Wed May 27 02:17:36 UTC 2020 x86_64 Linux

# java --version
openjdk 11.0.9 2020-10-20
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.9+11)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.9+11, mixed mode)
```

This is a sample Java program that I was able to build on my EKS node and repro the issue - however I cannot repro the issue locally in the Docker container (on the exact same version of OpenJDK). Not sure if this an issue with the image itself or a combination of host Kernel and image, but I couldn't repro this exact issue with centos.

```java

import com.sun.management.OperatingSystemMXBean;
import java.lang.management.ManagementFactory;
import java.math.RoundingMode;
import java.text.DecimalFormat;
import java.lang.Thread;

public class Program {
    public static void main(String[] args) throws InterruptedException {
        OperatingSystemMXBean osBean = (OperatingSystemMXBean)ManagementFactory.getOperatingSystemMXBean();
        try {
            while(true) {
                double load = osBean.getSystemCpuLoad();
                if (load < 0.0) {
                    // OS doesn't support this
                    load = 0.0;
                }

                DecimalFormat df = new DecimalFormat();
                df.setRoundingMode(RoundingMode.DOWN);
                df.setMaximumFractionDigits(4);

                System.out.println("Usage: " + df.format(load));

                Thread.sleep(1000);
            }
        } catch(Exception ex) {
            System.out.println(ex.getMessage());
            return;
        }
    }
}
```

**Comment by aahlenst** [comment]
cc @dinogun

**Comment by jerboaa** [comment]
This has nothing to do with centos vs. alpine. You are comparing JDK 11.0.3 with JDK 11.0.9. With JDK 11.0.9+ this has been added:
https://bugs.openjdk.java.net/browse/JDK-8248803

If you want to have the old behaviour back, i.e. get the host system (in your case likely the node your container runs on), pass `-XX:-UseContainerSupport` argument.

In order to be able to reproduce this locally, you'd have to have certain CPU quotas in place and run the JDK in a container.

**Comment by macqm** [comment]
Thanks @jerboaa - I understand more about what is happening now.
I would question however, the [implementation of this method](https://hg.openjdk.java.net/jdk-updates/jdk11u-dev/rev/42ac9f56bc42):
```java
  public double getSystemCpuLoad() {
+        if (containerMetrics != null) {
+            long quota = containerMetrics.getCpuQuota();
+            if (quota > 0) {
+                long periodLength = containerMetrics.getCpuPeriod();
+                long numPeriods = containerMetrics.getCpuNumPeriods();
+                long usageNanos = containerMetrics.getCpuUsage();
+                if (periodLength > 0 && numPeriods > 0 && usageNanos > 0) {
+                    long elapsedNanos = TimeUnit.MICROSECONDS.toNanos(periodLength * numPeriods);
+                    double systemLoad = (double) usageNanos / elapsedNanos;
+                    // Ensure the return value is in the range 0.0 -> 1.0
+                    systemLoad = Math.max(0.0, systemLoad);
+                    systemLoad = Math.min(1.0, systemLoad);
+                    return systemLoad;
+                }
+                return -1;
````
If you have a cpu quota then, the CPU load is calculated as:
`min(0, max(1, cpuacct.usage / (cpu.stats.nr_periods * cpu.cfs_period_us * 1000))`

These values come from:
- `/sys/fs/cgroup/cpuacct/cpuacct.usage`,
- `/sys/fs/cgroup/cpu/cpu.cfs_period_us`,
    and `/sys/fs/cgroup/cpu/cpu.stat`.

This makes it a _cummulative_ usage value -  whereas the documentation mentions `Returns the "recent cpu usage" for the whole system.`.

Given that the value is cumulative, I understand now why it converged to 0.22 in one of our environments in a smooth curve. 

I don't know what "recent usage" means exactly, but one idea would be for this method to return:
`delta_cpuacct.usage / (delta_cpu.stats.nr_periods * cpu.cfs_period_us * 1000)` 
... and delta being delta between now and... the from pervious call? 

The other concern is that it calculates the usage based on `cpuacct.usage` but also caps it at 1.0, meaning that if your quotas allow for more than 1 core usage, you are very likely to reach 1.0 and stay there.
Perhaps a better calculation should involve `cpuacct.usage_percpu` instead and return average usage per core?

**Comment by jerboaa** [comment]
@macqm Feel free to read the review thread of when this got implemented. Maybe that'll give you some idea why certain approaches have been taken.
https://mail.openjdk.java.net/pipermail/serviceability-dev/2019-December/029923.html

If you want to change/discuss the implementation please raise this upstream on the mailing list (serviceability-dev would be a good candidate).

Note that when the documentation was written, there were no such things as containers and cgroups. It needs to be taken with a grain of salt these days.

On the note of documentation, you mentioned "recent cpu usuage". While I cannot answer the question as to why that algo was chosen, the doc answers why it returns a value in the interval [0.0,1.0]. The documentation[1] says: `This value is a double in the [0.0,1.0] interval.`

https://docs.oracle.com/en/java/javase/11/docs/api/jdk.management/com/sun/management/OperatingSystemMXBean.html#getSystemCpuLoad()
