### ISSUE TITLE
JDK not found by program

### ISSUE THREAD

**Issue by frmaurer99** [AdoptOpenJDK/openjdk-support#218]
## Question

I installed the program Blue (https://blue.kunstmusik.com) which needed a Java 11 SDK so I installed OpenJDK11U-jdk_x64_windows_hotspot_11.0.9.1_1.
I used the option to add JAVA_HOME and I checked this is pointing to C:\Program Files\AdoptOpenJDK\jdk-11.0.9.101-hotspot\

But for some reason the program is not able to find the java install.
Am I missing something?

Thanks Frank
## Context

Java version:

C:\Users\frmau>java -version
openjdk version "11.0.9.1" 2020-11-04
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.9.1+1)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.9.1+1, mixed mode).

Your operating system and platform:
Windows 10 64bit

**Comment by aahlenst** [comment]
I suggest reading the docs of Blue or asking the creators of Blue how Blue expects to find the JDK. Otherwise it's hard to say what might be wrong.

Normally, programs look at `PATH` (should point to `C:\Program Files\AdoptOpenJDK\jdk-11.0.9.101-hotspot\bin`) or `JAVA_HOME` (looks accurate in your example). A restart might help, too.

**Comment by karianna** [comment]
Also check that you're dealing with the space character in Program Files correctly

**Comment by frmaurer99** [comment]
Thank you very much. The creator of Blue did come up with an answer even if he didn't figure out why it was not working as expected.

Thanks again
Frank

**Comment by aahlenst** [comment]
@frmaurer99 Would be great if you could tell us what the problem was in case somebody needs help in the future.

**Comment by frmaurer99** [comment]
The problem was that the program did not know where the JDK was installed as per the original question. The recommended fix was to add a jdkhome directory path to the blue.config file. This entry already existed in the file but was commented out so all I had to do was copy the corresct path into the value and un-comment the line.
