### ISSUE TITLE
JVM Crashing when use sigar 1.6.4

### ISSUE THREAD

**Issue by peiyanfei** [AdoptOpenJDK/openjdk-support#22]
OS: Windows Server 2012 R2 ,  64 bit build 9600 (6.3.9600.17415)
JRE: 1.8.0_222-b10  64bit
Native frames:
C  [sigar-amd64-winnt.dll+0x14ed4]
C  [sigar-amd64-winnt.dll+0x22718]

Java frames:
j org.hyperic.sigar.Sigar.getCpuListNative()[Long/hyperic/sigar/Cpu;+0

I have try some versions:
AdoptOpenJDK Builds:
OpenJDK8U-jre_x64_windows_hotspot_8u192b12             jvm not crash
OpenJDK8U-jre_x64_windows_hotspot_8u222b10             jvm crash
OpenJDK8U-jre_x64_windows_hotspot_8u232b09             jvm crash

OpenJDK upstream builds:
OpenJDK8u-jre_x64_windows_8u232b09                            jvm not crash

I think something wrong with the last builds of AdoptOpenJDK.

**Comment by aahlenst** [comment]
@karianna Could you extract additional information?

@peiyanfei You wrote something about a test program. Please share so that we can reproduce the problem. Otherwise, we cannot work on it.

**Comment by karianna** [comment]
@peiyanfei - Apologies I didn't not appear to receive it, what size is that file?

**Comment by jloisel** [comment]
Hi, same issue here with the program available here:
https://github.com/OctoPerf/jmx-agent/releases

Simply run the jar using java.

The dump:

```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00000001800156c4, pid=10136, tid=8160
#
# JRE version: OpenJDK Runtime Environment (14.0.1+7) (build 14.0.1+7)
# Java VM: OpenJDK 64-Bit Server VM (14.0.1+7, mixed mode, sharing, tiered, compressed oops, g1 gc, windows-amd64)
# Problematic frame:
# C  [sigar-amd64-winnt.dll+0x156c4]
#
# No core dump will be written. Minidumps are not enabled by default on client versions of Windows
#
# An error report file with more information is saved as:
# C:\Users\Utilisateur\Documents\GitHub\jmx-agent\metrics-agent\target\hs_err_pid10136.log
#
# If you would like to submit a bug report, please visit:
#   https://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
```

[hs_err_pid3428.log](https://github.com/AdoptOpenJDK/openjdk-support/files/4729900/hs_err_pid3428.log)
[hs_err_pid10136.log](https://github.com/AdoptOpenJDK/openjdk-support/files/4729901/hs_err_pid10136.log)

**Comment by aahlenst** [comment]
It crashes in Sigar's native code in various places which indicates that it is a problem with Sigar. However, it does not crash with Red Hat's upstream build. Looking at the output of `dumpbin /headers` (Section "Optional Header Values", entry "linker version") of the different binaries, the values are as follows:

* Sigar: 9.0 (VS 2008)
* Upstream 8u252: 10.0 (VS 2010)
* AdoptOpenJDK 8u252: 12.0 (VS 2013)

For translating the linker versions to Visual Studio versions, see https://mariusbancila.ro/blog/2015/08/12/version-history-of-vc-mfc-and-atl/.

@karianna Is my conclusion correct that this is most likely toolchain related and the right course of action would be to recompile Sigar?

**Comment by aahlenst** [comment]
@jloisel I don't follow. https://github.com/OctoPerf/jmx-agent/releases says the software is only compatible to Java 8. Besides, I just got a crash on 8.

**Comment by jloisel** [comment]
Yeah, I've put the warning because it crashes due to Sigar DLL not working on Java 9+. BEsides, the agent only runs on Windows.

**Comment by aahlenst** [comment]
It's more likely to crash on newer JDKs if it's toolchain related because those are even built with VS 2017.

**Comment by jloisel** [comment]
What do you mean by toolchain? There is an open issue in Sigar repo too:
https://github.com/hyperic/sigar/issues/136

On my computer, it works with JDK8 and crashes all the time with JDK9+.

**Comment by aahlenst** [comment]
I managed to recompile Sigar with the same VS version that we're using (VS 2017). This does not help. Zulu 11.0.7 (built with VS 2017) crashes, too.

Everything indicates that this is a problem within Sigar. I recommend to patch Sigar or to select a tool that is being maintained.

**Comment by jloisel** [comment]
There is sadly no alternative to Sigar, but thanks anyway.

**Comment by peiyanfei** [comment]
> There is sadly no alternative to Sigar, but thanks anyway.
May be use oshi instead.
github.com/oshi

**Comment by cnstar9988** [comment]
It is sigar 1.6.4 bug.
 
https://github.com/hyperic/sigar/issues/141
https://github.com/cnstar9988/sigar/commit/9e5dba8d520cca718209d93fb89a4c5daebb7655

**Comment by abserali786** [comment]
I downloaded another sigar 1.6.4 jar (1.6.4.129 (17.1.2016) release) from below link and placed in specific tool lib path (ServerAgent-2.2.3\lib).., then it worked for me.

https://javalibs.com/artifact/org.hyperic/sigar
