### ISSUE TITLE
[macos] support full window content options

### ISSUE THREAD

**Issue by kovdb** [AdoptOpenJDK/openjdk-support#228]
## Summary
Missing support for the following client properties:
"apple.awt.fullWindowContent"
"apple.awt.transparentTitleBar"

Support for these client properties is quite important since the following client property is no longer supported:
"apple.awt.brushMetalLook"

## Steps to reproduce
Run the test program.

```
import java.awt.Dimension;

import javax.swing.JFrame;
import javax.swing.SwingUtilities;

public class FullWindowContentWindowTest {
	public static void main(String[] arguments) {
		SwingUtilities.invokeLater(new Runnable() {
			@Override
			public void run() {
				JFrame frame = new JFrame("A full window content JFrame");
				frame.getRootPane().putClientProperty("apple.awt.fullWindowContent", true);
				frame.getRootPane().putClientProperty("apple.awt.transparentTitleBar", true);

				frame.setSize(new Dimension(400, 400));
				frame.setLocationByPlatform(true);
				frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
				
				frame.setVisible(true);
			}
		});
	}
}
```

## Expected results
A window without a visible title bar.

## Actual results
A window with a visible title bar.

## Triaging info

Java version:

openjdk version "1.8.0_282-internal"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_282-internal-202012141712-b05)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.282-b05, mixed mode)

What is your operating system and platform?
macOS Big Sur (version 11.0.1) on Intel

How did you install Java?
an installer package

Did it work before?
No

Did you test with other Java versions?
Yes

It works when using the JDK from Oracle:
java version "1.8.0_271"
Java(TM) SE Runtime Environment (build 1.8.0_271-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.271-b09, mixed mode)

Was fixed in JDK-8212549
https://bugs.java.com/bugdatabase/view_bug.do?bug_id=8211301

**Comment by aahlenst** [comment]
If I read https://bugs.openjdk.java.net/browse/JDK-8211301 correctly, it was backported to OpenJDK 11, not to OpenJDK 8 but to Oracle JDK 8. This would explain the difference. The backport should happen at OpenJDK.

**Comment by aahlenst** [comment]
Okay, I verified that indeed Oracle JDK has the backport but neither AdoptOpenJDK 8 nor Azul Zulu 8 has it. I have prepared a patch for OpenJDK 8, but now starts the tricky part: Getting it into OpenJDK.

**Comment by aahlenst** [comment]
Patch is awaiting backport approval.

**Comment by aahlenst** [comment]
Patch has landed in 8u-dev and should arrive with 8u292, due in April.
