### ISSUE TITLE
JVM crashes using AdoptOpenJDK 15 OpenJ9 and Gradle 6.7.1

### ISSUE THREAD

**Issue by Jeeppler** [AdoptOpenJDK/openjdk-support#229]
I tested it in a Debian 10 container with Gradle 6.7.1 and AdoptOpenJDK 15 OpenJ9. It crashed immediately with a JVM dump.

~~~
./gradlew tasks
Unhandled exception
Type=Segmentation error vmState=0x00000000
…
~~~

Java Version:

~~~
java --version
openjdk 15.0.1 2020-10-20
OpenJDK Runtime Environment AdoptOpenJDK (build 15.0.1+9)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.23.0, JRE 15 Linux amd64-64-Bit Compressed References 20201022_81 (JIT enabled, AOT enabled)
OpenJ9   - 0394ef754
OMR      - 582366ae5
JCL      - ad583de3b5 based on jdk-15.0.1+9)
~~~

I did the same test with AdoptOpenJDK 15 Hotspot and everything worked out of the box in the same environment.

This issue might be in the wrong repository as this issue is not related to `hombrew-opendjdk`, but I do not know where else to post it.

**Comment by adamfarley** [comment]
If it's an OpenJ9-specific segmentation error, I'd advise raising an OpenJ9 issue here: https://github.com/eclipse/openj9

**Comment by Jeeppler** [comment]
@adamfarley thanks. Opened the issue here: https://github.com/eclipse/openj9/issues/11508

**Comment by pshipton** [comment]
This one can be closed.
