### ISSUE TITLE
SIGFPE on Apple Silicon during division by zero

### ISSUE THREAD

**Issue by vmdarji85** [AdoptOpenJDK/openjdk-support#231]
Hello, I am getting fatal error when i am trying to compile simple java program which contain error.  I am using New macbook pro with M1. 

program :

class Test {

	public static void main(String[] args) {
		
		try {
			System.out.println("try");
			System.out.println(10/0); -> This is where I am getting fatal error instead of AEException.
		} catch (ArithmeticException e) {
			System.out.println("catch");
		}finally {
			System.out.println("finally");
		}
	}

}

Here is complete error message

A fatal error has been detected by the Java Runtime Environment:

SIGFPE (0x8) at pc=0x0000000118e9ea48, pid=4481, tid=7683

JRE version: Java(TM) SE Runtime Environment 18.9 (11.0.9+7) (build 11.0.9+7-LTS)
Java VM: Java HotSpot(TM) 64-Bit Server VM 18.9 (11.0.9+7-LTS, mixed mode, tiered, compressed oops, g1 gc, bsd-amd64)
Problematic frame:
j  com.sun.tools.javac.comp.ConstFold.fold2(ILcom/sun/tools/javac/code/Type;Lcom/sun/tools/javac/code/Type;)Lcom/sun/tools/javac/code/Type;+877 jdk.compiler@11.0.9
 No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again

Compiled method (c1)     884  193       3       java.lang.System::getSecurityManager (4 bytes)
 total in heap  [0x0000000119455010,0x0000000119455338] = 808
 relocation     [0x0000000119455178,0x00000001194551a0] = 40
 main code      [0x00000001194551a0,0x0000000119455260] = 192
 stub code      [0x0000000119455260,0x00000001194552f0] = 144
 metadata       [0x00000001194552f0,0x00000001194552f8] = 8
 scopes data    [0x00000001194552f8,0x0000000119455300] = 8
 scopes pcs     [0x0000000119455300,0x0000000119455330] = 48
 dependencies   [0x0000000119455330,0x0000000119455338] = 8
Could not load hsdis-amd64.dylib; library not loadable; PrintAssembly is disabled

**Comment by aahlenst** [comment]
On M1, either use https://github.com/microsoft/openjdk-aarch64/releases/tag/16-ea%2B10-macos or https://www.azul.com/downloads/zulu-community/?os=macos&architecture=arm-64-bit&package=jdk. Those are native ports for Apple Silicon without Rosetta 2.

**Comment by aahlenst** [comment]
BTW: `Could not load hsdis-amd64.dylib; library not loadable; PrintAssembly is disabled` is not the error. hsdis is the HotSpot disassembler and part of PrintAssembly. See https://wiki.openjdk.java.net/display/HotSpot/PrintAssembly for more information. It is an optional part of OpenJDK (there seem to be some licensing issues related to binutils). The message merely informs that PrintAssembly is unavailable, not that it is the reason of the crash.

**Comment by vmdarji85** [comment]
Hi @aahlenst ,

I am new to java and i dont know why i need to download macOS+AArch64 port for java to run my program. Can you provide more information?

**Comment by aahlenst** [comment]
For the last 10+ years, computers manufactured by Apple had only processors made by Intel with the x86-64 instruction set. So JDKs for macOS targeted x86-64. The new devices released last fall with the M1 CPU (Apple Silicon) use the ARMv8 instruction set that OpenJDK calls aarch64. Apple included a software-based emulation program in macOS 11 called Rosetta 2 that should make it possible to run code for x86-64 on Apple Silicon. Most programs actually run well on Rosetta 2, OpenJDK does apparently not. The links I provided above offer downloads of JDKs specifically produced for the M1. They should run faster and have less bugs.

**Comment by aahlenst** [comment]
Closing due to lack of requested feedback. We're happy to reopen the issue if feedback is provided by the OP (or anybody else) at a later date.
