### ISSUE TITLE
JFileChooser unable to open directories on OSX

### ISSUE THREAD

**Issue by JohnLussmyer** [AdoptOpenJDK/openjdk-support#233]
## Summary
The issue from the customer is:
I can't get a listing anymore of the folders when trying to import a product csv file. Desktop still works OK, but as soon as I go deeper into other folders with more subfolders and files the window stays blank.

## Steps to reproduce
Use JFileChooser on some OSX boxes.
We are currently using Adopt OpenJDK 11.0.7.
This is being seen on OSX 10.15.7, but only on SOME boxes with that version of OSX.  (and of course, not on any of ours, only the customers)

Also see: https://developer.apple.com/forums/thread/132986?page=1#655765022

## Expected results
JFileChooser can traverse directory tree.

## Actual results
Only the Desktop folder works.

## Triaging info

openjdk 11.0.9.1 2020-11-04
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.9.1+1)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.9.1+1, mixed mode)

What is your operating system and platform?
OSX 10.15.7

How did you install Java?
embedded in .app

Did it work before?
Still works on MOST systems, just not all.

**Comment by aahlenst** [comment]
[A JBS search](https://bugs.openjdk.java.net/browse/JDK-8227836?jql=labels%20%3D%20macos%20AND%20text%20~%20%22JFileChooser%22) did not reveal anything noteworthy.

Can you please share a sample (Main class) that triggers the problem at least on your customer's computer?

**Comment by aahlenst** [comment]
Closing due to lack of requested feedback. We're happy to reopen the issue if feedback is provided by the OP (or anybody else) at a later date.
