### ISSUE TITLE
awt.Robot keyPress/mouseMove don't function under Mac OS Big Sur

### ISSUE THREAD

**Issue by amharrison** [AdoptOpenJDK/openjdk-support#235]
## Summary
java.awt.Robot does not issue keyPress/keyRelease or mouseMove events under Big Sur. The request for mouse/keyboard control should trigger a security prompt from the OS, but it does not. Adding the appropriate java binary under System Preferences/Security & Privacy/Privacy/Accessibility has no effect.

## Steps to reproduce
Run the following under Big Sur.

```
import java.awt.FlowLayout;
import java.awt.MouseInfo;
import java.awt.Point;
import java.awt.Robot;
import java.awt.event.KeyEvent;

import javax.swing.JFrame;
import javax.swing.JTextArea;
import javax.swing.SwingUtilities;

public class RobotTest {

	public static void main(String[] args) {
		
		
		System.err.println("Java Version : "+System.getProperty("java.version"));
		System.err.println(System.getProperty("os.name")+" "+System.getProperty("os.version"));
		
		
		JFrame frame = new JFrame("test");
		frame.getContentPane().setLayout(new FlowLayout());
		JTextArea textArea = new JTextArea(10, 10);
		frame.getContentPane().add(textArea);
		frame.pack();
		frame.setVisible(true);
		textArea.requestFocus();

		try {			
			Robot robot = new Robot();
			robot.setAutoDelay(40);
			robot.setAutoWaitForIdle(true);

			Point p = new Point(textArea.getWidth(), textArea.getHeight());
			SwingUtilities.convertPointToScreen(p, textArea.getParent());
			System.err.println("Moving to " + p);

			robot.mouseMove(p.x, p.y);
			Point dest = MouseInfo.getPointerInfo().getLocation();
			
			if(dest.equals(p))
				System.err.println("mouseMove works");
			else
				System.err.println("mouseMove doesn't work");
			
			int[] keys = { KeyEvent.VK_T, KeyEvent.VK_E, KeyEvent.VK_S, KeyEvent.VK_T };
			for (int key : keys) {
				robot.delay(100);
				robot.keyPress(key);
				robot.delay(10);
				robot.keyRelease(key);
			}
			
			if("test".equals(textArea.getText()))
				System.err.println("keyPress works");
			else
				System.err.println("keyPress doesn't work");

		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

	}

}

```

## Expected results
The mouse should move to the lower corner of the text area. Then "test" should be typed into the text area. The test should print out 

Java Version : 15.0.1
Mac OS X 10.16
Moving to java.awt.Point[x=120,y=213]
mouseMove works
keyPress works

## Actual results
No mouse movement or keypress.

Java Version : 15.0.1
Mac OS X 10.16
Moving to java.awt.Point[x=120,y=213]
mouseMove doesn't work
keyPress doesn't work

## Triaging info

Java version:
openjdk 15.0.1 2020-10-20
OpenJDK Runtime Environment AdoptOpenJDK (build 15.0.1+9)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.23.0, JRE 15 Mac OS X amd64-64-Bit Compressed References 20201130_124 (JIT enabled, AOT enabled)
OpenJ9   - 0394ef754
OMR      - 582366ae5
JCL      - ad583de3b5 based on jdk-15.0.1+9)

What is your operating system and platform?
Mac OS Big Sur (11.1)

How did you install Java?
installer package from adoptjdk.

Did it work before?
mouseMove worked preCatalina, but Catalina broke keyPress. I vaguely recall a combination preCatalina that worked. :/

Did you test with other Java versions?

openjdk 15.0.1 2020-10-20
OpenJDK Runtime Environment AdoptOpenJDK (build 15.0.1+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 15.0.1+9, mixed mode, sharing)

openjdk version "1.8.0_275"
OpenJDK Runtime Environment (build 1.8.0_275-b01)
Eclipse OpenJ9 VM (build openj9-0.23.0, JRE 1.8.0 Mac OS X amd64-64-Bit Compressed References 20201112_760 (JIT enabled, AOT enabled)
OpenJ9   - 0394ef754
OMR      - 582366ae5
JCL      - b52d2ff7ee based on jdk8u275-b01)

openjdk version "17-ea" 2021-09-14
OpenJDK Runtime Environment (build 17-ea+4-165)
OpenJDK 64-Bit Server VM (build 17-ea+4-165, mixed mode, sharing)

**Comment by aahlenst** [comment]
Thanks a lot for the detailed report including a reproducer. It sounds similar to https://github.com/AdoptOpenJDK/openjdk-support/issues/222. That issue is about the mic, but the required interaction with macOS should be the same.

The big challenge is that nobody here really has the necessary expertise with both Java and macOS to diagnose what the exact problem is: missing entitlements, wrong app layout (as https://github.com/AdoptOpenJDK/openjdk-support/issues/222#issuecomment-753938200 suggests), missing API implemented by Java? https://github.com/AdoptOpenJDK/openjdk-support/issues/222#issuecomment-749682486 has some initial analysis.

Ultimately, the problem needs to be resolved at OpenJDK anyway. If you have the knowledge from the macOS side, @amharrison, it might make sense to send your diagnose incl. the reproducer to https://mail.openjdk.java.net/mailman/listinfo/awt-dev. Maybe someone there can give guidance for the Java side of things.

**Comment by amharrison** [comment]
Just got back from a deep dive into OpenJDK's bug tracker and found this [gem](https://bugs.java.com/bugdatabase/view_bug.do?bug_id=8226553), extrapolated a few OS versions, it suggests that it's not java's permissions that are invalid, they seem to be inherited from the parent application. If the parent application has the permissions (for "Developer Tools", not "Accessibility"), so too will java. So it's Terminal or the launching IDE that needs the permissions, not java. Once this is done, robot is functional again.

We can mark this as closed.

**Comment by rcampbellnc** [comment]
On MacOS 11.3 (Big Sur) - found that I had to:
a) provide Java with Accessibility (under System Preferences -> Security & Privacy) access
b) provide Java with Screen Recording ((under System Preferences -> Security & Privacy) access
Running my app from the terminal, I was prompted to allow filesystem access and told about the screen recording in preferences, but the Accessibility was not mentioned in the system messages on MacOS 11.3.
