### ISSUE TITLE
GPG key unavailable

### ISSUE THREAD

**Issue by kag0** [AdoptOpenJDK/openjdk-support#237]
The adoptopenjdk GPG key is unavailable over HTTP. This prevents installation and is breaking my CI builds (and I imagine others as well)

curl:
```
> GET /adoptopenjdk/api/gpg/key/public HTTP/1.1
> Host: adoptopenjdk.jfrog.io
> User-Agent: curl/7.68.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 503 Service Temporarily Unavailable
< Date: Tue, 12 Jan 2021 22:10:43 GMT
< Content-Type: text/html
< Content-Length: 190
< Connection: keep-alive
< 
<html>
<head><title>503 Service Temporarily Unavailable</title></head>
<body>
<center><h1>503 Service Temporarily Unavailable</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

In the meantime, try this to workaround
```
- gpg --keyserver keyserver.ubuntu.com --recv-keys 74885C03
- gpg --export --armor 74885C03 | apt-key add -
```

EDIT: 
actually all of adoptopenjdk.jfrog.io seems to be down so nothing can be installed from there even with the key.

**Comment by mo8Zomo0** [comment]
yes, as you added, other services are down as well, like the debian rep. I was just googling for 503 adoptopenjdk and found your case.

Debian error (in case the IP (35.231.52.82) is of interest):

Err:4 https://adoptopenjdk.jfrog.io/adoptopenjdk/deb buster InRelease       
  503  Service Temporarily Unavailable [IP: 35.231.52.82 443]
Reading package lists... Done                         
W: Failed to fetch https://adoptopenjdk.jfrog.io/adoptopenjdk/deb/dists/buster/InRelease  503  Service Temporarily Unavailable [IP: 35.231.52.82 443]

**Comment by mo8Zomo0** [comment]
btw, seems to work again.

**Comment by kag0** [comment]
looks like we're back
