### ISSUE TITLE
[macosx] Action registered for keyboard shortcut is called twice

### ISSUE THREAD

**Issue by myamamoto** [AdoptOpenJDK/openjdk-support#238]
## Summary
Action registered for keyboard shortcut is called twice

Everything is explained in this bug report in the JDK.
[https://bugs.openjdk.java.net/browse/JDK-8139169](https://bugs.openjdk.java.net/browse/JDK-8139169)

I have confirmed this problem with AdoptOpenJDK8u272-b10.

What I hope is that this fix will be backported to java8 as well.
[https://github.com/AdoptOpenJDK/openjdk-jdk9u/commit/e9142e7c00cb22caa079a9b45dada6708d1089c4](https://github.com/AdoptOpenJDK/openjdk-jdk9u/commit/e9142e7c00cb22caa079a9b45dada6708d1089c4)

## Triaging info

Java version:

AdoptOpenJDK8u272-b10

What is your operating system and platform?

macos 10.15.7 & 11.0.1

How did you install Java?

Using the installer(.pkg)

Did it work before?

No.

Did you test with other Java versions?

Yes, it seems to be resolved in java9 and above.

**Comment by aahlenst** [comment]
AdoptOpenJDK is not really in a position to handle backport requests or to develop patches for OpenJDK. Biggest chance to get this addressed is to commission a company that [offers support for OpenJDK](https://adoptopenjdk.net/support.html) or upstreams their fixes like [Red Hat](https://www.redhat.com/en/services/support) or [BellSoft](https://bell-sw.com/pages/services/).

**Comment by aahlenst** [comment]
@myamamoto I got around making a patch proposing a backport. While the patch itself would be fairly trivial (the original contained tons of unnecessary whitespace changes), the problem itself wasn't considered to be serious enough to warrant a backport at this time. Furthermore, there's a viable workaround. https://mail.openjdk.java.net/pipermail/jdk8u-dev/2020-June/012002.html explains what patches get accepted.

AdoptOpenJDK only incorporates custom patches in exceptional cases, for example, to fix a compilation problem. This isn't such a case.

**Comment by myamamoto** [comment]
@aahlenst I appreciate your cooperation.
By the way, what does a viable workaround mean?
I don't know how to avoid this problem.

**Comment by aahlenst** [comment]
The workaround is to use a different shortcut. 🤷‍♂️
