### ISSUE TITLE
Installation of AdoptOpenJDK via apt on Debian Bullseye

### ISSUE THREAD

**Issue by Redfire75369** [AdoptOpenJDK/openjdk-support#239]
## Question
I am currently running WSL2 with the Debian distro.
Upon following the instructions at https://adoptopenjdk.net/installation.html#linux-pkg to install AdoptOpenJDK, `sudo apt update` failed. 
When checking https://adoptopenjdk.jfrog.io/adoptopenjdk/deb, I saw there was no `bullseye` folder under `dists/`.
Can a new folder be added there and tested to ensure that AdoptOpenJDK can be installed on the (currently) testing branch of Debian?

Note: It seems to work fine with `buster` instead of `bullseye` in the sources but more testing is required

## Context
Java version: All

Your operating system and platform:
Windows 10 1909 on x86-64
WSL2 Debian 11 (Bullseye)

**Comment by aahlenst** [comment]
> Can a new folder be added there and tested to ensure that AdoptOpenJDK can be installed on the (currently) testing branch of Debian?

Packages for Bullseye are going to be uploaded as part of the January updates that come out in the next week. Our packages are currently identical across all Debian versions, so they should work.
