### ISSUE TITLE
fatal error: no original bytecode found in sun.nio.ch.WindowsSelectorImpl.updateSelectedKeys

### ISSUE THREAD

**Issue by fengshenme** [AdoptOpenJDK/openjdk-support#24]
A fatal error has been detected by the Java Runtime Environment:
#
#  Internal Error (c:/cygwin64/tmp/openjdk-jdk11u-windows-x64-hotspot/workspace/build/src/src/hotspot/share/oops/method.cpp:1762), pid=2540, tid=19268
#  fatal error: no original bytecode found in sun.nio.ch.WindowsSelectorImpl.updateSelectedKeys(Ljava/util/function/Consumer;)I at bci 7
#
# JRE version: OpenJDK Runtime Environment (11.0.4+11) (build 11.0.4+11)
# Java VM: OpenJDK 64-Bit Server VM (11.0.4+11, mixed mode, tiered, compressed oops, g1 gc, windows-amd64)
# No core dump will be written. Minidumps are not enabled by default on client versions of Windows
#
# An error report file with more information is saved as:
# C:\Users\10159\JAVA\www1907\ssm-file-upload\hs_err_pid2540.log
#
# If you would like to submit a bug report, please visit:
#   https://github.com/AdoptOpenJDK/openjdk-build/issues

**Comment by fengshenme** [comment]
This problem occurs when you start the springboot application, but it is not very frequent
Jdk11.05 version, appears antivirus software to report remote thread injection

在启动springboot应用的时候会出现这个问题，再启动就好了，出现这个问题不频繁
jdk11.05版本，出现了杀毒软件报远程线程注入

**Comment by aahlenst** [comment]
Closing due to lack of requested feedback.
