### ISSUE TITLE
Application with Java 11 fails to install in AIX

### ISSUE THREAD

**Issue by kthaya** [AdoptOpenJDK/openjdk-support#251]
I downloaded Java 11 from https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.9.1%2B1/OpenJDK11U-jdk_ppc64_aix_hotspot_11.0.9.1_1.tar.gz, application could not be installed due to following error.
`Unpacking JRE ...`
`Error unpacking jar files. The architecture or bitness (32/64)`
`of the bundled JVM might not match your machine.`

System information:
AIX 7.2 TL4
$ prtconf
System Model: IBM,8231-E2D
Machine Serial Number: 06ADA64
Processor Type: PowerPC_POWER7
Processor Implementation Mode: POWER 7
Processor Version: PV_7_Compat
Number Of Processors: 2
Processor Clock Speed: 4228 MHz
CPU Type: 64-bit
Kernel Type: 64-bit
LPAR Info: 17 soaxp422_suspend
Memory Size: 4096 MB
Good Memory Size: 4096 MB
Platform Firmware level: AL770_126
Firmware Version: IBM,AL770_126
Console Login: enable
Auto Restart: true
Full Core: false
NX Crypto Acceleration: Capable and Enabled
In-Core Crypto Acceleration: Not Capable
Is this a known issue?

**Comment by aahlenst** [comment]
The symptoms you describe do not add up. On one hand, you say you downloaded a tarball with the JDK for AIX. On the other hand, there's this message: `Unpacking JRE ... Error unpacking jar files. The architecture or bitness (32/64) of the bundled JVM might not match your machine.`.

Tar does not know anything about JRE or bitness. It sounds like the message comes from the application you want to run, and it brings its own JRE for some reason. So your application being incompatible with PPC seems unrelated to the JDK you downloaded.

**Comment by kthaya** [comment]
We create our own JRE pack from the JDK (that will include additional tools like jmap, jinfo, etc) and then we embed the custom JRE pack in to our application. This is the way it worked fine with JDK 8 that downloaded from IBM site. But after we migrate to java 11, we got the JDK from AdoptOpenJDK (as mentioned in https://www.ibm.com/support/pages/ibm-announcement-statement-distribution-and-support-open-source-java-version-11-or-higher-ibm-aix-operating-system) and end with above mentioned error.

**Comment by aahlenst** [comment]
11.0.10 does start on AIX as [can be seen in the build log](https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-aix-ppc64-hotspot/834/consoleFull):

```
13:16:25  =JAVA VERSION OUTPUT=
13:16:25  openjdk version "11.0.10" 2021-01-19
13:16:25  OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.10+9)
13:16:25  OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.10+9, mixed mode)
13:16:25  =/JAVA VERSION OUTPUT=
```

[The majority of tests passed, too](https://github.com/AdoptOpenJDK/TSC/issues/199#issuecomment-764533010).

Can you explain what you did? Do you have the problem **without the repackaging**, too? How do you repackage? Did you really download the AIX version for PPC and not the Linux version for PPC64LE?

**Comment by kthaya** [comment]
As I mentioned in earlier thread, we create the custom JRE pack then embed that with install4j. when I run the install4j file (i.e `./install_app`) in AIX platform it end up with that particular error.
yes, the problem persist with and without repacking.
we repack using following script:

```yaml
    - wget https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.9.1%2B1/OpenJDK11U-jre_ppc64_aix_hotspot_11.0.9.1_1.tar.gz
    - tar xzvf OpenJDK11U-jdk*.tar.gz
    - tar xzvf OpenJDK11U-jre*.tar.gz
    - cd jdk-11.0.9.1+1/
    - cp bin/jps ../jdk-11.0.9.1+1-jre/bin/
    - cp bin/jinfo ../jdk-11.0.9.1+1-jre/bin/
    - cp bin/jstack ../jdk-11.0.9.1+1-jre/bin/
    - cp bin/jstat ../jdk-11.0.9.1+1-jre/bin/
    - cp bin/jmap ../jdk-11.0.9.1+1-jre/bin/
    - cd ../jdk-11.0.9.1+1-jre/
    - tar czvf ../adoptopenjdk-hotspot-aix-x64-11.0.9.tar.gz *
```
If you see the link https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.9.1%2B1/OpenJDK11U-jre_ppc64_aix_hotspot_11.0.9.1_1.tar.gz, it is PPC64 not linux. Besides, that is the only one option available from download UI as well?
![image](https://user-images.githubusercontent.com/8937792/106933266-972fd780-677d-11eb-8a4e-e46a4cd0285c.png)
our application is with AdoptOpenJDK 11.0.9 not to the very latest 11.0.10 yet.

**Comment by aahlenst** [comment]
When you download the tarball, decompress it and run `java -version', does it work? Does your application run with the downloaded JDK if you skip the install4j step?

**Comment by kthaya** [comment]
Turns out the problem is with install4j step, it built the app using Java 8 and tried to run in java 11 environment .
Thanks for the help
