### ISSUE TITLE
Internal Error: guarantee(unique_thread_id != 0) failed: unique thread id was not found

### ISSUE THREAD

**Issue by vemv** [AdoptOpenJDK/openjdk-support#253]
## Summary

I have a Java program that reproducibly crashes with:

```
# A fatal error has been detected by the Java Runtime Environment:
#
#  Internal Error (os_bsd.cpp:721), pid=85868, tid=0x0000000004068807
#  guarantee(unique_thread_id != 0) failed: unique thread id was not found
#
# JRE version: OpenJDK Runtime Environment (8.0_282-b08) (build 1.8.0_282-b08)
# Java VM: OpenJDK 64-Bit Server VM (25.282-b08 mixed mode bsd-amd64 compressed oops)
# Core dump written. Default location: /cores/core or core.85868
#
# An error report file with more information is saved as:
# /Users/vemv/iroh/hs_err_pid85868.log
``` 

## Steps to reproduce

The program is private but I probably could pass the error report file as well as the core dump. Can those inadvertently include private info? If so I'd like to anoymize them first or pass them privately if possible.

#### Java version:

```
openjdk version "1.8.0_282"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_282-b08)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.282-b08, mixed mode)
```

#### What is your operating system and platform?

macOS Catalina 10.15.7

#### How did you install Java?

I installed the absolute latest JDK8 (as of today) via homebrew cask, which is namely:

https://raw.githubusercontent.com/AdoptOpenJDK/homebrew-openjdk/acb102fa1a03a7d3e24b363bd864e6cc1f4b7f0f/Casks/adoptopenjdk8.rb

**NOTE:** I intentionally use JDK8, as it's a very stable release, particularly as a user of the Clojure language which is sensitive to classloader, module, etc nuances.

##### Did it work before?

I think so but I can't recall which exact JDK8 build I was using back then

#### Did you test with other Java versions?

I tried with an older build of adoptopenjdk8, to no avail.

**Comment by aahlenst** [comment]
@vemv Can you please also share `/Users/vemv/iroh/hs_err_pid85868.log`?

**Comment by vemv** [comment]
Sure! Here it goes:

https://gist.github.com/vemv/65ac02a893339527a2e9e8f768f1f069

**Comment by aahlenst** [comment]
Does it always happen?

Can you check whether it happens with https://bell-sw.com/pages/downloads/#/java-8-lts or https://www.azul.com/downloads/zulu-community/?version=java-8-lts&os=macos&architecture=x86-64-bit&package=jdk?

**Comment by vemv** [comment]
It also happens with Oracle JDK8 latest, tried just now. Does that attempt suffice or should I also run one of the mentioned jdks?

**Comment by vemv** [comment]
> Does it always happen?

(yes)

**Comment by aahlenst** [comment]
If it fails with Oracle JDK 8, we're good. No further tests needed. Fastest way to get this reported: Fill in the form on https://bugreport.java.com/bugreport/. Be prepared that they ask for a reproducer.

**Comment by vemv** [comment]
The code that ultimately causes my issue is https://github.com/real-logic/aeron which is a hybrid Java/C++ project. In the history of its issue tracker one can find various reports of JVM crashes.

I see that eventually they get fixed - maybe I just experienced a new kind of bug.

Probably crashing the JVM is less of an oddity in a partially-native project, so I don't think anymore that I'm experiencing something worth reporting in https://bugreport.java.com/bugreport/ . 

If you share this assessment please close my issue.

**Comment by aahlenst** [comment]
> Probably crashing the JVM is less of an oddity in a partially-native project

I see that all the time. Majority of problems reported here is caused by 3rd party native code.
