### ISSUE TITLE
JVM Crashing intermittently with below error

### ISSUE THREAD

**Issue by ramrei** [AdoptOpenJDK/openjdk-support#26]
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f58a0064884, pid=1, tid=3687
#
# JRE version: OpenJDK Runtime Environment (11.0.3+7) (build 11.0.3+7)
# Java VM: OpenJDK 64-Bit Server VM (11.0.3+7, mixed mode, tiered, compressed oops, g1 gc, linux-amd64)
# Problematic frame:
# C  [libc.so.6+0x36884]
[timeout occurred during error reporting in step "printing problematic frame"] after 30 s.
# Core dump will be written. Default location: Core dumps may be processed with "/opt/dynatrace/oneagent/agent/rdp -p %p -P %P -e %e -s %s" (or dumping to /app/core.1)
#
# If you would like to submit a bug report, please visit:
#   https://github.com/AdoptOpenJDK/openjdk-build/issues
#

---------------  S U M M A R Y ------------

Command Line: -Xms2g -Xmx2g -XX:+UseG1GC -XX:+UseStringDeduplication -Xverify:none -Djava.net.preferIPv4Stack=true -Dcom.sun.jndi.ldap.connect.pool.timeout=3000 -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:7777 -Xlog:gc

Host:
[timeout occurred during error reporting in step "printing summary machine and OS info"] after 30 s.

------ Timeout during error reporting after 120 s. ------

**Comment by sxa555** [comment]
Brilliant - thanks for the update! I'll close it now
