### ISSUE TITLE
Unableto play Minecraft with MultiMC

### ISSUE THREAD

**Issue by Monniasza** [AdoptOpenJDK/openjdk-support#262]
**What are you trying to do?**
	Play Minecraft with Java 15
**Expected behaviour:**
	Minecraft starts up correctly
**Observed behaviour:**
	Minecraft does not start up or crashes immediately
	Log for Minecraft 1.7.10: [log](https://paste.ee/p/VomMz)
**Any other comments:**
	My game, [MultiMachineBuilder](https://github.com/MultiMachineBuilder/MultiMachineBuilder) works correctly, because it doesn't use JRE-specific transformation behaviour
	Re-created for:
	* Minecraft Forge 1.7.10
	* Minecraft Forge 1.12.2
	* Minecraft Forge 1.16.3
	* Fabric 1.16.4
	Also reported on https://github.com/MultiMC/MultiMC5/issues/3609
**Java version**
	AdoptOpenJDK HotSpot JRE 15.0.1.9

**Comment by aahlenst** [comment]
What makes you think that the JDK is to blame?

**Comment by Monniasza** [comment]
The Minecraft works correctly with Oracle JRE 8u202, but does not work wit AdoptOpenJDK

**Comment by aahlenst** [comment]
If you'd try AdoptOpenJDK 8u202, it would probably work, too. A lot changed between 8u202 and 15. You might have more success with the latest version of the 8u line, 8u282: https://adoptopenjdk.net/?variant=openjdk8&jvmVariant=hotspot.

**Comment by Monniasza** [comment]
All Of Fabric 3 log (using Fabric): [log](https://paste.ee/p/82WP0)
All the Mods 6 log (using Minecraft Forge) : [log](https://paste.ee/p/73mMx)
Both modpacks have crashed with JRE 15

**Comment by aahlenst** [comment]
It wants to use Nashorn. Nashorn was removed with 15: https://blog.adoptopenjdk.net/2020/09/adoptopenjdk-15-available/.
