### ISSUE TITLE
 EXCEPTION_ACCESS_VIOLATION

### ISSUE THREAD

**Issue by veiba01** [AdoptOpenJDK/openjdk-support#264]
Execute a program that uses JRE

completion

breakes directly

have a look at the attached logfile
[hs_err_pid8628.log](https://github.com/AdoptOpenJDK/openjdk-build/files/6009435/hs_err_pid8628.log)

**Comment by karianna** [comment]
@veiba01 This needs a lot more information - what version of Java? please print out java --version.

What program are you running?

Are you able to produce a short, simple reporducer?

**Comment by aahlenst** [comment]
This a problem in 3rd party native code. It crashes in `ucrtbase.dll`, which is part of the Windows 10 SDK. I assume that the code above feeds it invalid pointers:

```
j  com.ca.careg.CoraJava.JNIGetLastError(J[Ljava/lang/String;I)J+0
j  com.ca.careg.CoraJava.getLastError(JI)Ljava/lang/String;+26
j  com.ca.careg.CoraJava.init(ILjava/lang/String;II)J+56
```

**Comment by karianna** [comment]
@veiba01 please try with our 11.0.10+9 builds as this crash is from 11.0.3

**Comment by veiba01** [comment]
Hi Team,

it’s a broadcom utility to cleanup a database. As in the error message is mentioned to send the logfile to GitHub for help, I did send it to you.
I tested it in 2 environments, Win Server 2019, SQL Server 2019 and Win Server 2016, SQL Server 2016 with the same result.
The question is now, is it a general java problem which has to be solved independently of the software using it.
Is it a windows problem or perhaps a problem related to the SQL Server.

Regards
   Baerbel Veit

Mit freundlichen Grüßen / Best Regards
Bärbel Veit

MAXXYS AG | Am Helgenhaus 15-17 | 35510 Butzbach

phone    +49 6441 21004 0
fax          +49 6441 21004 20
mobile   +49 172 5364734
mail        baerbel.veit@maxxys.de<mailto:baerbel.veit@maxxys.de>
web        www.maxxys.de<http://www.maxxys.de/>


HRB2551 Wetzlar | Ust. ID-Nr. DE 221 2907 39
Vorstand: Bernhard Bock | Aufsichtsrat: Walter Biesel (Vorsitzender)

[axxys]
Der unabhängige Software Systemintegrator

Diese E-Mail enthält vertrauliche und/oder rechtlich geschützte Informationen. Wenn Sie nicht der richtige Adressat sind oder diese E-Mail irrtümlich erhalten haben, informieren Sie bitte sofort den Absender und vernichten Sie diese Mail.
Das unerlaubte Kopieren sowie die unbefugte Weitergabe dieser Mail ist nicht gestattet.
This e-mail may contain confidential and/or privileged information. If you are not the intended recipient (or have received this e-mail in error) please notify the sender immediately and destroy this e-mail. Any unauthorised copying, disclosure or distribution of the material in this e-mail is strictly forbidden.

Von: Andreas Ahlenstorf <notifications@github.com>
Gesendet: Freitag, 19. Februar 2021 12:08
An: AdoptOpenJDK/openjdk-support <openjdk-support@noreply.github.com>
Cc: Bärbel Veit <baerbel.veit@maxxys.de>; Mention <mention@noreply.github.com>
Betreff: Re: [AdoptOpenJDK/openjdk-support] EXCEPTION_ACCESS_VIOLATION (#264)


This a problem in 3rd party native code. It crashes in ucrtbase.dll, which is part of the Windows 10 SDK. I assume that the code above feeds it invalid pointers:

j  com.ca.careg.CoraJava.JNIGetLastError(J[Ljava/lang/String;I)J+0

j  com.ca.careg.CoraJava.getLastError(JI)Ljava/lang/String;+26

j  com.ca.careg.CoraJava.init(ILjava/lang/String;II)J+56

**Comment by iFireKin** [comment]
Im not much as a coder not much at all so how would i fix this?

**Comment by aahlenst** [comment]
Does Java come as part if the tool or did you install it separately? If separately, download from https://adoptopenjdk.net/releases.html?variant=openjdk11&jvmVariant=hotspot, install and try again. If Java came with that Broadcom utility, see if there's a newer version. Otherwise complain to Broadcom.

**Comment by veiba01** [comment]
Thank you for your support, also the latest java-version did not work, I reported the problem to Broadcom and now they have to solve the problem.


Mit freundlichen Grüßen / Best Regards
Bärbel Veit

MAXXYS AG | Am Helgenhaus 15-17 | 35510 Butzbach

phone    +49 6441 21004 0
fax          +49 6441 21004 20
mobile   +49 172 5364734
mail        baerbel.veit@maxxys.de<mailto:baerbel.veit@maxxys.de>
web        www.maxxys.de<http://www.maxxys.de/>


HRB2551 Wetzlar | Ust. ID-Nr. DE 221 2907 39
Vorstand: Bernhard Bock | Aufsichtsrat: Walter Biesel (Vorsitzender)

[axxys]
Der unabhängige Software Systemintegrator

Diese E-Mail enthält vertrauliche und/oder rechtlich geschützte Informationen. Wenn Sie nicht der richtige Adressat sind oder diese E-Mail irrtümlich erhalten haben, informieren Sie bitte sofort den Absender und vernichten Sie diese Mail.
Das unerlaubte Kopieren sowie die unbefugte Weitergabe dieser Mail ist nicht gestattet.
This e-mail may contain confidential and/or privileged information. If you are not the intended recipient (or have received this e-mail in error) please notify the sender immediately and destroy this e-mail. Any unauthorised copying, disclosure or distribution of the material in this e-mail is strictly forbidden.

Von: Andreas Ahlenstorf <notifications@github.com>
Gesendet: Sonntag, 21. Februar 2021 21:28
An: AdoptOpenJDK/openjdk-support <openjdk-support@noreply.github.com>
Cc: Bärbel Veit <baerbel.veit@maxxys.de>; Mention <mention@noreply.github.com>
Betreff: Re: [AdoptOpenJDK/openjdk-support] EXCEPTION_ACCESS_VIOLATION (#264)


Does Java come as part if the tool or did you install it separately? If separately, download from https://adoptopenjdk.net/releases.html?variant=openjdk11&jvmVariant=hotspot, install and try again. If Java came with that Broadcom utility, see if there's a newer version. Otherwise complain to Broadcom.
