### ISSUE TITLE
JVM crash on ARM64

### ISSUE THREAD

**Issue by markathomas** [AdoptOpenJDK/openjdk-support#266]
## Summary

JVM inside Docker container is crashing in the C1 Compiler Thread after around 5-10 of running on AArch64 Amazon Linux 2 host 

## Steps to reproduce

Not sure what to provide here.  This happens on one of three containers using the same JVM version, same Spring Boot version, same everything only the class name in current compilation ask is only used on container that is crashing.  I'd be happy to provide this class privately.  Let me know what else I can provide

## Expected results

JVM does not crash

## Actual results

Hard crash

## Triaging info

Java version:

openjdk version "11.0.10" 2021-01-19
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.10+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.10+9, mixed mode)

What is your operating system and platform?

Container is based on arm64v8/adoptopenjdk:11-jdk-hotspot

Host: AArch64 Amazon Linux 2 - 4.14.219-161.340.amzn2.aarch64 #1 SMP Thu Feb 4 05:54:27 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux

How did you install Java?

arm64v8/adoptopenjdk:11-jdk-hotspot container comes with it

Did it work before?

Switched to Arm64

Did you test with other Java versions?

yes, java 11.0.10 openj9 works fine; only hotspot having issues
[hs_err_pid7.log](https://github.com/AdoptOpenJDK/openjdk-support/files/6046380/hs_err_pid7.log)
[replay_pid7.log](https://github.com/AdoptOpenJDK/openjdk-support/files/6046381/replay_pid7.log)

**Comment by markathomas** [comment]
No rush on this, I'm using the OpenJ9 build currently.  This was more an FYI ticket.

**Comment by aahlenst** [comment]
Gets fix in April: https://bugs.openjdk.java.net/browse/JDK-8247766. Nightly builds should have it.

Might need a backport to 8.

**Comment by markathomas** [comment]
Good enough for me.
