### ISSUE TITLE
cacerts keystore certificates cause issues because of the changed format

### ISSUE THREAD

**Issue by valjo94** [AdoptOpenJDK/openjdk-support#270]
## Summary
The new Mozilla Root CA certificates, contained in the 11.0.10+9 build of AdoptOpenJDK JRE under lib/security/cacerts keystore are put under wrong aliases (almost identical as the subject), which causes issues with keystore management, because of the changed format and length - with aliases being like "c=pl,o=unizeto technologies s.a.,ou=certum certification authority,cn=certum trusted network ca 2" insted of "certumca [jdk]" like it was before the change.

## Steps to reproduce
List certificates in keystore like 
`keytool -list -v -keystore lib/security/cacerts  | grep Alias`

## Expected results
Certificate to be stored in the keystore with real aliases, instead of the subject of the certificate.

## Actual results
Certificate is stored in the keystore with its subject placed as a key(alias) to get to the given certificate data.

## Triaging info

Java version:
openjdk version "11.0.10" 2021-01-19
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.10+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.10+9, mixed mode)

What is your operating system and platform?
This issue is existing on every OS that we support - which are RHEL, AIX, Windows.

How did you install Java?
I used the binary archives per given OS & architecture.

Did it work before?
The problem is non existent before JRE 11.0.10+9

Did you test with other Java versions?
Yes, previous versions of the JRE have the old Root CA vendor, and have proper aliases for the certificates.

**Comment by aahlenst** [comment]
> which causes issues with keystore management

Please elaborate.

> Certificate to be stored in the keystore with real aliases, instead of the subject of the certificate.

Why?

Generally, looking at the thumbprint is the most reliable method.

**Comment by aahlenst** [comment]
Closing due to lack of requested feedback. We're happy to reopen the issue if feedback is provided by the OP (or anybody else) at a later date.
