### ISSUE TITLE
Running the jdk8u-282 binaries in an app for mac fails

### ISSUE THREAD

**Issue by k7295** [AdoptOpenJDK/openjdk-support#273]
After downloading these binaries 

I am using these binaries [jre_x64_mac_hotspot_8u282b08.tar.gz](https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u282-b08/OpenJDK8U-jre_x64_mac_hotspot_8u282b08.tar.gz) in an app for mac (Catalina)
and get this issue:
![Screen Shot 2021-03-03 at 15 10 52](https://user-images.githubusercontent.com/15851474/109872903-a7c75680-7c32-11eb-96ba-e91d43e4ff5d.png) 
Could anyone know how to fix it?

**Comment by aahlenst** [comment]
What are you doing to get this problem?

**Comment by k7295** [comment]
I am creating a connection-manager that launches a new jvm with those binaries but after create that I got that issue

**Comment by aahlenst** [comment]
No, that wasn't my question. You download the tarball, then you unpack it, what then? Step by step. The error message indicates an entitlement problem (Java has a JIT and needs appropriate entitlements). See https://stackoverflow.com/questions/52911791/hardened-runtime-for-java-and-mojave for what's required (more or less).

**Comment by k7295** [comment]
yes, I know that is something related to the entitlements but this is all the codesign output, and it seems to have the JIT entitlement 
````
Identifier=net.java.openjdk.cmd
Format=Mach-O thin (x86_64)
CodeDirectory v=20500 size=832 flags=0x10000(runtime) hashes=17+5 location=embedded
VersionPlatform=1
VersionMin=657664
VersionSDK=658944
Hash type=sha256 size=32
CandidateCDHash sha1=1ba6f00b54113b29ef25e67cb00a80bb8fa80bb3
CandidateCDHashFull sha1=1ba6f00b54113b29ef25e67cb00a80bb8fa80bb3
CandidateCDHash sha256=996250cf70b51e62fe6b39dfde13dbb2891d3dbf
CandidateCDHashFull sha256=996250cf70b51e62fe6b39dfde13dbb2891d3dbffdc241624908aaf5b12d1d4e
Hash choices=sha1,sha256
CMSDigest=df0ff56334b6bf625b600f1ff279273b3061c7c3aaee28de5fe26ca57bf126f6
CMSDigestType=2
Page size=4096
    -5=633e0f689a63307676d30275f0a474e0962b649e14ee91379c5dae3d18b49578
    -4=0000000000000000000000000000000000000000000000000000000000000000
    -3=0000000000000000000000000000000000000000000000000000000000000000
    -2=5cf9409838ccbabef2a0ebdb87f55ac1f0c7860844793262f70f50d4cb57cf17
CDHash=996250cf70b51e62fe6b39dfde13dbb2891d3dbf
Signature size=9038
Authority=Developer ID Application: London Jamocha Community CIC (VDX7B37674)
Authority=Developer ID Certification Authority
Authority=Apple Root CA
Timestamp=Jan 20, 2021 at 06:25:48
Info.plist entries=4
TeamIdentifier=VDX7B37674
Runtime Version=10.14.0
Sealed Resources=none
Internal requirements count=1 size=180
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>com.apple.security.cs.allow-jit</key>
    <true/>
    <key>com.apple.security.cs.allow-unsigned-executable-memory</key>
    <true/>
    <key>com.apple.security.cs.disable-library-validation</key>
    <true/>
    <key>com.apple.security.cs.allow-dyld-environment-variables</key>
    <true/>
    <key>com.apple.security.cs.debugger</key>
    <true/>
</dict>
</plist>%
```

**Comment by k7295** [comment]
If I am right the binaries have the correct entitlement,  also when I do `java -version` it works, it is only when I launch the java with my app. 
First, check for a valid libjli, then launch the jvm with those binaries, and  immediately after that, get that issue

**Comment by aahlenst** [comment]
Your looking at the JDK in isolation, not at your app. If you want to bundle the JDK, you have to treat it as part of your app. So your app needs those entitlements and you need to resign the JDK as part of your app. You really have to follow what @tresf documented so nicely on StackOverflow: https://stackoverflow.com/a/53528020/759042 (note to myself: Add that to our upcoming user manual).

But I have to add: I never did that myself. I'm only relaying what our experts for notarization/code signing are doing.

**Comment by tresf** [comment]
Another good resource, albeit a bit proprietary: https://bell-sw.com/announcements/2020/06/10/How-to-Notarize-a-Mac-Application-with-Liberica-JDK/

**Comment by k7295** [comment]
> Your looking at the JDK in isolation, not at your app. If you want to bundle the JDK, you have to treat it as part of your app. So your app needs those entitlements and you need to resign the JDK as part of your app. You really have to follow what @tresf documented so nicely on StackOverflow: https://stackoverflow.com/a/53528020/759042 (note to myself: Add that to our upcoming user manual).
> 
> But I have to add: I never did that myself. I'm only relaying what our experts for notarization/code signing are doing.

using the same entitlements in my app solves my issue with the openjdk!! thanks so much for your help
