### ISSUE TITLE
DateTimeFormatter parse exception thrown with valid dates

### ISSUE THREAD

**Issue by nsaftarli** [AdoptOpenJDK/openjdk-support#275]
## Summary

Using the datetime format of "ddMMMyyyy" throws an exception for almost all month values but May. 

## Steps to reproduce

```
import java.time.format.DateTimeFormatter;


public class Test {
    public static void main(String[] args) {
        DateTimeFormatter dateTimeFormatter = DateTimeFormatter.ofPattern("ddMMMyyyy");

        System.out.println(dateTimeFormatter.parse("19May1989"));
        System.out.println(dateTimeFormatter.parse("19Mar1989"));
    }
}
```

## Expected results
{},ISO resolved to 1989-05-19
{},ISO resolved to 1989-03-19

## Actual results

{},ISO resolved to 1989-05-19
Exception in thread "main" java.time.format.DateTimeParseException: Text '19Mar1989' could not be parsed at index 2
	at java.base/java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:2046)
	at java.base/java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1874)
	at Test.main(Test.java:9)

## Triaging info

Java version:

openjdk version "11.0.10" 2021-01-19
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.10+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.10+9, mixed mode)

What is your operating system and platform?

MacOS 10.15.7

How did you install Java?

SDKman

Did it work before?

I am not sure but other members of my team have it working with 11.0.3

Did you test with other Java versions?

Tried 11.0.9, 11.0.10, and 1.8. Works with 1.8 and 11.0.3.

**Comment by nsaftarli** [comment]
Update: Looks like it's an issue with the Canadian locale. If your locale is picked up as "en_US", the code above will perform fine. With "en_CA" it will break.

**Comment by aahlenst** [comment]
We had that before: https://bugs.openjdk.java.net/browse/JDK-8250626. If you can do the research and argue (Javadoc, comparisons with other platforms) why the resolution is wrong, please do so. I'll then reopen and try to find someone who posts your argument to JBS.

**Comment by nsaftarli** [comment]
@aahlenst while specifying Locale explicitly does solve the issue as a workaround, there's actually a small bug in the representation of month abbreviations. Take a look at the following from FormatData_en_CA:

```
        final String[] metaValue_MonthAbbreviations = new String[] {
               "Jan.",
               "Feb.",
               "Mar.",
               "Apr.",
               "May",
               "Jun.",
               "Jul.",
               "Aug.",
               "Sep.",
               "Oct.",
               "Nov.",
               "Dec.",
               "",
            };
```

as you can see the abbreviations for all the months are appended with a period whereas May is not. This causes the code to fail. As a follow up to the above steps to reproduce, if you try this, it will work:

`
import java.time.format.DateTimeFormatter;


public class Test {
    public static void main(String[] args) {
        DateTimeFormatter dateTimeFormatter = DateTimeFormatter.ofPattern("ddMMMyyyy");

        System.out.println(dateTimeFormatter.parse("19May1989"));
        System.out.println(dateTimeFormatter.parse("19Mar.1989"));
    }
}`

So month abbreviation is inconsistent when the locale is "en_CA", which causes problems when attempting to parse dates.

**Comment by aahlenst** [comment]
Question is what the Javadoc has to say on this, whether there are regression tests that confirm that this behaviour is correct, whether there are OS differences, ... You can also try to mail https://mail.openjdk.java.net/mailman/listinfo/core-libs-dev and ask for clarification on the behaviour of DateTimeFormatter and its locale sensitivity.
