### ISSUE TITLE
Shenandoah GC not available in 11.0.10

### ISSUE THREAD

**Issue by Mcfloy** [AdoptOpenJDK/openjdk-support#280]
**What are you trying to do?**
I'm trying to use the Shenandoah GC in the latest OpenJDK docker files, but the latest (11.0.10) doesn't seem to recognize it.

**Expected behaviour:**
When using the option `-XX:+UseShenandoahGC ` it should use the Shenandoah GC.
**Observed behaviour:**
When using the option `-XX:+UseShenandoahGC ` we get an error from the compiler saying that ShenandoahGC is not recognized.

**Any other comments:**
Command used to test the behaviour:
```
docker run -it  openjdk:11.0.10-jre-buster

root@313191e57915:/# java --version
openjdk 11.0.10 2021-01-19
OpenJDK Runtime Environment 18.9 (build 11.0.10+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.10+9, mixed mode, sharing)
root@313191e57915:/# java -XX:+UseShenandoahGC -Xlog:gc -version
Unrecognized VM option 'UseShenandoahGC'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

I mark it as a bug as we should have the new GC available in docker (or at least with a new name to retrieve it)

**Comment by Mcfloy** [comment]
Oh okay my bad, indeed I will close this ticket and mention it in the issue provided by jerboaa.

Thanks !

**Comment by aahlenst** [comment]
@Mcfloy If you want Shenandoah, you should pick a distribution that has it. It's basically a "feature" of OpenJDK builds provided by Oracle not to have it. AdoptOpenJDK isn't the only one with Shenandoah enabled. Same with CentOS, RHEL, Fedora.
