### ISSUE TITLE
Unable to Load jar file during plugin startup

### ISSUE THREAD

**Issue by raghuhollap** [AdoptOpenJDK/openjdk-support#283]
I am trying to load a jar file during plugin startup. But unable to load it with JDK 12 or later version.
below is the code snippet :
-------------------------------------CODE---------------------------------------------------
URLClassLoader urlSysLoader = new URLClassLoader(new URL[] {url}, sysLoader);
Method method = sysClass.getDeclaredMethod("addURL", parameters);
/**
* The addURL() appends the specified URL to the list of URLs to search for
* classes and resources. and since this Method is Protected and we are not inheriting
*  i'm forced to make it visible.
 */	
method.setAccessible(true);
// Invoke addURL method with jar URL to add the classes to URL ClassLoader
method.invoke(urlSysLoader, new Object[] { url });
Field scl = ClassLoader.class.getDeclaredField("scl");
scl.setAccessible(true);
 // Replace the static scl (System Class Loader for running instance) with 
 // newly created URL ClassLoader (system class loader + jar files loaded)
scl.set(null, urlSysLoader);
-----------------------------------------CODE----------------------------------------------

Getting below error :
----------------------------------------ERROR---------------------------------------------------------------------------------
java.lang.NoSuchFieldException: scl
	at java.base/java.lang.Class.getDeclaredField(Class.java:2569)
	at com.xxxxxx.tde.core.characterset.OS2200CharSetPlugin.loadCharSetLib(OS2200CharSetPlugin.java:160)
	at com.xxxxxx.tde.core.characterset.OS2200CharSetPlugin$1.run(OS2200CharSetPlugin.java:66)
----------------------------------------ERROR---------------------------------------------------------------------------------

The above code was working till JDK 11  version.

Please let me know any suggestion or any other alternative approach to achieve the same.

Thanks and Regards,
Raghu

**Comment by karianna** [comment]
Is this with an AdoptOpenJDK binary?  Have you tried with the latest 16+36 GA build?

**Comment by raghuhollap** [comment]
@karianna , Yes I tried using latest 16+36 GA build, facing same problem.

**Comment by aahlenst** [comment]
@raghuhollap You're calling via reflection into JDK internals. Why do you assume that this is supported in any way? There's also no guarantee that the property is named identically on all JVMs. I recommend to ask on StackOverflow for programming advice. We cannot help with that.

**Comment by raghuhollap** [comment]
The above code was working till JDK 11. since JDK 12 and later this code is not working.

**Comment by aahlenst** [comment]
> The above code was working till JDK 11. since JDK 12 and later this code is not working.

I got that. But again, you're using reflection to directly access a **private** variable in the JDK:

```
Field scl = ClassLoader.class.getDeclaredField("scl");
scl.setAccessible(true);
```

It's called private for a reason. This is not supported and where the code fails. So either find a way to do what you're doing using **public** APIs or try to convince the JDK development team to enhance the API. Relying on private APIs can be nice as long as it works, but ultimately there's no guarantee that it will continue to work. This has happened to you.
