### ISSUE TITLE
Crash on opening since 3/29

### ISSUE THREAD

**Issue by Faderr** [AdoptOpenJDK/openjdk-support#288]
Runelite will load (plugins, etc.) succesfully but as soon as the main 'frame' opens, it crashes within moments.

[jvm_crash_pid_17652.log](https://github.com/AdoptOpenJDK/openjdk-support/files/6229999/jvm_crash_pid_17652.log)

**Comment by aahlenst** [comment]
Hard to say what exactly goes wrong, but it's in 3rd party code (jogamp.nativewindow.windows.GDI.DescribePixelFormat1) that tries to access memory segments it should not. Reasons can be manifold. Best you can do is update Runelite and, if the problem persists, report it to Runelite.
