### ISSUE TITLE
JVM consuming more Virtual and Resident memory

### ISSUE THREAD

**Issue by morthasrinivas** [AdoptOpenJDK/openjdk-support#37]
**Platform:**
RHEL7
**Architecture:**
X86 64-bit

Please describe the issue that you are having with our binaries and if possible how to recreate it.

I am running a light-weight application - SCP(AdoptOpenJDK 8) with memory limit of 256meg( -Xmx256m) but the virtual and resident memory doesn't honour the memory limit.  Virtual memory took 19G and Resident 370meg. 

We took the heapdump(JMap) but the heap has 18Meg live allocations. 
It looks to me a Java bug.  
![image](https://user-images.githubusercontent.com/28856763/70925989-47122500-2052-11ea-8ff2-5a31fd1d81b7.png)

**Comment by grzesuav** [comment]
@morthasrinivas what are you expectations ? 

Xmx limist just heap memory, java process has also off-heap memory usage.

Can you run your app with 
`java -XX:+UnlockDiagnosticVMOptions -XX:+PrintCommandLineFlags`
and show the output from flags printed there ?

**Comment by morthasrinivas** [comment]
After setting the below options, the memory footprint is reduced and never crossed 256meg.

-XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=25 -XX:MetaspaceSize=64m -Xmx256M

**Comment by grzesuav** [comment]
Can you check what `-XX:+UnlockDiagnosticVMOptions -XX:+PrintCommandLineFlags` prints applied along flags your are setting ?

**Comment by aahlenst** [comment]
Closing due to lack of requested feedback.
