### ISSUE TITLE
Switching Gtk themes deadlocks UI

### ISSUE THREAD

**Issue by tresf** [AdoptOpenJDK/openjdk-support#4]
**Description:**
Switching themes on Ubuntu 18.04 using Gnome Tweak Utility deadlocks the Swing UI if the Gtk theme is being used.

> <img src="https://user-images.githubusercontent.com/6345473/80511097-a14cbc00-8949-11ea-9d16-b0d7461311f2.gif" width="250px"/>

**Platform:**
Linux (Ubuntu 18.04)
AdoptOpenJDK 11.0.7

**Architecture:**
x86_64

**Steps:**

1. Install the `gnome-tweak-tool`

   ```bash
   sudo add-apt-repository universe
   sudo apt install gnome-tweak-tool
   ```

2. Run the following code snippet

   ```java
   import javax.swing.*;
   
   public class ThemeCrash {
       public static void main(String ... args) {
           SwingUtilities.invokeLater(() -> {
               try {
                   UIManager.setLookAndFeel("com.sun.java.swing.plaf.gtk.GTKLookAndFeel");
                   JOptionPane.showMessageDialog(null, "test");
               } catch (Throwable ignore) { }
           });
       }
   }
   ```

3. Observe that the "Ok" button can be clicked.
4. Launch Gnome Tweak Tool.  From the "Appearance" tab, change the theme from "Adwaita (default)" to "Adwaita-dark"
5. Observe that the "Ok" button can no longer be clicked.

**Comment by aahlenst** [comment]
@tresf Could you please verify whether this is still a problem with 11.0.7? If it is, please check with https://adoptopenjdk.net/upstream.html, too. In that case, we might be able to report that to OpenJDK.

**Comment by tresf** [comment]
>  @tresf Could you please verify whether this is still a problem with 11.0.7

The bug still occurs with 11.0.7:

```
openjdk version "11.0.7" 2020-04-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.7+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.7+10, mixed mode)
```

The bug still occurs with 11.0.7 from OpenJDK:
```
openjdk version "11.0.7" 2020-04-14
OpenJDK Runtime Environment 18.9 (build 11.0.7+10)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.7+10, mixed mode)
```

**Comment by aahlenst** [comment]
@jerboaa We have [steps to reproduce](https://github.com/AdoptOpenJDK/openjdk-support/issues/4#issue-533935310) and [confirmation it is still a problem with 11.0.7](https://github.com/AdoptOpenJDK/openjdk-support/issues/4#issuecomment-620156971). Ready for OpenJDK?

**Comment by jerboaa** [comment]
@tresf Is this an Ubuntu only problem or Gnome generically? Have you tried?

**Comment by tresf** [comment]
Please excuses my candor, but I'll growing a bit frustrated with the burden of proof required for convincing the team that this bug exists.

**Comment by aahlenst** [comment]
@tresf Sorry, please bear with us. One problem is that the bug lingered for so long and I don't have the necessary machines around for testing it myself (OpenJDK might have fixed that in the meantime). The other challenge is the high bar that we have to meet for reporting to OpenJDK.

A few weeks ago, I've started to work with reporters on improving the bugs quickly so that they become ready to report in a reasonable timeframe. But I have yet to work through the backlog.

**Comment by jerboaa** [comment]
@tresf I've tried this on my Fedora 30 switching back and forth from Adwaita to Adwaita-dark and don't seem to be able to reproduce this. Seems specific to Ubuntu perhaps?

**Comment by tresf** [comment]
@aahlenst thanks for the explanation however please also understand that besides Martijn's response in August of 2019, I haven't perceived much in regards to effort, leaving a feeling similar to "[Have you turned the computer off and back on again](https://i.giphy.com/media/DUtVdGeIU8lmo/giphy.webp)". 🙄 🙂 

> @tresf I've tried this on my Fedora 30 switching back and forth from Adwaita to Adwaita-dark and don't seem to be able to reproduce this. Seems specific to Ubuntu perhaps?

@jerboaa I've updated the original example to reproduce on Wayland.  The bug exists, but the L&F must be forced.  OpenJDK uses a [deprecated flag for detecting the GDM called `GNOME_DESKTOP_SESSION_ID` with a value of `this-is-deprecated`](https://stackoverflow.com/q/40603418/3196753).  Apparently Wayland didn't feel like carrying this over. 🤣I assume someone's already reported the lack of GTK detection in Wayland, if not, I'd happily file that bug as well.

Here's an example which works on Fedora Core Workstation 32 with AdoptOpenJDK 11.0.7:


```diff
import javax.swing.*;
   
public class ThemeCrash {
    public static void main(String ... args) {
        SwingUtilities.invokeLater(() -> {
            try {
-               UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
+               UIManager.setLookAndFeel("com.sun.java.swing.plaf.gtk.GTKLookAndFeel");
                JOptionPane.showMessageDialog(null, "test");
            } catch (Throwable ignore) { }
        });
    }
}
```

**Comment by tresf** [comment]
Preview attached to [original bug report](https://github.com/AdoptOpenJDK/openjdk-support/issues/4#issue-533935310).  Notice the theme is visibly different from when using Swing's default L&F.

**Comment by tresf** [comment]
> I assume someone's already reported the lack of GTK detection in Wayland, if not, I'd happily file that bug as well.

I couldn't find one, filed #94.

**Comment by jerboaa** [comment]
Thanks @tresf. Reported upstream as:
https://bugs.openjdk.java.net/browse/JDK-8244088

**Comment by tresf** [comment]
@jerboaa @aahlenst thanks kindly.

**Comment by tresf** [comment]
Another duplicate, but specific to Java 8 and marked as resolved: https://bugs.openjdk.java.net/browse/JDK-8219072

**Comment by aahlenst** [comment]
@tresf I think what was delivered there were the release notes, not a fix for the underlying issue.

**Comment by tresf** [comment]
Update: Our JDK vendor has patched this so a subsequent patch should land shortly on openjdk.

I'm not aware of the details as they were not provided, but an OpenJDK11 build with this working on Ubuntu 18.04 and 20.04 switching between dark and light themes was tested and working.  More details to follow.

**Comment by tresf** [comment]
The patch has been submitted, awaiting openjdk approval: https://mail.openjdk.java.net/pipermail/swing-dev/2020-August/010694.html

**Comment by tresf** [comment]
Patched upstream via https://github.com/openjdk/jdk/pull/932, awaiting JDK11 backport.

**Comment by aahlenst** [comment]
Backported to 11.0.11: https://bugs.openjdk.java.net/browse/JDK-8244088.
