### ISSUE TITLE
What is the support plan of AdoptOpenJDK 8 on Windows 2019?

### ISSUE THREAD

**Issue by puneet-jain2020** [AdoptOpenJDK/openjdk-support#40]
Is the AdoptOpenJDK 8 supported on Windows 2019.

**Comment by puneet-jain2020** [comment]
Any update on this issue please.

**Comment by aahlenst** [comment]
Windows Server 2008 R2 or later are supported.

**Comment by puneet-jain2020** [comment]
Thanks for the confirmation.
