### ISSUE TITLE
Java based server doesn't accept connection via https with x86_64-alpine-jre-11.0.5_10

### ISSUE THREAD

**Issue by iritome** [AdoptOpenJDK/openjdk-support#41]
* **Platform and architecture (e.g. Linux/x64**:
x64, Window 10 Enterprise 

* **Java version (from "java --version") e.g. 1.8.0_181, 11.0.4+11 etc.**:
x86_64-alpine-jre-11.0.5_10
* **Variant e.g. HotSpot or OpenJ9**:
HotSpot
* **Have you tested it with other vendors' java**:
No
* **Steps to reproduce**:
1) We have a java based server running in a docker container
2) We have a java based client application that connects with the server from 1) via http or https. For https we use a self generated certificate, which is valid. The client application is compiled with 
x86_64-alpine-jre-11.0.5_10.
3) When using x86_64-alpine-jre-11.0.5_10 for the server, the client is not able to connect via https with the server
4) The connection is successful when using x86_64-alpine-jre-11.0.4_11 or version 3_7  on server

* **Error messsage and/or description of what is not working as expected**:
Find attached the stack trace from server when the client connects via https.
[ServerSigningExceptionDocker.txt](https://github.com/AdoptOpenJDK/openjdk-support/files/4059847/ServerSigningExceptionDocker.txt)

**Comment by iritome** [comment]
Unfortunately we get exactly the same error.

**Comment by aahlenst** [comment]
@iritome Please share a project and steps to reproduce the issue.

**Comment by karianna** [comment]
> @iritome Please share a project and steps to reproduce the issue.

And go for 11.0.7

**Comment by aahlenst** [comment]
Closing due to lack of requested feedback.

**Comment by iritome** [comment]
Sorry for the delayed answer. Unfortunately, I cannot provide you any feedback until the 16the of June, the earliest, as I do not have access to the required systems until then.

**Comment by aahlenst** [comment]
@iritome No problem. Will reopen when you provide feedback.
