### ISSUE TITLE
OpenJ9: java.lang.ref.Reference.clear() unexpectedly called

### ISSUE THREAD

**Issue by jcflack** [AdoptOpenJDK/openjdk-support#42]
* **Platform and architecture (e.g. Linux/x64**:

Linux/x64

* **Java version (from "java --version") e.g. 1.8.0_181, 11.0.4+11 etc.**:

```
OpenJDK Runtime Environment (11.0.5+10)
Eclipse OpenJ9 VM (openj9-0.17.0, JRE 11 Linux amd64-64-Bit 20191016_322 (JIT enabled, AOT enabled)
OpenJ9   - 77c1cf708
OMR      - 20db4fbc
JCL      - 2a7af5674b based on jdk-11.0.5+10)
```

* **Variant e.g. HotSpot or OpenJ9**:

OpenJ9

* **Have you tested it with other vendors' java**:

Yes indeedy.

* **Steps to reproduce**:

Compile and run the following:

```java
import java.lang.ref.ReferenceQueue;
import java.lang.ref.WeakReference;

public class RefTest<T> extends WeakReference<T> {
  RefTest(T referent, ReferenceQueue<? super T> q) {
    super(referent, q);
  }

  @Override
  public void clear() {
    throw new UnsupportedOperationException("Hey! Don't call my clear()!");
  }

  private void internalClear() {
    /* allowed callers call here; do special stuff then really clear */
    super.clear();
  }

  public static void main(String[] args) {
    ReferenceQueue<String> q = new ReferenceQueue<>();
    RefTest<String> r = new RefTest<>("Hi!", q);
    r.enqueue();
  }
}
```

* **Error messsage and/or description of what is not working as expected**:

Test in HotSpot: expected result, successful completion (no output)

Test in OpenJ9:

```
Exception in thread "main" java.lang.UnsupportedOperationException: Hey! Don't call my clear()!
	at RefTest.clear(RefTest.java:11)
	at java.base/java.lang.ref.Reference.enqueue(Reference.java:106)
	at RefTest.main(RefTest.java:22)
```

The application class that overrides and disables `clear()` in this way is ok in principle, essentially as an assertion that client code is using it in the expected way.

The JDK API docs guarantee that `clear()` is never called by the garbage collector ("This method is invoked only by Java code; when the garbage collector clears references it does so directly, without invoking this method"). Also (except in OpenJ9, apparently), `enqueue()` does not call `clear()`. The API description for `enqueue()` says that it "clears this reference object" before enqueuing it, but in other JREs that *doesn't happen by calling the `clear()` method*; it's done directly, similarly to when the garbage collector does it.

The stack trace from OpenJ9 above shows `clear()` being called directly from `enqueue()`, on line 106 of `Reference.java`. Looking on `hg.openjdk.java.net`, I have not found any version of the jdk11 sources where `enqueue()` contains a call to `clear()` (and the method is rarely anywhere near line 106). Is the OpenJ9 build using some substituted version of `Reference.java`? Where is the source for that? And why does its `enqueue()` call `clear()`?

**Comment by pshipton** [comment]
FYI the OpenJ9 source is found here https://github.com/eclipse/openj9/blob/1ae5654cf79de053c96737b16acdac5acfb09389/jcl/src/java.base/share/classes/java/lang/ref/Reference.java#L135

**Comment by pshipton** [comment]
The behavior was added via https://github.com/eclipse/openj9/pull/900

**Comment by pshipton** [comment]
This is being resolved by https://github.com/eclipse/openj9/pull/8334, which will be in the OpenJ9 0.19 release (Java 14) and 0.20 release (Java 8, 11).

**Comment by aahlenst** [comment]
The upstream bug was closed and the fix released as part of the last quarterly update.
