### ISSUE TITLE
unable to use JMX parameters with AdoptOpenJDK

### ISSUE THREAD

**Issue by Sreenu-11** [AdoptOpenJDK/openjdk-support#43]
unable to use JMX parameters with Adopt OpenJDK  . We were using oracle java for jira7.9.2 and upgraded to v8.5.3 and using Adopt Open JDK , Jira is not starting if we add below parameters . How can we use below parameters with Adopt OPEN JDK?

JMX_PARAMETERS="-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=9010 -Dcom.sun.management.jmxremote.rmi.port=9010 -Dcom.sun.management.jmxrn.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false

* **Platform and architecture (e.g. Linux/x64**: Linux/x64

* **Java version (from "java --version") e.g. 1.8.0_181, 11.0.4+11 etc.**: AdoptOpenJDK -1.8.0_232 

* **Variant e.g. HotSpot or OpenJ9**: HotSpot

* **Have you tested it with other vendors' java**: yes .. it is working with oracle java 

* **Steps to reproduce**:

* **Error messsage and/or description of what is not working as expected**:
tomcat is not starting

**Comment by aahlenst** [comment]
@Sreenu-11 Please try with a recent version of AdoptOpenJDK, or even better one of the upstream builds: https://adoptopenjdk.net/upstream.html. If the problem persists, provide error messages or even better a sample project that we can run (public GitHub repositories are great for this).

If we don't hear from you in a week or so, I'm going to close this issue.

**Comment by aahlenst** [comment]
Closing due to lack of requested feedback.

**Comment by ksmith1787** [comment]
3 months waiting on a response, then given 10 days to respond. Submitter probably never saw the response in April.  Just FYI, this is a real bug.

**Comment by aahlenst** [comment]
@ksmith1787 Just because an issue is closed, this does not mean that it is forbidden to supply the requested infromation. You can do that, too, if you want us to work on it. Share an executable test case and we‘re happy to investigate.
