### ISSUE TITLE
Binaries for ShenandoahGC for Java 8?

### ISSUE THREAD

**Issue by KaneHart** [AdoptOpenJDK/openjdk-support#48]
* **Platform and architecture (e.g. Linux/x64**:
Windows 10

* **Java version (from "java --version") e.g. 1.8.0_181, 11.0.4+11 etc.**:

* **Variant e.g. HotSpot or OpenJ9**:
HotSpot

* **Have you tested it with other vendors' java**:
N/A

* **Steps to reproduce**:
java -XX:+UseShenandoahGC -jar forge-1.7.10-10.13.4.1614-1.7.10-universal.jar

* **Error messsage and/or description of what is not working as expected**:
Unrecognized VM option 'UseShenandoahGC'

Clearly the latest nightly build does not include it but I can't seem to find a binary for windows out there for Java 8 on a none corporate site that requires logins, etc.

**Comment by jerboaa** [comment]
Shenandoah GC is part of mainline HotSpot OpenJDK with JDK 12 onwards. See: https://openjdk.java.net/jeps/189.

That is JDK 11 AdoptOpenJDK builds won't have Shenandoah either. There is work under way to bring Shenandoah to JDK 11u. See:
http://mail.openjdk.java.net/pipermail/jdk-updates-dev/2020-January/002399.html

With any luck it'll land in JDK 8u mainline at some point in the future.

How would AdoptOpenJDK gain Shenandoa GC for JDK 8? By building from http://hg.openjdk.java.net/aarch64-port/jdk8u-shenandoah/

Builds currently available which might or might not fit your usecase (I have not tested/used them myself):
https://builds.shipilev.net/openjdk-shenandoah-jdk8/
https://developers.redhat.com/products/openjdk/download (requires developer login setup)

Full disclosure: I work for Red Hat.

**Comment by jerboaa** [comment]
@karianna not sure why you've flagged this as a bug. It's expected for AdoptOpenJDK builds to not contain Shenandoah.

**Comment by karianna** [comment]
Corrected the label and closing, thank you @jerboaa !
