### ISSUE TITLE
Inconsistent tool behavior between distributions

### ISSUE THREAD

**Issue by mipastgt** [AdoptOpenJDK/openjdk-support#49]
* **Platform and architecture (e.g. Linux/x64**: 
macOS 10.14.6

* **Java version (from "java --version") e.g. 1.8.0_181, 11.0.4+11 etc.**:
openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.6+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.6+10, mixed mode)

* **Variant e.g. HotSpot or OpenJ9**:
HotSpot

* **Have you tested it with other vendors' java**:
Yes

* **Steps to reproduce**:
Run the command `jar --describe-module --file your_favorite_jar.jar`

* **Error messsage and/or description of what is not working as expected**:
The problem is that the language of the output of the above command is different from other distributions as you can see below.
```
$ /Library/Java/JavaVirtualMachines/jdk-11.0.6.jdk/Contents/Home/bin/jar --describe-module --file annotations-16.0.3.jar
No module descriptor found. Derived automatic module.

org.jetbrains.annotations@16.0.3 automatic
requires java.base mandated
contains org.intellij.lang.annotations
contains org.jetbrains.annotations

$ /Library/Java/JavaVirtualMachines/jdk-11.0.6+10/Contents/Home/bin/jar --describe-module --file annotations-16.0.3.jar
Kein Moduldeskriptor gefunden. Automatisches Modul wurde abgeleitet.

org.jetbrains.annotations@16.0.3 automatic
requires java.base mandated
contains org.intellij.lang.annotations
contains org.jetbrains.annotations
```
The first command above is executed by Oracle JDK and the output is english whereas the second command is exectued with AdoptOpenJDK and the output is in german because the default locale of my machine is set to german. This poses a problem to scripts which analyze the output of such commands if some java distributions arbitrarily adopt different conventions of which output language is chosen. I wonder how such difference can occur if you do not fiddle explicitly with the common JDK sources. I have tested this with all Oracle OpenJDK distributions from 11 to 15 and they all use english as the output language. Only AdoptOpenJDK uses the language as defined by the default locale.

**Comment by sxa555** [comment]
This is a question for Oracle. I have verified that the openjdk binaries from ourselves, Azul, Bellsoft and Amazon and RedHat's reference implementation all behave in the same way as ours (they are all based on the OpenJDK codebase so that's what you'd expect).

Oracle must be doing something different on their internal builds to cause that difference. 

The line with that message is in the openjdk codebase here:
https://github.com/AdoptOpenJDK/openjdk-jdk11u/blob/5f01925b80ed851b133ee26fbcb07026ac04149e/src/jdk.jartool/share/classes/sun/tools/jar/resources/jar_de.properties#L80

**Comment by sxa555** [comment]
I would have thought that the non-Oracle behaviour was more in line with convention though - if you run, for example, `ls /NonsexistantFile` the message comes back in your system language (and would lead to similar parsing problems if you tried to process it) and the output from our releases is in line with that.

**Comment by mipastgt** [comment]
Not on my system. See attached screen shot.
<img width="506" alt="Bildschirmfoto 2020-02-03 um 00 38 37" src="https://user-images.githubusercontent.com/16735714/73617329-b7ceca00-461d-11ea-91d2-52c2b9c898ea.png">
You see that the menu line is in german but the shell uses english for the output of the 'ls' command. Obviously there are different language settings possible although I think what I am using is the default.

**Comment by sxa555** [comment]
Interesting - I was testing on Linux and setting `LC_ALL=de_DE` makes the message come out in German
```
[sxa@sxa git]$ LC_ALL=de_DE ls /NonexistantFile
ls: Zugriff auf /NonexistantFile nicht m�glich: Datei oder Verzeichnis nicht gefunden
[sxa@sxa git]$ 
```
although as you say I just logged into a macos box and it seems to behave differently (unless the language support isn't on the machine, but `locale -a` suggests they're all there.

**Comment by mipastgt** [comment]
Just for comparison. Here is what I get on the Mac for this:

```
ip8:~ mpaus$ echo $LANG
de_DE.UTF-8
ip8:~ mpaus$ echo $LC_ALL

ip8:~ mpaus$ locale -a
en_NZ
nl_NL.UTF-8
pt_BR.UTF-8
fr_CH.ISO8859-15
eu_ES.ISO8859-15
.
.
.
de_DE
lt_LT
tr_TR
C
POSIX
ip8:~ mpaus$ LC_ALL=de_DE ls /NonexistantFile
ls: /NonexistantFile: No such file or directory
ip8:~ mpaus$ 
```
As you can see LC_ALL is not set by default but setting it explicitly as you did also makes no difference.

Originally I discovered this issue under different circumstances. I wrote a Java program to analyze the content of JAR files and I used the ToolProvider class to access and run the jar command. This worked ok until I tried AdobtOpenJDK for the first time where I was hit by the problem described above. So I don't think that any terminal settings are relevant for this issue.

**Comment by aahlenst** [comment]
As Stewart pointed out, we‘re in line with OpenJDK. Therefore, there is nothing for us to do here.

On https://stackoverflow.com/questions/64038/setting-java-locale-settings, there are multiple ways described to influence the locale of a Java program.
