### ISSUE TITLE
macOS Version of AdoptOpenJDK 8 cannot be notarized

### ISSUE THREAD

**Issue by wjg57** [AdoptOpenJDK/openjdk-support#53]
* **Platform and architecture (e.g. Linux/x64**:
macOS 10.14/x64  / 10.15/x64

* **Java version (from "java --version") e.g. 1.8.0_181, 11.0.4+11 etc.**:
jdk8u242-b08

* **Variant e.g. HotSpot or OpenJ9**:
HotSpot

* **Have you tested it with other vendors' java**:
No

* **Steps to reproduce**:
$ otool -l java | grep sdk
shows the sdk version used to compile the binaries.
((The otool command is part of the XCode command line tools.))

* **Error messsage and/or description of what is not working as expected**:
The jdk8u242 macOS version as currently available for download is built w/r/t macOS SDK version 10.8.

This makes it impossible to perform notarization(1) of any assembly that contains an unmodified  copy of the JDK, because for notarization to work the minimum required SDK version is 10.9.

(1) https://developer.apple.com/documentation/xcode/notarizing_macos_software_before_distribution

**Comment by aahlenst** [comment]
Duplicate of https://github.com/AdoptOpenJDK/openjdk-build/issues/1130.

Please see https://github.com/AdoptOpenJDK/openjdk-build/issues/1130#issuecomment-580794726 for a summary.

**Comment by wjg57** [comment]
Yes, it's exactly this issue.

Tracking AdoptOpenJDK/openjdk-build#1130 (which I did not find even though I was looking)
