### ISSUE TITLE
jdk8u242-b08 crashes on AIX 7.1 : Type=Segmentation error vmState=0x00020011

### ISSUE THREAD

**Issue by trex58** [AdoptOpenJDK/openjdk-support#61]
* **Platform and architecture (e.g. Linux/x64**:
AIX 7.1 (7100-05-04-1913) PPC64 (BE)

* **Java version (from "java --version") e.g. 1.8.0_181, 11.0.4+11 etc.**:
+ /usr/jdk8u242-b08/bin/java -version
openjdk version "1.8.0_242"
OpenJDK Runtime Environment (build 1.8.0_242-b08)
Eclipse OpenJ9 VM (build openj9-0.18.1, JRE 1.8.0 AIX ppc64-64-Bit Compressed References 20200122_533 (JIT enabled, AOT enabled)
OpenJ9   - 51a5857
OMR      - 7a1b023
JCL      - 8cf8a30 based on jdk8u242-b08)

* **Variant e.g. HotSpot or OpenJ9**:
OpenJ9

* **Have you tested it with other vendors' java**:
Yes. IBM JVM. Breaks in another place.

* **Steps to reproduce**:
 wget https://github.com/bazelbuild/bazel/releases/download/2.1.0/bazel-2.1.0-dist.zip
 mkdir basel-2.1.0
 cd basel-2.1.0
 unzip ../bazel-2.1.0-dist.zip
export JAVA_HOME=/usr/jdk8u242-b08
export JAVA_OPTS="-Xmx8000m"
$JAVA_HOME/bin/java -version
python --version
env EXTRA_BAZEL_ARGS="--host_javabase=@local_jdk//:jdk" bash ./compile.sh

* **Error messsage and/or description of what is not working as expected**:

    currently loading: @com_google_protobuf//
    Fetching @remote_java_tools_linux; fetching
    Fetching ..._linux; Extracting /tmp/bazel_syiRoroD/out/external/remote_jav\
a_tools_linux/java_tools_javac11_linux-v7.0.zip
Unhandled exception
Type=Segmentation error vmState=0x00020011
[PB-AIX.txt](https://github.com/AdoptOpenJDK/openjdk-support/files/4230320/PB-AIX.txt)

J9Generic_Signal_Number=00000018 Signal_Number=0000000b Error_Value=00000000 Signal_Code=00000032
Handler1=09001000A08449A8 Handler2=09001000A0733890
...
See attached file.
[PB-AIX.txt](https://github.com/AdoptOpenJDK/openjdk-support/files/4230319/PB-AIX.txt)

**Comment by pshipton** [comment]
Duplicated at the OpenJ9 project https://github.com/eclipse/openj9/issues/8619
