### ISSUE TITLE
API URL returns 404

### ISSUE THREAD

**Issue by nealef** [AdoptOpenJDK/openjdk-support#62]
Every so often when I run wget against the URL:```https://api.adoptopenjdk.net/v2/binary/releases/openjdk13?openjdk_impl=hotspot&os=linux&arch=s390x&release=latest&type=jdk``` I receive "Not Found". This condition often lasts for a few hours before returning the expected tar ball. I am running a docker build script with the wget embedded so often reference it mutliple times per day as I attempt to get the build correct. It doesn't seem to happen for 8/11/12 but that may just be due to luck.

**Comment by karianna** [comment]
@nealef - Please use the new v3 API - https://api.adoptopenjdk.net/swagger-ui/ - issue is fixed there.
