### ISSUE TITLE
How can we get notification of new LTS releases?

### ISSUE THREAD

**Issue by m8ram** [AdoptOpenJDK/openjdk-support#64]
Not sure if this is the right place to log this but I can't find any other way to report this.

What options are there for us to subscribe to notifications of new releases?
I had a quick look at the API but that seems to allow only downloading new versions and does not offer a way to check if a newer version is available.

Email notification would work as well but is not preferred since we all receive far too many emails already.

**Comment by SnejPro** [comment]
I would like to see an updater for the windows version that notifies my when a new version is available. So i don't miss any security releases.

**Comment by karianna** [comment]
https://github.com/AdoptOpenJDK/TSC/issues/32
