### ISSUE TITLE
JDK 12.0.2.10 UnsatisfiedLinkError

### ISSUE THREAD

**Issue by ed0906** [AdoptOpenJDK/openjdk-support#65]
**Platform:**
Macbook Pro: Catalina 10.15.3
Java version:

```
openjdk 12.0.2 2019-07-16
OpenJDK Runtime Environment AdoptOpenJDK (build 12.0.2+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 12.0.2+10, mixed mode)
```

**Architecture:**
Spring Boot application using Kafka Streams (which uses Rocksdb)

**Issue**
```
java.lang.UnsatisfiedLinkError: /private/var/folders/zj/431cj13967x63b20h34m49r1y4hc5k/T/librocksdbjni13228446526115795751.jnilib: dlopen(/private/var/folders/zj/431cj13967x63b20h34m49r1y4hc5k/T/librocksdbjni13228446526115795751.jnilib, 1): no suitable image found.  Did find:
	/private/var/folders/zj/431cj13967x63b20h34m49r1y4hc5k/T/librocksdbjni13228446526115795751.jnilib: code signature in (/private/var/folders/zj/431cj13967x63b20h34m49r1y4hc5k/T/librocksdbjni13228446526115795751.jnilib) not valid for use in process using Library Validation: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.
```

I can confirm this is an issue with JDK build `12.0.2+10`. 
When I downgrade to  `12.0.1+12` the issue no longer appears.

**Comment by sxa555** [comment]
Is there a reason you're using JDK12? That one went out of support over six months ago and won't be getting any more updates.

**Comment by aahlenst** [comment]
This looks like the usual problems with binaries that are not notarized. JDK 13 is notarized, so this problem should go away.

**Comment by sxa555** [comment]
@aahlenst You wouldn't expect that to be different between 12.0.1 and 12.0.2 though would you?

**Comment by aahlenst** [comment]
There was a lot back and forth before Catalina was released. If I remember correctly, George enabled notarization and it seemed to work on the surface, but only because we did not send the notarized binaries through the test suite. Then we got bug reports, there was no quick fix and in turn rolled everything back because of it.

**Comment by sxa555** [comment]
Hmmm yeah now you mention it that could have been around that time. Fair comment.

**Comment by ed0906** [comment]
> Is there a reason you're using JDK12? That one went out of support over six months ago and won't be getting any more updates.

For whatever reason our architecture currently only supports Java 12

**Comment by karianna** [comment]
@ed0906 - I'm afraid we won't be putting out a new release of the 12.0.x series.  13.0.2 is the current non-LTS supported release.
