### ISSUE TITLE
JavaFX app crashes OpenJDK8U-jdk_arm_linux_hotspot_8u232b09 on Raspbian 8 (jessie) with Internal Error (os_linux_zero.cpp:254)

### ISSUE THREAD

**Issue by ptkatch** [AdoptOpenJDK/openjdk-support#66]
* **Platform and architecture (e.g. Linux/x64**:
Raspbian GNU/Linux 8 (jessie)/armv7l (Raspbian Pi 3B)

* **Java version (from "java --version") e.g. 1.8.0_181, 11.0.4+11 etc.**:
openjdk version "1.8.0_232"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_232-b09)
OpenJDK Zero VM (AdoptOpenJDK)(build 25.232-b09, interpreted mode)

* **Variant e.g. HotSpot or OpenJ9**:

* **Have you tested it with other vendors' java**:
Yes, Oracle jdk-8u192-linux-arm32-vfp-hflt.tar.gz, works fine, 
Azul zulu8.40.0.178-ca-jdk1.8.0_222-linux_aarch32hf crashes at libfreetype.so.6

* **Steps to reproduce**:
- Install https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u232-b09/OpenJDK8U-jdk_arm_linux_hotspot_8u232b09.tar.gz
- Install armv6hf-sdk-8.60.9.zip from https://gluonhq.com/download/javafx-embedded-sdk by following José Pereda's instructions at  
    https://stackoverflow.com/questions/40481455/running-javafx-gui-on-the-raspberry-pi/40483500#40483500
- Run app: `java -cp /home/pi/MapTest.jar -Djava.security.policy=/home/pi/crm.policy BrowserTest.StartUp3`	  

* **Error messsage and/or description of what is not working as expected**:
A fatal error has been detected by the Java Runtime Environment:
Internal Error (os_linux_zero.cpp:254), pid=751, tid=0x61d62460
fatal error: caught unhandled signal 11"
  
See attached file AdoptOpenJDK_hs_err_pid751.log
[AdoptOpenJDK_hs_err_pid751.log](https://github.com/AdoptOpenJDK/openjdk-support/files/4259013/AdoptOpenJDK_hs_err_pid751.log)

**Comment by aahlenst** [comment]
OpenJFX 8 is unmaintained. If you need to stay on JDK 8, please use one of Oracle‘s offerings (Oracle JDK). Otherwise, upgrade to OpenJFX 14 together with AdoptOpenJDK 14. If the issue persists, report back.

**Comment by ptkatch** [comment]
Error comes from (still maintained?) AdoptOpenJDK8, not OpenJFX8. OpenJFX14 builds available for armv6 AFAIK do not support WebKit I need.

**Comment by aahlenst** [comment]
@ptkatch The dump you provided is full of references to JavaFX. If the problem is not in JavaFX, why do I have to install it to reproduce the problem?

AdoptOpenJDK 8 is going to be supported beyond 2025, but that is not enough. JavaFX needs to be updated alongside and this isn‘t happening.

**Comment by ptkatch** [comment]
@aahlenst because JavaFX helps to pinpoint problem in AdoptOpenJDK? I am just trying to find solution with tools I have available.

**Comment by aahlenst** [comment]
Again, the crash dump is full of references to JavaFX. Why should the problem be in AdoptOpenJDK?

Is that version of JavaFX supposed to be compatible to 8u232?

And: Please share a project that we can run that reproduces the problem.

**Comment by ptkatch** [comment]
Thank you Andreas for re-opening this case. To answer your 1st and 2nd questions, 
test app MapTest.jar works with Azul's 8u242 (zulu8.44.0.213-ca-jdk1.8.0_242-linux).
It supposed to look like on MapTest.jpg picture.
  
MapTest.jar was provided to us by 3rd party developer, so if you have questions re sources
it may take some time to get the answers.
  
Thank you.
[MapTest.zip](https://github.com/AdoptOpenJDK/openjdk-support/files/4665572/MapTest.zip)

**Comment by aahlenst** [comment]
The key difference between AdoptOpenJDK and Zulu/Liberica is, that both Azul and BellSoft have their private fork of OpenJFX 8 that they each patch independently and bundle with their OpenJDK. So if they notice that OpenJFX stops working, they fix it in their private OpenJFX fork.

Reading your report, you try to get to the same result, but now with AdoptOpenJDK (that knows nothing of OpenJFX) and a OpenJFX 8 build from Gluon, that is most likely very old and, because the public OpenJFX 8 is unmaintained, not tested/patched to work with more recent versions of OpenJDK. I do not know for sure, but Gluon as OpenJFX lead stated that they not intend to work on anything pre OpenJDK 11 (that‘s the point where Oracle stopped bundling it). Has that changed?

To make AdoptOpenJDK support OpenJFX 8, we‘d either need volunteers with the necessary knowledge or donors that make it possible to hire at least one person. Until now, neither has happened which indicates that interest is low. Also, our discussions with Azul and BellSoft went nowhere.

To convince me that the problem is in AdoptOpenJDK, show me that the same thing works with Red Hat‘s OpenJDK build, available from https://adoptopenjdk.net/upstream.html. Otherwise we cannot help.

**Comment by ptkatch** [comment]
1. My target is Raspberry Pi. Azul JDK8 linux armv6 build doesn't have JavaFX, you have to use 3rd party JavaFX like Gluon. 
MapTest app works with combo Azul JDK8 + Gluon JavaFX8, how does fixing Azul OpenJFX fork make Azul JDK to work?
2. Don't know Gluon plans about JFX8, only that gluon-jfx-8.60.9 works with azul-jdk-8.242 
3. I understand your resources challenge, why did you ask me for the test case then?
4. There's no RedHat's OpenJDK8 linux build for armv6 available at https://adoptopenjdk.net/upstream.html

**Comment by aahlenst** [comment]
I tested our first nightly build with a proper client VM in a long time, available on https://ci.adoptopenjdk.net/job/jdk8u-linux-arm-hotspot-client/1/artifact/workspace/target/OpenJDK8U-jdk_arm_linux_hotspot_2020-08-05-15-51.tar.gz.

Following the instructions in https://stackoverflow.com/a/40483500/759042 with a slight difference (see below), I can report that we've reached parity of Azul Zulu 8u265 for ARM32: I can run https://docs.oracle.com/javase/8/javafx/get-started-tutorial/hello_world.htm without crashing. It does not display a GUI on the latest Raspbian 10, prints only "Hello World" to the console and except the space bar no input device works anymore, effectively forcing me to power-cycle the Raspberry Pi.

One thing to note: The line `sudo mv arm/* /opt/jdk1.8.0_111/jre/lib/arm/` in https://stackoverflow.com/a/40483500/759042 is not correct (anymore). It should read `sudo mv arm/* /opt/jdk1.8.0_111/jre/lib/aarch32`.

So, from my point of view, we've done what we could do. If you need anything better, please reach out to Gluon or OpenJFX.

**Comment by ptkatch** [comment]
Thank You, Andreas.

Pavel.
________________________________
