### ISSUE TITLE
EXCEPTION_ACCESS_VIOLATION with OpenJDK 64-Bit 8.0_202-b08 for Windows-64

### ISSUE THREAD

**Issue by TCSSupport** [AdoptOpenJDK/openjdk-support#67]
**Description**: We observed application outage several times while Atlassian was helping us investigate on application side. We have checked the application server and found that Tomcat service was in stopped state in our two nodes in several occasions. There is no clear or reproducible reason to make the issue happen. From the attached hs_err_pidxxxx.log file, you can see it shows a problematic frame: [fontmanager.dll+0x60158]. Atlassian recommended different approaches since the problem indicates there is something wrong with the fontmanager and how it is handling the fonts available either inside the JDK directory structure or in the Windows directory structure. We even upgraded the JDK to a more recent version as per Atlassian recommendation but to no avail. Please help us investigate the issue.

**URL / Application Name**: Atlassian Confluence 6.13.6 Data Center with 2 nodes - Microsoft SQL Server 12.00.6024 and Windows Server 2012 R2 amd64

We have attached the log
[hs_err_pid15864_1.log](https://github.com/AdoptOpenJDK/openjdk-support/files/4283774/hs_err_pid15864_1.log)

**Comment by TCSSupport** [comment]
The issue has happened again. Can you please confirm if upgrading the JDK version will help if this is an issue with the older fontmanager.dll?

**Comment by karianna** [comment]
@TCSSupport Have you tried the jdk 1.8.0_242 build?

**Comment by aahlenst** [comment]
Closing due to lack of requested feedback.
