### ISSUE TITLE
Mac OS hardened runtime?

### ISSUE THREAD

**Issue by rqqb** [AdoptOpenJDK/openjdk-support#72]
Mac OS 10.14

Java version : any

Are any of the Mac OS builds built with hardened runtime so that they can be included in notarised packages?

**Comment by aahlenst** [comment]
https://github.com/AdoptOpenJDK/openjdk-build/issues/1130

tl;dr: Nightly builds of AdoptOpenJDK 11 are ready. AdoptOpenJDK 8 is waiting for the necessary patches to be upstreamed at OpenJDK (I haven't seen them yet). AdoptOpenJDK 14 (EA) should be ready, please see https://github.com/AdoptOpenJDK/openjdk14-binaries/releases for binaries and report back whether they work.

**Comment by rqqb** [comment]
I tried jdk14-2020-03-08-04-22

Apparently the signature on Contents/MacOS/libjli.dylib is invalid, otherwise looks OK.

Also tried an AdoptOpenJDK 11 (from Jan 2019??), not hardened but maybe I didn't get the latest.

**Comment by aahlenst** [comment]
AdoptOpenJDK 11 would be here: https://adoptopenjdk.net/nightly.html?variant=openjdk11&jvmVariant=hotspot. Latest PKG was produced on the 6th of March.

**Comment by rqqb** [comment]
Getting the same error with the latest AdoptOpenJDK 11:

{
      "severity": "error",
      "code": null,
      "path": "PDVinstall.zip/PDVinstall.app/Contents/Resources/Java/jre.zip/jre/Contents/MacOS/libjli.dylib",
      "message": "The signature of the binary is invalid.",
      "docUrl": null,
      "architecture": "x86_64"
    }

**Comment by sxa555** [comment]
Main issue for addition of notarization at AdoptOpenJDK for reference https://github.com/AdoptOpenJDK/openjdk-build/issues/1130

**Comment by aahlenst** [comment]
Likely causes for the problems:

AdoptOpenJDK/openjdk-build#1584
AdoptOpenJDK/openjdk-build#1585

**Comment by karianna** [comment]
@gdams Can this be closed as a duplicate?

**Comment by aahlenst** [comment]
@rqqb Notarized PKGs have been released for all supported OpenJDK versions. If you still experience issues, please open a new issue.

**Comment by tmmlsBE** [comment]
I have the same issue in version Temurin-17.0.2+8 

      "path": "<deleted>/Contents/runtime/Contents/MacOS/libjli.dylib",
      "message": "The signature of the binary is invalid.",
      "docUrl": null,
      "architecture": "x86_64"

What is the solution?

**Comment by karianna** [comment]
> I have the same issue in version Temurin-17.0.2+8
> 
> ```
>   "path": "<deleted>/Contents/runtime/Contents/MacOS/libjli.dylib",
>   "message": "The signature of the binary is invalid.",
>   "docUrl": null,
>   "architecture": "x86_64"
> ```
> 
> What is the solution?

use the latest 17.0.3 pkg package
