### ISSUE TITLE
FlightRecorderOptions reset date format

### ISSUE THREAD

**Issue by atosscsd-bb** [AdoptOpenJDK/openjdk-support#77]
Running java with VM-argument `-XX:FlightRecorderOptions` will reset the date format to *en*.

* **Platform and architecture:** Linux/x64

* **Java version**:
```
openjdk version "14" 2020-03-17
OpenJDK Runtime Environment AdoptOpenJDK (build 14+36)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 14+36, mixed mode, sharing)
```

* **Variant:** HotSpot

* **Have you tested it with other vendors' java**: Reproduces also with OracleJDK 14

* **Steps to reproduce**

Consider following class:
```
import java.text.DateFormat;
import java.util.Calendar;
import java.util.GregorianCalendar;

public class Main
{
    public static void main( String[] args )
    {
        GregorianCalendar date = new GregorianCalendar( 2020, Calendar.JANUARY,
            1 );
        DateFormat formatter = DateFormat.getDateTimeInstance();

        String expected = "01.01.2020, 00:00:00";
        String formatted = formatter.format( date.getTime() );

        System.out.println(
            String.format( "expected: %s%nactual:   %s", expected, formatted ) );
    }
}
```

When running this class java 14 and with VM arguments `-Duser.country=DE -Duser.language=de -XX:StartFlightRecording`, `date` will be formatted to `01.01.2020, 00:00:00`.

When running this class with java 14 and VM arguments `-Duser.country=DE -Duser.language=de -XX:StartFlightRecording -XX:FlightRecorderOptions=stackdepth=128`, `date` will be formatted to `2020 Jan 1 00:00:00`.

I'd expect that in both cases, the formatted date is identical.

This scenario works as expected with latest java 11.

**Comment by karianna** [comment]
@atosscsd-bb This is an upstream bug that should be reported to http://mail.openjdk.java.net/mailman/listinfo/hotspot-jfr-dev - I think the bug report you have should be fine to drop to that mailing list and they'll open a ticket.

**Comment by atosscsd-bb** [comment]
@karianna Thanks for the link. Reported issue to mailing list.
