### ISSUE TITLE
elasticsearch-env: line 71: 124 Aborted  (core dumped)

### ISSUE THREAD

**Issue by aalloosshh** [AdoptOpenJDK/openjdk-support#78]
Ubuntu 18.04.4 LTS, 4.15.0-76-generic

JRE version:  (11.0.6+10
OpenJDK 64-Bit Server VM (11.0.6+10, mixed mode, tiered, compressed oops, g1 gc, linux-amd64)

Client: Docker Engine - Community Version:           19.03.5
Server: Docker Engine - Community  Version:          18.09.9

root@K8C01-W02:~# docker run --name elasticsearch bitnami/elasticsearch:latest
 13:30:58.85
 13:30:58.87 Welcome to the Bitnami elasticsearch container
 13:30:58.87 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-elasticsearch
 13:30:58.87 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-elasticsearch/issues
 13:30:58.88 Send us your feedback at containers@bitnami.com
 13:30:58.88
 13:30:58.88 INFO  ==> ** Starting Elasticsearch setup **
 13:30:59.00 INFO  ==> Configuring/Initializing Elasticsearch...
 13:30:59.04 INFO  ==> Setting default configuration
 13:30:59.06 INFO  ==> Configuring Elasticsearch cluster settings...

 13:30:59.18 INFO  ==> ** Elasticsearch setup finished! **
 13:30:59.19 INFO  ==> ** Starting Elasticsearch **
 A fatal error has been detected by the Java Runtime Environment:

 SIGILL (0x4) at pc=0x00007efdd42be7f2, pid=124, tid=125

 JRE version:  (11.0.6+10) (build )
 Java VM: OpenJDK 64-Bit Server VM (11.0.6+10, mixed mode, tiered, compressed oops, g1 gc, linux-amd64)
 Problematic frame:
 v  ~StubRoutines::call_stub

 Core dump will be written. Default location: Core dumps may be processed with '/usr/share/apport/apport %p %s %c %d %P" (or dumping to //core.124)

 An error report file with more information is saved as:
 /tmp/hs_err_pid124.log
Could not load hsdis-amd64.so; library not loadable; PrintAssembly is disabled

 If you would like to submit a bug report, please visit:
   https://github.com/AdoptOpenJDK/openjdk-support/issues

/opt/bitnami/elasticsearch/bin/elasticsearch-env: line 71:   124 Aborted                 (core dumped) "$JAVA" -cp "$ES_CLASSPATH" org.elasticsearch.tools.java_version_checker.JavaVersionChecker

can some help me, by explain what this error mean, and how can i solve this issue. 
thank you

**Comment by aahlenst** [comment]
Please see https://github.com/AdoptOpenJDK/openjdk-build/issues/893. Should be fixed in 11.0.7+4 or better.
