### ISSUE TITLE
browser plugin javaws using IE and Chrome

### ISSUE THREAD

**Issue by vp054179** [AdoptOpenJDK/openjdk-support#79]
* **Platform and architecture (e.g. Linux/x64**: Windows

* **Java version (from "java --version") e.g. 1.8.0_181, 11.0.4+11 etc.**:  openjdk version "1.8.0_242"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_242-b08)
OpenJDK Client VM (AdoptOpenJDK)(build 25.242-b08, mixed mode)

* **Variant e.g. HotSpot or OpenJ9**: hotspot

* **Have you tested it with other vendors' java**: yes

* **Steps to reproduce**:

* **Error messsage and/or description of what is not working as expected**:

THere is not java browser plugin like we Oracle used to have. I want to know how can i do it using icedtea web?

**Comment by karianna** [comment]
See https://github.com/adoptopenjdk/icedtea-web

**Comment by vp054179** [comment]
i could launch my jnlp using icedtea web command line...but i want to download the jnlp from my browser so downloading it and running it i need 

![internet-explorer](https://user-images.githubusercontent.com/62913960/77969945-a407b300-72b0-11ea-9b46-b92a52d2e497.jpg)

**Comment by karianna** [comment]
No Adopt does not (and won't as it's a security concern) - you'll need to stick with Oracle for Java 8 or try OpenWebStart by Karakun
