### ISSUE TITLE
Visual Studio Code unable to access the JDK.

### ISSUE THREAD

**Issue by astroman133** [AdoptOpenJDK/openjdk-support#82]
* **Platform and architecture (e.g. Linux/x64**:
Windows 10 x64

* **Java version (from "java --version") e.g. 1.8.0_181, 11.0.4+11 etc.**:
11.0.6.10

* **Variant e.g. HotSpot or OpenJ9**:
Hotspot

* **Have you tested it with other vendors' java**:
New to Java, so no.

* **Steps to reproduce**:
In Visual Studio Code JDK configuration says "JDK 8+ is required while the path is pointing to version 0." However, AdoptOpenJDK is installed and configured at C:\Program Files\AdoptOpenJDK\jdk-11.0.6.10-hotspot and is the specified location in the java.home setting and the JDK_HOME and JAVA_HOME environment variables.

I have tried re-installing both the JDK and VSC, as well as logging off and on.

I posted this with the Visual Studio Code repo, but they said that it was not their problem.

* **Error messsage and/or description of what is not working as expected**:
JDK 8+ is required while the path is pointing to version 0.

**Comment by aahlenst** [comment]
Could you add a link to the documentation plus a link to the Visual Studio Code ticket?

**Comment by brunoborges** [comment]
@astroman133 are you on Windows? If yes, please give a try to the Java Pack Installer:

https://aka.ms/vscode-java-installer-win

**Comment by astroman133** [comment]
Thanks! Yes, I am running Windows 10 x64, but the vscode-java-installer was already installed. Because it is a MS installer, I contacted them first.

I re-ran the VSC Java Pack Installer and got the following error output.
[11:49:03 AM] Download JDK
[11:52:38 AM] Download JDK ... [Completed]
[11:52:38 AM] Install JDK
[11:53:28 AM] Install JDK ... [Completed]
[11:53:28 AM] Configure Java Settings
[11:53:28 AM] Error occurred
[11:53:28 AM] Java Home not found.

I created another VSC ticket; Here is a link: [https://github.com/microsoft/vscode-java-pack/issues/351](url)

**Comment by brunoborges** [comment]
Thanks @astroman133 ... I'll continue the discussion over the ticket on the vscode-java-pack project since this is an issue with VS Code, not with AdoptOpenJDK.

@karianna you may close this issue now.
