### ISSUE TITLE
NullPointerException when loading DLLs (Windows x64)

### ISSUE THREAD

**Issue by fmukrjs** [AdoptOpenJDK/openjdk-support#83]
Windows 10 x64
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.242-b08, mixed mode)
HotSpot

Unable to load a 64-bit DLL:

Caused by: java.lang.NullPointerException
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1847)
        at java.lang.Runtime.loadLibrary0(Runtime.java:871)
        at java.lang.System.loadLibrary(System.java:1124)

It works in these previous releases:
8u232-b09
8u222-b10
8u202-b08

I am not sure whether this is also a problem in 32-bit environments.

We will re-test with 8u252 when it is released.

**Comment by JohnLussmyer** [comment]
I just updated to JDK OpenJDK11U-jdk_x64_windows_hotspot_11.0.7_10
and I'm getting a similar error.

08:44:31.915 [Metrix TSCall-Remote] DEBUG m.efi.tileserver.TileServerJNI - loading: common DLL: msvcr110
08:44:31.915 [Metrix TSCall-Remote] ERROR m.efi.tileserver.TileServerJNI - loading: Native code library failed to load:
java.lang.NullPointerException: null
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:2646) ~[?:?]
	at java.lang.Runtime.loadLibrary0(Runtime.java:830) ~[?:?]
	at java.lang.System.loadLibrary(System.java:1870) ~[?:?]
	at com.efi.tileserver.TileServerJNI.<clinit>(TileServerJNI.java:68) [bin/:?]
	at java.lang.Class.forName0(Native Method) [?:?]
	at java.lang.Class.forName(Class.java:315) [?:?]

**Comment by aahlenst** [comment]
Please test with https://adoptopenjdk.net/upstream.html?variant=openjdk8&jvmVariant=hotspot (OpenJDK 8) and https://adoptopenjdk.net/upstream.html?variant=openjdk11&jvmVariant=hotspot (OpenJDK 11) and report back.

**Comment by JohnLussmyer** [comment]
Updated to referenced JDK 11, same error.

**Comment by karianna** [comment]
@JohnLussmyer which version of Windows are you running on?

**Comment by karianna** [comment]
I suspect this is a 'we use a too modern build toolchain' issue

**Comment by JohnLussmyer** [comment]
Windows 7 (yeah, I know...)

**Comment by aahlenst** [comment]
Windows 7 is no longer officially supported by AdoptOpenJDK. We are now on Windows Server 2012 R2 and Windows 8.1. Official announcement is forthcoming.

**Comment by JohnLussmyer** [comment]
Is the JVM going to Detect Win 7 and not allow it to run?

**Comment by karianna** [comment]
> Is the JVM going to Detect Win 7 and not allow it to run?

It won't per se but the native DLLs the JVM expect likely won't be there on Windows 7 and so....

**Comment by aahlenst** [comment]
> Is the JVM going to Detect Win 7 and not allow it to run?

No.

Due to the EOL of Windows 7 and Server 2008 R2, we‘re now building and testing on different platforms. Toolchain should be the same as before, but apparently isn‘t. If you can reproduce the issue on Windows 8.1, we might be able to do something about it.

**Comment by JohnLussmyer** [comment]
So, Java 11 will be able to launch on Win 7 - but things may not work correctly.
Is that a correct statement?
I need to be clear on how things are going to work, as we can disable the feature that uses the DLL's if the OS is Win 7.

**Comment by aahlenst** [comment]
We‘re not doing anything on purpose to render our Windows binaries unusable on older Windows versions. Until your bug report came in, we expected them to work as before.

**Comment by JohnLussmyer** [comment]
Ok.  Thank you.  That does make life a bit easier.

**Comment by JohnLussmyer** [comment]
We have now been able to re-test this on Windows 10.
It ALSO fails on Windows 10.

09:56:17.245 [ Metrix TSCall-Local] DEBUG m.efi.tileserver.TileServerJNI - loading: common DLL: msvcr110
09:56:17.246 [ Metrix TSCall-Local] ERROR m.efi.tileserver.TileServerJNI - loading: Native code library failed to load:
java.lang.NullPointerException: null
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:2646) ~[?:?]
	at java.lang.Runtime.loadLibrary0(Runtime.java:830) ~[?:?]
	at java.lang.System.loadLibrary(System.java:1870) ~[?:?]

**Comment by JohnLussmyer** [comment]
Shall I create a new issue for this?

**Comment by fmukrjs** [comment]
> Windows 10 x64
> OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.242-b08, mixed mode)
> HotSpot
> 
> Unable to load a 64-bit DLL:
> 
> Caused by: java.lang.NullPointerException
> at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1847)
> at java.lang.Runtime.loadLibrary0(Runtime.java:871)
> at java.lang.System.loadLibrary(System.java:1124)
> 
> It works in these previous releases:
> 8u232-b09
> 8u222-b10
> 8u202-b08
> 
> I am not sure whether this is also a problem in 32-bit environments.
> 
> We will re-test with 8u252 when it is released.

It seems my original reported problem has been lost and the issue closed because of a similar problem in a completely different (and unsupported) environment (i.e. Windows 7). The original issue I reported was on Windows 10 which is supported.

We have re-tested with the latest releases of 8 and 11 and it is now broken in both of them. So the problem was introduced between 8u232-b09 and 8u242-b08. In v11, it was introduced at a similar time although I am not sure of the exact version.

Can you please re-open this?

**Comment by aahlenst** [comment]
@JohnLussmyer @fmukrjs Thanks for reporting back.

To get things going: Can one of you provide an executable test case?

To clarify, you tested with https://adoptopenjdk.net/upstream.html? If it happens with it, too, it's an OpenJDK issue. Then we have to report it elsewhere and really need an executable test case.

**Comment by JohnLussmyer** [comment]
Okay, just tried with OpenJDK11U-jre_x64_windows_11.0.7_10.zip
Same Error

14:45:39.213 [                main] INFO             applications.Metrix - java.vm.version= 11.0.7+10
14:45:39.213 [                main] INFO             applications.Metrix - java.vm.vendor=  Oracle Corporation
14:45:39.213 [                main] INFO             applications.Metrix - java.vm.name=    OpenJDK 64-Bit Server VM

14:45:39.418 [ Metrix TSCall-Local] DEBUG m.efi.tileserver.TileServerJNI - loading: common DLL: msvcr110
14:45:39.418 [ Metrix TSCall-Local] ERROR m.efi.tileserver.TileServerJNI - loading: Native code library failed to load:
java.lang.NullPointerException: null
    at java.lang.ClassLoader.loadLibrary(Unknown Source) ~[?:?]
    at java.lang.Runtime.loadLibrary0(Unknown Source) ~[?:?]
    at java.lang.System.loadLibrary(Unknown Source) ~[?:?]

**Comment by fmukrjs** [comment]
I have an update after experimenting further. These are the results for several recent builds:

JDK 11
11.0.6 - working
11.0.7 (all release builds) - not working
11.0.8+1 (30 Apr 2020) - not working

JDK 8
8u232 - Working
8u242 - Not working
8u252 - Working

The reason it is not working is that the sys_paths static field in ClassLoader is null in the call to LoadLibrary made by the 3rd party JNI class library.

I used the debugger to check the value of sys_paths before making the first call to the library and it is set as expected but after the call fails, it is null. On builds that work, it is set to the same value before the call and after it.

What I notice is that in 8u242, 11.0.7 and 11.0.8 (the non-working versions), there is a static method in ClassLoader called `initLibraryPaths` that sets the value of `sys_paths` whereas in the working versions, the code to set `sys_paths` is at the top of the `loadLibrary` method:
`if (sys_paths == null) {
usr_paths = initializePath("java.library.path"); ... }`
with no method called `initLibraryPaths`.

That can't be a coincidence!

Why was the change from 8u232 to 8u242 reverted in 8u252 and why has the same change not been reverted in 11.0.7?

**Comment by aahlenst** [comment]
Both of you, please give the output of `java -version` for every test you make so that I can determine who built the offending JDK. If it only affects AdoptOpenJDK, it is toolchain related. If it affects AdoptOpenJDK and builds provided by Red Hat, it is either the toolchain or a bug in OpenJDK.

In either case, we really need something that we can run ourselves that triggers the bug. The test suite did not catch it and I have no JNI calling code lying around. Without it, I cannot find out if compiling with another VS version helps.

@fmukrjs While I appreciate your analysis, I does not really help at the moment. If you want an answer to your question about the changes in OpenJDK, you need to dig in yourself. I did a quick search of JBS with the information both of you provided, but nothing interesting popped up.

**Comment by JohnLussmyer** [comment]
Note that my post made 19 hours ago IS testing with the Redhat build from the previously posted upstream.html page, AND that my post does include the build version information.

**Comment by JohnLussmyer** [comment]
Just wrote this little test app that reproduces the problem.
[TestLoadDLL.zip](https://github.com/AdoptOpenJDK/openjdk-support/files/4565482/TestLoadDLL.zip)

**Comment by JohnLussmyer** [comment]
Oops, forgot the source file.

package com.test;

import java.io.File;
import java.lang.reflect.Field;

public class TestLoadlibDLL {

	public static void main(final String[] args) {
		String dllName = "msvcr110";
		String dir = System.getProperty("user.dir");
		File file = new File(dir, dllName + ".dll");
		System.out.println("Path=" + file.getAbsolutePath() + ", " + file.exists());

		// Add DLL location to paths
		try {
			String newpath = dir + ";" + System.getProperty("java.library.path");
			System.out.println("library.path=" + newpath);
			System.setProperty("java.library.path", newpath);
			Field fieldSysPath = ClassLoader.class.getDeclaredField("sys_paths");
			fieldSysPath.setAccessible(true);
			fieldSysPath.set(null, null);

		} catch (NoSuchFieldException | SecurityException | IllegalArgumentException | IllegalAccessException e) {
			System.err.println("FAILED to add path");
			System.exit(-1);
		}

		System.loadLibrary(dllName);
		System.out.println("Loaded " + dllName);
	}

}

**Comment by fmukrjs** [comment]
> Oops, forgot the source file.
> 
> ```
> package com.test;
> 
> import java.io.File;
> import java.lang.reflect.Field;
> 
> public class TestLoadlibDLL {
> 
> 	public static void main(final String[] args) {
> 		String dllName = "msvcr110";
> 		String dir = System.getProperty("user.dir");
> 		File file = new File(dir, dllName + ".dll");
> 		System.out.println("Path=" + file.getAbsolutePath() + ", " + file.exists());
> 
> 		// Add DLL location to paths
> 		try {
> 			String newpath = dir + ";" + System.getProperty("java.library.path");
> 			System.out.println("library.path=" + newpath);
> 			System.setProperty("java.library.path", newpath);
> 			Field fieldSysPath = ClassLoader.class.getDeclaredField("sys_paths");
> 			fieldSysPath.setAccessible(true);
> 			fieldSysPath.set(null, null);
> 
> 		} catch (NoSuchFieldException | SecurityException | IllegalArgumentException | IllegalAccessException e) {
> 			System.err.println("FAILED to add path");
> 			System.exit(-1);
> 		}
> 
> 		System.loadLibrary(dllName);
> 		System.out.println("Loaded " + dllName);
> 	}
> }
> ```

I can see why it isn't working now.

The versions that it does not work on have changed the way sys_paths is evaluated. Instead of being evaluated on each call to loadLibrary (if it is null), it is evaluated once during VM startup.

Therefore, the "trick" of setting sys_paths to null by forcing access using reflection as in your code sample will not work any more.

I suspect the Beckhoff library I am using is using the same trick to adjust the paths.

Since this really shouldn't be done and there is already a warning "All illegal access operations will be denied in a future release", I don't really see this as a bug.

To make it work (by force), you could test for the existence of the static method initLibraryPaths on ClassLoader and call that instead of setting sys_paths to null.

The following will work (I tried it) but I don't recommend it as it will most likely stop working in some future release:

```
      try {
        Method initLibPaths = ClassLoader.class.getDeclaredMethod("initLibraryPaths");
        initLibPaths.setAccessible(true);
        initLibPaths.invoke(null);
      }
      catch (NoSuchMethodException | InvocationTargetException e) {
        Field fieldSysPath = ClassLoader.class.getDeclaredField("sys_paths");
        fieldSysPath.setAccessible(true);
        fieldSysPath.set(null, null);
      }
```
As far as I am concerned, this issue can be closed now since it only breaks code that is doing something it shouldn't!

**Comment by karianna** [comment]
@fmukrjs thank you so much!

**Comment by JohnLussmyer** [comment]
So this means there is no supported way to load a DLL that isn't on the path BEFORE launching the JVM?  (We don't even know if the DLL should be loaded, or even exists before our app is running.)

**Comment by aahlenst** [comment]
@JohnLussmyer Probably best to ask on StackOverflow. If you do so, please add a link to your post here.
