### ISSUE TITLE
OpenJDK 11 + OpenJ9: DateFormat does't work well on AIX

### ISSUE THREAD

**Issue by gaolibj** [AdoptOpenJDK/openjdk-support#84]
**Platform:**
AIX
**Architecture:**
PPC64
Please describe the issue that you are having with our binaries and if possible how to recreate it.
There is a simple case to recreate the issue. 

bash-4.4$ cat DateFormatTest.java
import java.text.*;
import java.util.*;

public class DateFormatTest{
public static void main(String[] args){
        DateFormat df = DateFormat.getDateInstance(DateFormat.MEDIUM, Locale.CHINA);
        String date = df.format(new Date());
        System.out.println("MEDIUM :" + date);
    }
}

bash-4.4$ java DateFormatTest    
MEDIUM :2020?4?16?

openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.6+10)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.18.1, JRE 11 AIX ppc64-64-Bit Compressed References 20200122_466 (JIT enabled, AOT enabled)
OpenJ9   - 51a5857
OMR      - 7a1b023
JCL      - da35e0c based on jdk-11.0.6+10)

**Comment by gaolibj** [comment]
Just tried the latest build. Seems still failed.  The built you said hasn't released.  Right? I will try the new one tomorrow.  BTW, can I know the detailed changeset for the fix?  Thanks.

bash-4.4$ bin/java -version
openjdk version "11.0.7" 2020-04-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.7+9-202004142340)
Eclipse OpenJ9 VM AdoptOpenJDK (build master-31b6c98, JRE 11 AIX ppc64-64-Bit Compressed References 20200414_561 (JIT enabled, AOT enabled)
OpenJ9   - 31b6c98
OMR      - f06e656
JCL      - 58d6fa1 based on jdk-11.0.7+9)
bash-4.4$ bin/java -cp /home/gaolibj DateFormatTest
MEDIUM :2020?4?16?

**Comment by pshipton** [comment]
The jdk11 result looks reasonable to me: `MEDIUM :2020年4月17日`, and consistent with Hotspot. I expect the AIX machine isn't configured to use a character set which supports the Chinese output.

**Comment by gaolibj** [comment]
@pshipton That make sense.  But JDK80 got the different result on the same system. Why does the two jdk behave differently. 

bash-4.4$ java DateFormatTest  ==> jdk80
MEDIUM :2020-4-16

**Comment by pshipton** [comment]
@gaolibj yes, Java 8 has a different behavior from Java 11.

**Comment by pshipton** [comment]
I expect the reason why Java 11 is different is http://openjdk.java.net/jeps/252 "Use CLDR Locale Data by Default". The Oracle Java 11 migration guide states "Code that uses locale-sensitive services such as date, time, and number formatting may produce different results with the CLDR locale data."
It also states the following, which does revert the test case to the Java 8 behavior.
"To enable behavior compatible with JDK 8, set the system property java.locale.providers to a value with COMPAT ahead of CLDR, for example, java.locale.providers=COMPAT,CLDR."

**Comment by pshipton** [comment]
@karianna this is not a bug, nor is it related to OpenJ9.

**Comment by gaolibj** [comment]
Thanks all.  No more questions and close the issue.
