### ISSUE TITLE
AdoptOpen JRE 11-07 for Win 64 has doubled in size

### ISSUE THREAD

**Issue by JohnLussmyer** [AdoptOpenJDK/openjdk-support#85]
* **Platform and architecture (e.g. Linux/x64**:
MS WIndows, x64

* **Java version (from "java --version") e.g. 1.8.0_181, 11.0.4+11 etc.**:
11.0.7+10

* **Error messsage and/or description of what is not working as expected**:
The JRE.zip is now 87MB, which is about double what it was in the .6 release.
It appears that it contains full debug information.

**Comment by aahlenst** [comment]
Duplicate of https://github.com/AdoptOpenJDK/openjdk-build/issues/1670. Rebuild is underway.

**Comment by gdams** [comment]
fixed in https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/tag/jdk-11.0.7%2B10.1
