### ISSUE TITLE
SIGSEGV when compiling Maven project

### ISSUE THREAD

**Issue by ajplockyer** [AdoptOpenJDK/openjdk-support#86]
* **Platform and architecture (e.g. Linux/x64**:
MacOS 10.14.6

* **Java version (from "java --version") e.g. 1.8.0_181, 11.0.4+11 etc.**:
14.0+36

* **Variant e.g. HotSpot or OpenJ9**:
HotSpot

* **Have you tested it with other vendors' java**:
No

* **Steps to reproduce**:
Running `mvn clean install` on any reasonably sized Maven project results in errors.

* **Error message and/or description of what is not working as expected**:
```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00000001094f40b8, pid=13677, tid=39427
#
# JRE version: OpenJDK Runtime Environment AdoptOpenJDK (14.0+36) (build 14+36)
# Java VM: OpenJDK 64-Bit Server VM AdoptOpenJDK (14+36, mixed mode, sharing, tiered, compressed oops, g1 gc, bsd-amd64)
# Problematic frame:
# V  [libjvm.dylib+0x4f40b8]  PhaseLive::compute(unsigned int)+0x432
#
# No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /Users/alistair.lockyer/projects/platform/platform/hs_err_pid13677.log

#
# Compiler replay data is saved as:
# /Users/alistair.lockyer/projects/platform/platform/replay_pid13677.log
#
# If you would like to submit a bug report, please visit:
#   https://github.com/AdoptOpenJDK/openjdk-support/issues
#
Abort trap: 6
```

[hs_err_pid13677.log](https://github.com/AdoptOpenJDK/openjdk-support/files/4493448/hs_err_pid13677.log)

**Comment by aahlenst** [comment]
A few minutes ago, we published 14.0.1. Does it happen with it, too?

**Comment by ajplockyer** [comment]
Thanks for the suggestions. I have tested with 14.01 (installed from the link) and I'm seeing a similar error:

```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x0000000111f9e8c1, pid=15106, tid=23555
#
# JRE version: OpenJDK Runtime Environment (14.0.1+7) (build 14.0.1+7)
# Java VM: OpenJDK 64-Bit Server VM (14.0.1+7, mixed mode, sharing, tiered, compressed oops, g1 gc, bsd-amd64)
# Problematic frame:
# V  [libjvm.dylib+0x19e8c1]  _ZN8IndexSet6insertEj+0x19
#
# No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /Users/alistair.lockyer/projects/platform/platform/hs_err_pid15106.log
[thread 7171 also had an error]
```

**Comment by karianna** [comment]
@ajplockyer Ah - looks like a bug that should be reported upstream in that case.  I'll ask for a JBS reporter.

**Comment by aahlenst** [comment]
@ajplockyer If you want this to move forward, please share a project that reproduces this issue. Can be any OSS project.

**Comment by aahlenst** [comment]
I tested with https://github.com/jooq, although I do not know whether that fits the OP's idea of "reasonably sized". Worked without a hitch.

```
$ mvn -version
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /usr/local/Cellar/maven/3.6.3_1/libexec
Java version: 14.0.1, vendor: AdoptOpenJDK, runtime: /Library/Java/JavaVirtualMachines/adoptopenjdk-14.jdk/Contents/Home
Default locale: de_CH, platform encoding: UTF-8
OS name: "mac os x", version: "10.15.4", arch: "x86_64", family: "mac"
```

We'll reopen as soon as we get reproduction steps.

**Comment by aldaris** [comment]
In my case this error happens quite frequently when I'm building a project with a multithreaded build (-T1C). Sadly the project isn't open source...

**Comment by ManuelB** [comment]
I have similair issues: https://bugs.launchpad.net/ubuntu/+source/openjdk-lts/+bug/2054474
