### ISSUE TITLE
OSX drag from Finder has invalid data

### ISSUE THREAD

**Issue by JohnLussmyer** [AdoptOpenJDK/openjdk-support#87]
* **Platform and architecture (e.g. Linux/x64**:
OSX 10.11.6 and several newer versions

* **Java version (from "java --version") e.g. 1.8.0_181, 11.0.4+11 etc.**:
OpenJDK11U-jre_x64_mac_hotspot_11.0.6_10 (and _11)
Also happens with 11.0.7

* **Have you tested it with other vendors' java**:
No

* **Steps to reproduce**:
Drag a file from Finder to a JComponent with a TransferHandler.
When the canImport(final TransferHandler.TransferSupport info) method is called,   The data in the Transferable seems to be invalid.
Transferable.getTransferDataFlavors() returns many Flavors.
Transferable.getTransferData(Flavor) always returns null even if Transferable.isDataFlavorSupported(Flavor) returns true.

Note that this used to work in Java 8 builds, and still works on the Windows builds.

the data is valid when TransferHandler.importData() is called.

**Comment by aahlenst** [comment]
You‘re busy testing, thanks a lot. Could you please try the upstream builds here, too? Makes triage a lot easier.

https://adoptopenjdk.net/upstream.html

**Comment by JohnLussmyer** [comment]
That one will take a while, as we imbed the JRE in our Mac builds. (Notarization makes it even more of a PITA)

**Comment by JohnLussmyer** [comment]
Also, there aren't any OSX builds there.

**Comment by karianna** [comment]
@JohnLussmyer I see you're on 11.0.6 :-) - we just released 11.0.7 today, can you try that one?

**Comment by JohnLussmyer** [comment]
Yes, the problem still exists in 11.0.7

**Comment by aahlenst** [comment]
@JohnLussmyer I did a quick search in JBS and nothing stood out. Could you please share a sample project that reproduces the problem and that we can run? A public GitHub repository would be great. If you have time, test with another OpenJDK provider, e.g. Azul Zulu oder Bell Soft Liberica. If one of them is affected, too, this issue should be ready to report to OpenJDK.

**Comment by aahlenst** [comment]
Closing due tue lack of requested feedback. We'll reopen as soon as we receive further information.
