### ISSUE TITLE
IntelliJ 2020.1 doesn't work with AdoptOpenJDK ?

### ISSUE THREAD

**Issue by hagar-qim** [AdoptOpenJDK/openjdk-support#90]
* **Platform and architecture (e.g. Linux/x64**:  
Windows 10 x46

* **Java version (from "java --version") e.g. 1.8.0_181, 11.0.4+11 etc.**: 
AdoptOpenJDK\jdk-8.0.252.09-hotspot\

* **Variant e.g. HotSpot or OpenJ9**: 
HotSpot

* **Have you tested it with other vendors' java**:

* **Steps to reproduce**: 
upgraded from a 2019.x version of IntelliJ. it fails at startup, even after startup of the machine.
IDEA_JDK_64 was already correctly configured to AdoprOpenJDK  for the 2019 version

* **Error messsage and/or description of what is not working as expected**:
after upgrade of IntelliJ to 2020.1, the IDE won't start and fails with the message : 
"Cannot load a JDK class: com.sun.jdi.Field. please ensure you run the IDE on JDK rather than JRE"

**Comment by aahlenst** [comment]
IntelliJ uses a bundled JDK that deviates from OpenJDK and you should use that. That does not mean that IntelliJ uses the bundled JDK to run your projects (that's configurable).

How to proceed here: Please present a statement by Jetbrains that a stock OpenJDK is supported for running IntelliJ. Then test with https://adoptopenjdk.net/upstream.html. Also check their issue tracker whether it's a problem on their end.

**Comment by hagar-qim** [comment]
ok, I know a bit more. 
I opened a ticket at IntelliJ and their response was to use their  sdk11.The new  IntelliJ 2020.1 doesn't work at all with any sdk8, not even Oracle's (tried this out myself). You need at least java version 11. It seems the upgrade process could have been a bit smarter by detecting that we were using a custom sdk.
2020.01 however, provides a mechanism for changing the sdk , and that (more or less) works. 
I also tried AdoptOpenJdk 11 and 14, and both also seem to work. I haven't tested it exhaustively, but at least the IDE starts, maven does its thing, and I can build.
