### ISSUE TITLE
Adopt OpenJDK latest not working with Oracle SQL Developer

### ISSUE THREAD

**Issue by AJonen** [AdoptOpenJDK/openjdk-support#91]
* **Platform and architecture (e.g. Linux/x64**: Windows Server 2012 64Bit

* **Java version (from "java --version") e.g. 1.8.0_181, 11.0.4+11 etc.**: openjdk version "1.8.0_252"

* **Variant e.g. HotSpot or OpenJ9**: Hotspot

* **Have you tested it with other vendors' java**: Oracle Java

* **Steps to reproduce**: just download Oracle SQL Developer, start the App (sqldeveloper.exe)
 and you will be prompted with the error message.

<img width="456" alt="osql_error" src="https://user-images.githubusercontent.com/64203169/80096690-404c6f00-856a-11ea-8480-5c61f89972af.png">

* **Error messsage and/or description of what is not working as expected**: "Please specify the path to the Java JDK home"

**Comment by aahlenst** [comment]
Is Oracle SQL Developer to supposed to work with OpenJDK? Has it ever worked with OpenJDK (any vendor)? Oracle being Oracle, maybe Oracle SQL Developer is being unreasonable here and refuses to work with any JDK that isn't from Oracle.

**Comment by aahlenst** [comment]
I looked at the release notes for the most recent release: https://www.oracle.com/technetwork/developer-tools/sql-developer/downloads/sqldev-relnotes-194-5908846.html

> Oracle SQL Developer 19.4 release requires Oracle Java 8 or 11/12/13, with a minimum version of 1.8 update 121. 

So, they clearly state that they want Oracle Java.

We can't do anything about that.

**Comment by knasim** [comment]
This really sucks that Oracle would precluded OpenJDK from being used by SQLDeveloper !

**Comment by slominskir** [comment]
FYI - Looks like it might be possible to force SQL Developer to work with AdoptOpenJDK by copying msvcr100.dll from somewhere else.   

https://community.oracle.com/tech/developers/discussion/4333001/essential-solution-for-missing-msvcr100-dll
