### ISSUE TITLE
Confirm if Tomcat version 9.0.6 is supported with Adopt OpenJDK

### ISSUE THREAD

**Issue by mkoribilli** [AdoptOpenJDK/openjdk-support#93]
* **Platform and architecture (e.g. Linux/x64**: Window 2016 server

* **Java version (from "java --version") e.g. 1.8.0_181, 11.0.4+11 etc.**: Oracle Java 1.8

* **Variant e.g. HotSpot or OpenJ9**: Adopt OpenJDK 9

* **Have you tested it with other vendors' java**: No

* **Steps to reproduce**:

* **Error messsage and/or description of what is not working as expected**:

**Comment by mkoribilli** [comment]
We have Tomcat 9.0.6 and would like to move from Oracle Java to Adopt OpenJDK would like to know the detailed support matrix of Adopt OpenJDK + Tomcat

**Comment by aahlenst** [comment]
We don't have support/compatibility charts per product, sorry.

At work, we have multiple services that use Tomcat with various versions of AdoptOpenJDK. Works without a hitch.
