### ISSUE TITLE
EXCEPTION_ACCESS_VIOLATION OpenJDK 11.0.1+13 when opening DirectoryDialog or FileDialog

### ISSUE THREAD

**Issue by becvar** [AdoptOpenJDK/openjdk-support#95]
**Platform:**
Windows 10

**Architecture:**
64 bit Build 17134 (10.0.17134.1)

We have consistent JVM crash on our test machine when opening  DirectoryDialog or FileDialog.

So far we managed to reproduce the issue only on our test machines and only when our product (large Eclipse based application) is run using QFTest GUI test tool (https://www.qfs.de/en.html). 

Crash report is attached. 
[hs_err_AdoptOpenJDK.log](https://github.com/AdoptOpenJDK/openjdk-build/files/2738434/hs_err_AdoptOpenJDK.log)

Issue is also reproducible on Oracle JDK _(Java(TM) SE Runtime Environment (11.0.1+13) (build 11.0.1+13-LTS))_
[hs_err_OracleJRE.log](https://github.com/AdoptOpenJDK/openjdk-build/files/2738433/hs_err_OracleOpenJDK.log)

**Comment by aahlenst** [comment]
Closing due to lack of requested feedback. Besides, the problem description makes it sound like it isn't the fault of the JDK.
