### ISSUE TITLE
Open J9 Hardened version not signed properly

### ISSUE THREAD

**Issue by Ram-Krishnamurthy** [AdoptOpenJDK/openjdk-support#99]
* **Platform and architecture (e.g. Linux/x64**: Mac Catalina

* **Java version (from "java --version") e.g. 1.8.0_181, 11.0.4+11 etc.**: OpenJDK8U-jre_x64_mac_openj9_macosXL_8u252b09_openj9-0.20.0.tar.gz

* **Variant e.g. HotSpot or OpenJ9**:  Open J9 (Hardened) Large Heap

* **Have you tested it with other vendors' java**: No

* **Steps to reproduce**: See below

* **Error messsage and/or description of what is not working as expected**:
We used the Open J9 hardened version released last week and we got this error from Apple during notarization:
{ "severity": "error", "code": null, "path": "/jre/Contents/MacOS/libjli.dylib", "message": "The signature of the binary is invalid.", "docUrl": null, "architecture": "x86_64" }
It says libjli.dylib has no signature, but I believe its a link file?
We also tried this command
File downloaded - OpenJDK8U-jre_x64_mac_openj9_macosXL_8u252b09_openj9-0.20.0.tar.gz* unzipped it to the folder jdk8u252-b09-jre-j9 and then checked signature -
codesign -vvvv jdk8u252-b09-jre-j9jdk8u252-b09-jre-j9/: code has no resources but signature indicates they must be present

Looks like these binaries were not signed. This error does not happen with the Hotspot version. Only happens with Open J9 (large heap)

**Comment by aahlenst** [comment]
Did you sign the bundled binaries as described in https://medium.com/adoptopenjdk/adoptopenjdk-8u252-11-0-7-and-14-0-1-available-df8617d182df, section "Notarization and Hardened Runtime Support on macOS"?

**Comment by Ram-Krishnamurthy** [comment]
We didn't have to do that for Hotspot. Is that something unique to Open J9?

**Comment by aahlenst** [comment]
You have to re-sign the bundle, see https://github.com/AdoptOpenJDK/openjdk-support/issues/97.

@gdams: Are there differences between OpenJ9 and HotSpot in that regard?

**Comment by DanHeidinga** [comment]
@keithc-ca can you take a look at this?

**Comment by keithc-ca** [comment]
I downloaded the latest b09.2 `.tar.gz` [package](https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u252-b09.2_openj9-0.20.0/OpenJDK8U-jdk_x64_mac_openj9_macosXL_8u252b09_openj9-0.20.0.tar.gz): the gatekeeper will not allow execution.
Downloading and installing the `.pkg` [package](https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u252-b09.2_openj9-0.20.0/OpenJDK8U-jdk_x64_mac_openj9_macosXL_8u252b09_openj9-0.20.0.pkg) works for me. 

@Ram-Krishnamurthy Can you try the latest `.pkg`? There were problems with the `b09` and `b09.1` builds.

**Comment by Ram-Krishnamurthy** [comment]
Thanks .pkg works.

**Comment by keithc-ca** [comment]
The [release notes](https://medium.com/adoptopenjdk/adoptopenjdk-8u252-11-0-7-and-14-0-1-available-df8617d182df) say: 'only pkg installers are notarized'.

@Ram-Krishnamurthy noted that the pkg installer works: this should be closed.
